'use client';
import dynamic from 'next/dynamic';
import {useEffect,useMemo,useState} from 'react';
import type {FishingMapEntry} from '@/lib/fishing-map-data';
import {markerKinds} from '@/lib/spot-markers';
import {englishSpotTypes,prefectureNames,facilityEnglish} from '@/lib/i18n/common';
import type {SpotPrimaryType} from '@/lib/spot-classification';
import SpotFavorite,{useSpotFavorites} from '../SpotFavorite';
import s from '../SpotMap.module.css';
const Map=dynamic(()=>import('../InteractiveSpotMap'),{ssr:false,loading:()=> <p>Loading interactive map… You can use the location list below.</p>});
const noOp=()=>{};const emptyShops:never[]=[];const emptyActivity={};
export default function MapExplorer({entries,fish,methods}:{entries:FishingMapEntry[];fish:Record<string,string>;methods:Record<string,string>}){
 const [query,setQuery]=useState(''),[pref,setPref]=useState(''),[fishId,setFish]=useState(''),[method,setMethod]=useState('');const [types,setTypes]=useState<SpotPrimaryType[]>(Object.keys(markerKinds) as SpotPrimaryType[]),[savedOnly,setSaved]=useState(false),[selected,setSelected]=useState<string>(),[limit,setLimit]=useState(24),[initialized,setInitialized]=useState(false);
 const favorites=useSpotFavorites();
 useEffect(()=>{const q=new URLSearchParams(window.location.search);setQuery(q.get('q')??'');setPref(q.get('prefecture')??'');setFish(q.get('fish')??'');setMethod(q.get('method')??'');setInitialized(true);},[]);
 useEffect(()=>{if(!initialized)return;const url=new URL(window.location.href);for(const [key,value] of Object.entries({q:query,prefecture:pref,fish:fishId,method})){if(value)url.searchParams.set(key,value);else url.searchParams.delete(key);}window.history.replaceState(null,'',url.pathname+url.search+url.hash);},[initialized,query,pref,fishId,method]);
 const filtered=useMemo(()=>entries.filter(e=>types.includes(e.primaryType as SpotPrimaryType)&&(!pref||e.prefecture===pref)&&(!savedOnly||favorites.includes(e.slug))&&(!fishId||e.fishSlugs?.includes(fishId))&&(!method||e.methodSlugs?.includes(method))&&(!query||`${e.name} ${e.slug} ${prefectureNames[e.prefecture??'']} ${e.fish.join(' ')}`.toLowerCase().includes(query.toLowerCase()))),[entries,types,pref,savedOnly,favorites,fishId,method,query]);
 const active=filtered.find(e=>e.slug===selected);
 return <><div className="enFilters"><label>Place or fish<input value={query} onChange={e=>{setQuery(e.target.value);setLimit(24)}} placeholder="Wakayama, Japanese place name…"/></label><label>Prefecture<select value={pref} onChange={e=>setPref(e.target.value)}><option value="">All Japan</option>{Object.entries(prefectureNames).map(([jp,en])=><option key={jp} value={jp}>{en}</option>)}</select></label><label>Fish<select value={fishId} onChange={e=>setFish(e.target.value)}><option value="">All fish</option>{Object.entries(fish).sort((a,b)=>a[1].localeCompare(b[1])).map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></label><label>Method<select value={method} onChange={e=>setMethod(e.target.value)}><option value="">All methods</option>{Object.entries(methods).map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></label></div><p role="status">{filtered.length} locations{savedOnly&&!favorites.length?' — no saved spots yet.':''}</p><Map locale="en" activity={emptyActivity} boundaryPrefectures={pref?[pref]:[]} favorites={favorites} favoritesOnly={savedOnly} onFavoritesChange={setSaved} shopsOn={false} onShopsChange={noOp} shops={emptyShops} onShopSelect={noOp} entries={filtered} selected={active?.slug} onSelect={setSelected} selectedTypes={types} onTypesChange={setTypes} fitKey={`en|${pref}|${query}|${fishId}|${method}|${types.join(',')}|${savedOnly}`} preview={active?<section className={s.mapPreview} data-spot-preview aria-label="Selected location"><button className={s.previewClose} aria-label="Close preview" onClick={()=>setSelected(undefined)}>×</button><small>{prefectureNames[active.prefecture??'']} · {englishSpotTypes[active.primaryType as SpotPrimaryType]}</small><h2 lang="ja">{active.name}</h2><p>{active.fish.slice(0,3).join(' · ')}</p><small>Parking: {facilityEnglish(active.parking)} · Toilet: {facilityEnglish(active.toilet)}</small><div className={s.previewActions}><SpotFavorite locale="en" slug={active.slug} name={active.name}/><a href={`/en/spots/${active.slug}`}>View details →</a></div></section>:null}/><div className="enMapList"><h2>Locations</h2><p className="enMuted">Original Japanese place names are retained so you can match signs and show them to local staff.</p>{filtered.slice(0,limit).map(e=><a key={e.slug} href={`/en/spots/${e.slug}`}><strong lang="ja">{e.name}</strong> — {prefectureNames[e.prefecture??'']} · {englishSpotTypes[e.primaryType as SpotPrimaryType]}</a>)}{filtered.length>limit&&<button className="enButton" onClick={()=>setLimit(n=>n+24)}>Show more locations</button>}</div></>;
}
