import Link from 'next/link';
import s from './gear.module.css';
export const metadata={title:'釣具｜UOLINK'};
const targets=[
 {fish:'タチウオ',icon:'⚔️',href:'/fish/tachiuo',routes:[{place:'🚤 船',method:'/methods/tachiuo-tenya',name:'船テンヤ',items:'専用竿・両軸/電動・PE1.5〜3号・40号前後テンヤ'},{place:'⚓ 堤防',method:'/methods',name:'ウキ・引き釣り',items:'磯/ルアー竿・スピニング・ワイヤー/太ハリス・テンヤ/ウキ'}],amazon:'https://link.amazon/B01XtTirB'},
 {fish:'マアジ',icon:'🐟',href:'/fish/aji',routes:[{place:'⚓ 堤防',method:'/methods/sabiki',name:'サビキ',items:'万能竿・スピニング・サビキ・カゴ'},{place:'🚤 船',method:'/methods',name:'船アジ',items:'船竿・両軸/電動・胴突き/サビキ・オモリ'}]},
 {fish:'マダイ',icon:'🔴',href:'/fish/madai',routes:[{place:'🚤 船',method:'/methods/tai-rubber',name:'タイラバ',items:'タイラバ竿・小型両軸・PE0.6〜1号・ヘッド'},{place:'⚓ 堤防',method:'/methods',name:'カゴ・フカセ',items:'磯/遠投竿・スピニング・ウキ・ハリス'}]},
 {fish:'ブリ',icon:'💨',href:'/fish/buri',routes:[{place:'🚤 船',method:'/methods/nomase',name:'船ノマセ',items:'青物船竿・両軸/電動・PE3号前後・泳がせ仕掛け'},{place:'⚓ 堤防',method:'/methods/nomase',name:'堤防ノマセ',items:'磯/遠投竿・4000〜6000番・PE2〜4号・泳がせ仕掛け'}]}
];
export default function Page(){return <div className="section pageTop"><div className="pageHero"><span>FISHING GEAR</span><h1>釣具は「魚 × 場所」から選ぶ。</h1><p>狙う魚と釣る場所が決まれば、必要なロッド・リール・ライン・仕掛けを絞り込めます。</p></div><div className="adNotice">このページにはAmazonアソシエイト等のアフィリエイトリンクを含みます。</div><div className={s.targetGrid}>{targets.map(x=><article className={s.target} key={x.fish}><div className={s.targetHead}><span>{x.icon}</span><div><small>TACKLE GUIDE</small><h2>{x.fish}の釣具</h2><p>釣り方に合う道具をチェック</p></div></div>{x.routes.map(r=><div className={s.route} key={r.place}><div><b>{r.place}｜{r.name}</b><p>{r.items}</p></div><Link href={r.method}>この釣り方へ →</Link></div>)}{x.amazon&&<a className={s.amazonCard} href={x.amazon} target="_blank" rel="sponsored noopener noreferrer"><div className={s.amazonVisual}>🎣</div><div><small>Amazon</small><b>船タチウオテンヤ用ロッド</b><span>商品を見る →</span></div></a>}<div className={s.actions}><Link href={x.href}>魚の特徴を見る →</Link></div></article>)}</div></div>}
