// Read-only check against a production build served on localhost:3132.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
const slugs=['ika-metal-upper-or-lower','nomase-bait-hook-position','fukase-gandama-moving','sayori-hook-behind-float','haze-float-too-deep','reel-rinse-drag-reset','jigging-first-bottom-reset','fly-line-feet-tangle','fish-simmer-pan-size','bass-crank-cast-distance-depth','trip-bag-order-rain'];
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE});try{
for(const width of [1280,390]){const context=await browser.newContext({viewport:{width,height:844},isMobile:width===390,hasTouch:width===390});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
for(const slug of slugs){const r=await page.goto('http://localhost:3132/guide/'+slug);assert.equal(r.status(),200,slug);await page.locator('h1').waitFor();assert.equal(await page.locator('table').count(),1,slug);assert.ok((await page.locator('link[rel=canonical]').getAttribute('href')).endsWith('/guide/'+slug));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),slug);assert.ok(await page.getByRole('link',{name:'釣り方の全体を確認する'}).count());}
await page.screenshot({path:`/tmp/uolink-505-guide-${width}.png`,fullPage:true});
await page.goto('http://localhost:3132/guide/ika-metal-upper-or-lower');assert.equal(await page.getByRole('link',{name:'対象魚・釣り方に合う釣り場を探す →'}).getAttribute('href'),'/spots?fish=kensakiika');await page.getByRole('link',{name:'釣り方の全体を確認する'}).click();await page.waitForURL('**/guide/kensakiika-starting-guide');
await page.goto('http://localhost:3132/guide');const search=page.getByRole('textbox',{name:'知りたいこと'});await search.fill('スプール');await page.getByRole('button',{name:'検索',exact:true}).click();await page.waitForURL('**/guide?q=*');assert.ok((await page.locator('main').innerText()).includes('スプール'));await search.fill('ムニエル');await page.getByRole('button',{name:'検索',exact:true}).click();await page.getByRole('link').filter({hasText:'魚のムニエルは粉を先に付けて置いておいてよい？'}).first().click();await page.waitForURL('**/guide/fish-meuniere-flour-timing');assert.deepEqual(errors,[]);console.log('PASS',width,'11 groups, table/canonical/overflow, parent navigation, MAP link, index search');await context.close();}
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
