import Link from 'next/link';
import {gearKindLabels,gearSubtypeLabels,getGearSubtype,gearCatalog,filterGear,paginateGear} from '@/lib/gear-catalog';
import {fishCatalog} from '@/lib/fish-registry';
import {getMethod} from '@/lib/method-registry';
import GearProductVisual from '@/components/GearProductVisual';
import s from '@/components/GearCatalog.module.css';
export const metadata={title:'釣具図鑑｜ロッド・リール・ルアー・用品を選ぶ',description:'メーカー・種類・対象魚・釣り方からロッド・リール・ルアー・エギ・ライン・クーラー・小物を探すUOLINK釣具図鑑。仕様、ラインの組み合わせ、関連する釣法を確認できます。',alternates:{canonical:'/gear'}};
export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const raw=await searchParams;const q=Object.fromEntries(['q','brand','kind','subtype','method','fish'].map(k=>[k,typeof raw[k]==='string'?raw[k]:'']));const products=filterGear(q);const pagination=paginateGear(products,typeof raw.page==='string'?raw.page:undefined);const pageUrl=(page:number)=>{const params=new URLSearchParams(Object.entries(q).filter(([,v])=>!!v));params.set('page',String(page));return `/gear?${params}`};
 const methods=[...new Set(gearCatalog.flatMap(p=>p.methods))].map(getMethod).filter(m=>!!m);const fish=fishCatalog.filter(f=>gearCatalog.some(p=>p.fish.includes(f.slug)));
 return <div className="section pageTop"><div className="pageHero"><span>GEAR ENCYCLOPEDIA</span><h1>釣具図鑑</h1><p>使いたい道具から、次の釣りへ。</p></div><p className={s.intro}>ロッド・リール・ルアーからライン・クーラー・小物まで。対応する魚、釣り方、ラインや小物の組み合わせまで確認できます。</p>
 <form action="/gear" className={s.filters}><label>製品名・メーカー<input name="q" defaultValue={q.q} placeholder="例：ソルパラ、2500" maxLength={80}/></label><label>種類<select name="kind" defaultValue={q.kind}><option value="">すべて</option>{Object.entries(gearKindLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>細分類<select name="subtype" defaultValue={q.subtype}><option value="">すべて</option>{Object.entries(gearSubtypeLabels).filter(([id])=>gearCatalog.some(p=>getGearSubtype(p)===id)).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>メーカー<select name="brand" defaultValue={q.brand}><option value="">すべて</option>{[...new Set(gearCatalog.map(p=>p.brand))].map(b=><option key={b}>{b}</option>)}</select></label><label>対象魚<select name="fish" defaultValue={q.fish}><option value="">すべて</option>{fish.map(f=><option value={f.slug} key={f.slug}>{f.name}</option>)}</select></label><label>釣り方<select name="method" defaultValue={q.method}><option value="">すべて</option>{methods.map(m=><option value={m.slug} key={m.slug}>{m.name}</option>)}</select></label><button>絞り込む</button><Link href="/gear">解除</Link></form>
 <p>{products.length}製品</p><div className={s.grid}>{pagination.items.map(p=><article key={p.slug} className={s.card}><Link href={`/gear/${p.slug}`}><GearProductVisual product={p} compact/><div className={s.content}><small>{p.brand} · {gearKindLabels[p.kind]}{getGearSubtype(p)&&` / ${gearSubtypeLabels[getGearSubtype(p)!]}`}</small><h2>{p.name}</h2><p>{p.summary}</p><span>仕様・組み合わせを見る →</span></div></Link></article>)}</div>{!products.length&&<p>該当する製品はまだ登録されていません。条件を減らすか、<Link href={`/gear/preparation${q.method?`?method=${encodeURIComponent(q.method)}`:''}`}>釣法別の道具選び</Link>をご覧ください。</p>}
 <nav className={s.pagination} aria-label="釣具一覧のページ">{pagination.page>1&&<Link href={pageUrl(pagination.page-1)}>← 前へ</Link>}<span>{pagination.page} / {pagination.totalPages}</span>{pagination.page<pagination.totalPages&&<Link href={pageUrl(pagination.page+1)}>次へ →</Link>}</nav><section className={s.section}><h2>準備や釣り方から選ぶ</h2><div className={s.links}><Link href="/methods">釣り方・仕掛け図解 →</Link><Link href="/gear/preparation">基本装備・魚別タックル →</Link><Link href="/guide/fishing-first-checklist">初めての持ち物 →</Link></div><div className={s.legacy}>{['tachiuo','aji','madai','buri','kisu','kasago','saba','kawahagi','hirame','aoriika'].map(id=><a id={id} key={id} href={`/gear/preparation#${id}`}>{fishCatalog.find(f=>f.slug===id)?.name??id}の道具 →</a>)}</div></section></div>
}
