import {createHmac,createHash} from 'node:crypto';
import type {CatchReport} from '../catches/types';
import {HttpError} from './request';
export function backendConfigured(){return !!(process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.SUPABASE_SERVICE_ROLE_KEY);}
export function catchStoreReady(){return backendConfigured()&&process.env.CATCH_REPORTS_ENABLED==='true';}
function config(){if(!backendConfigured())throw new HttpError(503,'公開釣果は準備中です。端末内の記録は利用できます。');return {url:process.env.NEXT_PUBLIC_SUPABASE_URL!.replace(/\/$/,''),key:process.env.SUPABASE_SERVICE_ROLE_KEY!};}
export async function storeRequest(path:string,init:RequestInit={}){const {url,key}=config();const response=await fetch(url+path,{...init,headers:{apikey:key,Authorization:`Bearer ${key}`,...init.headers},cache:'no-store',signal:AbortSignal.timeout(12000)});if(!response.ok)throw new HttpError(503,'公開釣果の保存先へ接続できません。端末内の記録は保持されています。');return response;}
export async function takeQuota(request:Request,bucket:string,limit:number){const {key}=config();const ip=request.headers.get('x-vercel-forwarded-for')??request.headers.get('x-forwarded-for')?.split(',')[0]??'unknown';const hash=createHmac('sha256',key).update(bucket+':'+ip).digest('hex');const r=await storeRequest('/rest/v1/rpc/uolink_take_quota',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({p_key:hash,p_limit:limit})});if(!(await r.json()))throw new HttpError(429,'送信回数の上限です。1時間ほど空けてください。');}
export async function publishCatch(report:CatchReport,token:string,photo?:Buffer){const {photo:discard,...payload}=report;void discard;const tokenHash=createHash('sha256').update(token).digest('hex');
 const existing=await storeRequest(`/rest/v1/catch_reports?id=eq.${report.id}&select=token_hash,status`);const rows=await existing.json();if(rows.length){if(rows[0].token_hash!==tokenHash)throw new HttpError(409,'記録IDが重複しています。');return rows[0].status;}
 const photoPath=photo?`${report.id}.jpg`:null;
 if(photo)await storeRequest(`/storage/v1/object/catch-photos/${photoPath}`,{method:'POST',headers:{'Content-Type':'image/jpeg','x-upsert':'true'},body:new Uint8Array(photo)});
 try{await storeRequest('/rest/v1/catch_reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:report.id,spot_slug:report.spotSlug,fish_slug:report.fishSlug,caught_on:report.date,time_band:report.time,method_slug:report.methodSlug??null,payload,photo_path:photoPath,token_hash:tokenHash,status:'pending'})});}catch(error){if(photoPath)await storeRequest('/storage/v1/object/catch-photos',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({prefixes:[photoPath]})}).catch(()=>{});throw error;}return 'pending';
}
export async function recentCatches(spotSlug:string,offset=0){const r=await storeRequest(`/rest/v1/catch_reports?spot_slug=eq.${encodeURIComponent(spotSlug)}&status=eq.approved&order=caught_on.desc,created_at.desc&limit=10&offset=${offset}&select=payload,photo_path`);const rows=await r.json() as {payload:CatchReport;photo_path:string|null}[];return Promise.all(rows.map(async row=>{let photo:string|undefined;if(row.photo_path){const signed=await storeRequest(`/storage/v1/object/sign/catch-photos/${row.photo_path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expiresIn:600})});const {signedURL}=await signed.json();photo=config().url+'/storage/v1'+signedURL;}return {...row.payload,photo};}));}
export async function removePublicCatch(id:string,token:string){const hash=createHash('sha256').update(token).digest('hex');const r=await storeRequest(`/rest/v1/catch_reports?id=eq.${id}&token_hash=eq.${hash}`,{method:'DELETE',headers:{Prefer:'return=representation'}});const rows=await r.json();if(rows.length)await storeRequest('/storage/v1/object/catch-photos',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({prefixes:[`${id}.jpg`]})});}
