const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),Module=require('module'),ts=require('typescript');
const root=path.resolve(__dirname,'..'),resolve=Module._resolveFilename;Module._resolveFilename=function(s,...a){return resolve.call(this,s.startsWith('@/')?path.join(root,s.slice(2)):s,...a)};
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{esModuleInterop:true,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,f);
const {fishSpecies}=require('../lib/fish-species'),{fishCatalog}=require('../lib/fish-registry'),{getSpeciesTableGuide}=require('../lib/fish-species/define'),{fishingMapEntries}=require('../lib/fishing-map-data'),{markerKind,clusterCellSize,clusterPoints}=require('../lib/spot-markers');
test('all species have explicit representative dishes, raw safeguards and full new profiles',()=>{for(const f of fishSpecies){if(!f.cooking){assert.ok(f.hazard?.cookingEnabled===false||(f.cookingOmission?.note&&f.cookingOmission.sources.length),f.base.slug);continue;}assert.ok(f.representativeRecipes?.length);assert.ok(f.representativeRecipes.length<=4);const cards=getSpeciesTableGuide(f).dishes;assert.deepEqual(cards.map(c=>c.recipe),f.representativeRecipes);for(const r of f.cooking.recipes){assert.ok(r.ingredients.length>=2&&r.steps.length>=3);if(['yamame','wakasagi','unagi','ayu','amago','nijimasu'].includes(f.base.slug))assert.notEqual(r.preparation,'raw');}}
for(const slug of ['unagi','yamame','wakasagi']){const f=fishCatalog.find(f=>f.slug===slug);assert.ok(f.cooking.recipes.length>=4);assert.ok(f.detail.safety.length>20&&f.launch.identify.length>=3);assert.ok(f.media.image);}
for(const slug of ['kawahagi','umazurahagi','hirame','kanpachi','sayori','akamutsu'])assert.equal(fishSpecies.find(f=>f.base.slug===slug).representativeRecipes[0],'sashimi');});
test('map classifies managed facilities and filters before clustering with no lost points',()=>{for(const slug of ['amagasaki-uoturi','naruohama'])assert.equal(markerKind(fishingMapEntries.find(s=>s.slug===slug)),'sea-park');for(const e of fishingMapEntries)assert.ok(e.primaryType&&Array.isArray(e.features));const boats=fishingMapEntries.filter(s=>markerKind(s)==='boat');assert.ok(boats.length);const clustered=clusterPoints(boats,()=>({x:0,y:0}),undefined,clusterCellSize(8));assert.deepEqual(clustered.flat().map(s=>s.slug),boats.map(s=>s.slug));assert.ok(clusterCellSize(8)<30);assert.equal(clusterPoints([],()=>({x:0,y:0})).length,0);});
test('new map entries have evidence and every relationship resolves',()=>{const {platformMapExpansion}=require('../lib/fishing-map-20260917'),{getGuide}=require('../lib/all-guides'),{methodDetails}=require('../lib/method-registry');assert.equal(platformMapExpansion.length,6);for(const s of platformMapExpansion){assert.ok(s.sources.length&&s.verifiedAt&&s.positionNote&&s.officialUrl);for(const f of s.fishSlugs??[])assert.ok(fishCatalog.some(x=>x.slug===f));for(const m of s.methodSlugs??[])assert.ok(methodDetails[m],m);for(const g of s.guideSlugs??[])assert.ok(getGuide(g),g);}});
test('sharing cards cover public content with absolute JPEG images below 5MB',()=>{const {allGuides}=require('../lib/all-guides'),{pageSharing}=require('../lib/page-sharing'),cards=require('../lib/sharing-images.json');for(const route of ['/', '/fish','/guide','/spots','/identify',...allGuides.map(g=>'/guide/'+g.slug),...fishCatalog.map(f=>'/fish/'+f.slug),...fishingMapEntries.map(s=>'/spots/'+s.slug)]){assert.ok(cards[route],route);const m=pageSharing(route,'title','description'),img=m.openGraph.images[0];assert.equal(m.alternates.canonical,'https://uolink.vercel.app'+route);assert.equal(img.type,'image/jpeg');assert.equal(img.width,1200);assert.equal(img.height,630);assert.equal(m.twitter.card,'summary_large_image');const b=fs.readFileSync(path.join(root,'public',cards[route]));assert.ok(b.length<5e6);assert.equal(b.readUInt16BE(0),0xffd8);}});
const {parseCatch,validDeleteToken}=require('../lib/catches/types');const allowed={fish:new Set(['aji']),spots:new Set(['naruohama']),methods:new Set(['sabiki'])};const report={id:'12345678-1234-4234-8234-123456789012',source:'real',spotSlug:'naruohama',fishSlug:'aji',count:2,date:'2026-09-16',time:'morning',methodSlug:'sabiki',rig:'4号',comment:'底の少し上'};
test('real catch schema rejects game data, future dates, impossible values and unknown links',()=>{assert.equal(parseCatch(report,allowed,new Date('2026-09-17')).count,2);for(const patch of [{source:'quest'},{count:-1},{count:1.5},{sizeCm:NaN},{date:'2026-02-31'},{date:'2030-01-01'},{fishSlug:'missing'},{spotSlug:'missing'},{methodSlug:'missing'},{comment:'x'.repeat(501)}])assert.throws(()=>parseCatch({...report,...patch},allowed,new Date('2026-09-17')));assert.ok(validDeleteToken(report.id));assert.ok(!validDeleteToken('../bad'));});
test('JPEG server validation strips metadata and rejects invalid images',()=>{const {cleanJpeg}=require('../lib/server/request');const cards=require('../lib/sharing-images.json');const original=fs.readFileSync(path.join(root,'public',cards['/']));const exif=Buffer.from([255,225,0,10,69,120,105,102,0,0,1,2]);const image=Buffer.concat([original.subarray(0,2),exif,original.subarray(2)]);const clean=cleanJpeg('data:image/jpeg;base64,'+image.toString('base64'));assert.ok(!clean.includes(Buffer.from('Exif')));assert.equal(clean.readUInt16BE(0),0xffd8);assert.throws(()=>cleanJpeg('data:image/png;base64,AAAA'));assert.throws(()=>cleanJpeg('data:image/jpeg;base64,AAAA'));});
test('identification accepts multiple registered candidates, never hallucinated slugs',()=>{const {validateIdentification}=require('../lib/fish-identification');const v={candidates:[{slug:'aji',confidence:'medium',reason:'ゼイゴ状の特徴',check:'尾の付け根'}],uncertain:'近縁種との区別が必要'};assert.equal(validateIdentification(v,new Set(['aji'])).candidates.length,1);assert.throws(()=>validateIdentification({...v,candidates:[{...v.candidates[0],slug:'unknown'}]},new Set(['aji'])));assert.deepEqual(validateIdentification({candidates:[],uncertain:'魚が写っていません'},new Set(['aji'])).candidates,[]);});
test('catch API persists pending data, exposes only approved, and identification parses mocked provider output',async()=>{
const env={SUPABASE_URL:process.env.SUPABASE_URL,NEXT_PUBLIC_SUPABASE_URL:process.env.NEXT_PUBLIC_SUPABASE_URL,SUPABASE_SERVICE_ROLE_KEY:process.env.SUPABASE_SERVICE_ROLE_KEY,CATCH_REPORTS_ENABLED:process.env.CATCH_REPORTS_ENABLED,OPENAI_API_KEY:process.env.OPENAI_API_KEY,FISH_IDENTIFY_MODEL:process.env.FISH_IDENTIFY_MODEL,FISH_IDENTIFY_ENABLED:process.env.FISH_IDENTIFY_ENABLED};Object.assign(process.env,{SUPABASE_URL:'https://server.example.invalid',NEXT_PUBLIC_SUPABASE_URL:'https://legacy.example.invalid',SUPABASE_SERVICE_ROLE_KEY:'test-only',CATCH_REPORTS_ENABLED:'true',OPENAI_API_KEY:'test-only',FISH_IDENTIFY_MODEL:'test-vision',FISH_IDENTIFY_ENABLED:'true'});const originalFetch=global.fetch;const calls=[];global.fetch=async(url,init={})=>{calls.push({url:String(url),init});if(String(url).includes('/rpc/'))return Response.json(true);if(String(url).includes('/responses'))return Response.json({output:[{content:[{type:'output_text',text:JSON.stringify({candidates:[{slug:'aji',confidence:'low',reason:'銀色の体',check:'ゼイゴを確認'}],uncertain:'参考情報'})}]}]});return Response.json([]);};
try{const api=require('../app/api/catches/route'),req=new Request('https://uolink.vercel.app/api/catches',{method:'POST',headers:{origin:'https://uolink.vercel.app','content-type':'application/json'},body:JSON.stringify({report,deleteToken:report.id,consent:true})});assert.equal((await api.POST(req)).status,202);const post=calls.find(c=>c.url.endsWith('/rest/v1/catch_reports')&&c.init.method==='POST');assert.ok(post.url.startsWith('https://server.example.invalid/'));assert.equal(JSON.parse(post.init.body).status,'pending');assert.ok(!post.init.body.includes('deleteToken'));const get=await api.GET(new Request('https://uolink.vercel.app/api/catches?spot=naruohama'));assert.equal(get.status,200);assert.ok(calls.some(c=>c.url.includes('status=eq.approved')&&c.url.includes('limit=10')));const cards=require('../lib/sharing-images.json'),image='data:image/jpeg;base64,'+fs.readFileSync(path.join(root,'public',cards['/'])).toString('base64');const identify=require('../app/api/identify/route');const res=await identify.POST(new Request('https://uolink.vercel.app/api/identify',{method:'POST',headers:{origin:'https://uolink.vercel.app','content-type':'application/json'},body:JSON.stringify({image,consent:true})}));assert.equal(res.status,200);assert.equal((await res.json()).candidates[0].slug,'aji');const provider=calls.find(c=>c.url.includes('/responses'));assert.equal(JSON.parse(provider.init.body).store,false);assert.equal(JSON.parse(provider.init.body).text.format.strict,true);
}finally{global.fetch=originalFetch;for(const [k,v]of Object.entries(env)){if(v===undefined)delete process.env[k];else process.env[k]=v;}}
});
test('disabled external services return honest availability without making network requests',async()=>{const api=require('../app/api/identify/route');const prior=process.env.FISH_IDENTIFY_ENABLED;delete process.env.FISH_IDENTIFY_ENABLED;try{assert.equal((await (await api.GET()).json()).available,false);const res=await api.POST(new Request('https://uolink.vercel.app/api/identify',{method:'POST',headers:{origin:'https://uolink.vercel.app','content-type':'application/json'},body:'{}'}));assert.equal(res.status,503);}finally{if(prior!==undefined)process.env.FISH_IDENTIFY_ENABLED=prior;}});
test('river expansion connects complete species, approved locations and parent guides',()=>{const {riverMapExpansion}=require('../lib/fishing-map-river-expansion'),{getGuide,getParentGuide}=require('../lib/all-guides'),{questFish}=require('../lib/quest/catalog');const f=fishSpecies.find(s=>s.base.slug==='iwana');assert.ok(f);assert.equal(f.cooking.recipes.length,4);assert.ok(f.cooking.recipes.every(r=>r.preparation==='cooked'));assert.ok(fs.existsSync(path.join(root,'public',f.media.image)));assert.ok(questFish.some(s=>s.slug==='iwana'));assert.ok(getGuide('iwana-first-trip'));assert.equal(getParentGuide('wakasagi-dome-reservation-check').slug,'wakasagi-first-trip');assert.equal(riverMapExpansion.length,3);for(const spot of riverMapExpansion){assert.equal(spot.primaryType,'boat');assert.ok(spot.lat&&spot.lng&&spot.sources.length>=2);for(const slug of spot.fishSlugs)assert.ok(fishCatalog.some(f=>f.slug===slug));for(const slug of spot.guideSlugs)assert.ok(getGuide(slug));}for(const spot of fishingMapEntries.filter(s=>s.fish.includes('イワナ')))assert.ok(spot.fishSlugs.includes('iwana'));assert.equal(new Set(fishingMapEntries.map(s=>s.slug)).size,fishingMapEntries.length);});
test('national map growth preserves sourced positions, classification and resolvable links',()=>{const {nationalMapGrowth}=require('../lib/fishing-map-national-growth'),{getGuide}=require('../lib/all-guides'),{methodDetails}=require('../lib/method-registry');assert.equal(nationalMapGrowth.length,20);assert.equal(new Set(fishingMapEntries.map(s=>s.slug)).size,fishingMapEntries.length);for(const s of nationalMapGrowth){assert.ok(s.lat>24&&s.lat<46&&s.lng>122&&s.lng<146,s.slug);assert.ok(s.sources.length&&s.officialUrl&&s.verifiedAt&&s.positionNote,s.slug);assert.ok(s.note.length>30&&s.caution.length>=2,s.slug);for(const g of s.guideSlugs??[])assert.ok(getGuide(g),g);for(const m of s.methodSlugs??[])assert.ok(methodDetails[m],m);const entry=fishingMapEntries.find(e=>e.slug===s.slug);assert.equal(entry.primaryType,require('../lib/spot-classification').spotPrimaryType(s));for(const f of entry.fishSlugs??[])assert.ok(fishCatalog.some(x=>x.slug===f),f);}const winter=nationalMapGrowth.find(s=>s.slug==='shinotsuko-tappu');assert.match(winter.status,/冬季/);assert.equal(nationalMapGrowth.find(s=>s.slug==='ariake-west-pier-park').parking,false);for(const s of nationalMapGrowth.filter(s=>s.terrain==='port'))assert.equal(s.toilet,undefined);assert.equal(markerKind(nationalMapGrowth.find(s=>s.type==='boat')),'boat');});

test('map sessions preserve empty selections, default shops off, and reject corrupt state',()=>{const {readMapLayers}=require('../lib/map-session');const {markerKinds}=require('../lib/spot-markers');assert.deepEqual(readMapLayers(null),{types:Object.keys(markerKinds),shops:false});assert.deepEqual(readMapLayers('{oops'),readMapLayers(null));assert.deepEqual(readMapLayers(JSON.stringify({types:[],shops:true})),{types:[],shops:true});assert.deepEqual(readMapLayers(JSON.stringify({types:['boat','boat','bogus',null],shops:true})),{types:['boat'],shops:true});});
test('nearby shops exclude closed locations and sort by real distance without joining fishing spots',()=>{const {nearbyTackleShops,tackleShops}=require('../lib/tackle-shops');const base=tackleShops[0];const shops=[{...base,id:'far',lat:base.lat+.1},{...base,id:'closed',status:'closed'},{...base,id:'near'},{...base,id:'outside',lat:base.lat+2}];assert.deepEqual(nearbyTackleShops(shops,base,30).map(x=>x.shop.id),['near','far']);assert.equal(new Set(tackleShops.map(s=>s.id)).size,tackleShops.length);for(const s of tackleShops){assert.ok(s.sources.length&&s.verifiedAt&&s.address);assert.ok(!fishingMapEntries.some(e=>e.slug===s.id));}});
test('map audit detects missing types, duplicate IDs, invalid coordinates and nearby duplicates',()=>{const {validateFishingMap}=require('../lib/map-validation');const base={...fishingMapEntries.find(s=>s.lat&&s.lng),slug:'test',name:'地点'};const issues=validateFishingMap([base,{...base,primaryType:undefined,prefecture:undefined},{...base,slug:'bad',lat:999},{...base,slug:'unknown',lat:undefined,lng:undefined}]);for(const code of ['duplicate-id','missing-type','missing-prefecture','invalid-coordinate','same-coordinate','same-name','missing-coordinate'])assert.ok(issues.some(i=>i.code===code),code);assert.equal(validateFishingMap(fishingMapEntries).filter(i=>i.level==='error').length,0);});
test('unknown catches preserve optional bait and size labels without fake fish links',()=>{for(const fishSlug of ['unknown','other']){const result=parseCatch({...report,fishSlug,bait:'オキアミ',sizeLabel:'F3'},allowed,new Date('2026-09-17'));assert.equal(result.fishSlug,fishSlug);assert.equal(result.bait,'オキアミ');assert.equal(result.sizeLabel,'F3');}assert.throws(()=>parseCatch({...report,bait:'x'.repeat(101)},allowed,new Date('2026-09-17')));});
test('every representative recipe has an existing image and newly filled assets are species-specific',()=>{for(const f of fishSpecies){if(!f.cooking)continue;for(const r of getSpeciesTableGuide(f).dishes){assert.ok(r.src,`${f.base.slug}/${r.recipe} missing image`);assert.ok(fs.existsSync(path.join(root,'public',r.src)),r.src);if(r.src.startsWith('/images/cooking/'))assert.equal(r.src,`/images/cooking/${f.base.slug}-${r.recipe}.webp`);}}});

test('coastal growth fills every formerly empty prefecture with verified distinct destinations',()=>{const {coastalMapGrowth}=require('../lib/fishing-map-coastal-growth'),{getGuide}=require('../lib/all-guides'),{methodDetails}=require('../lib/method-registry');assert.equal(coastalMapGrowth.length,18);for(const pref of ['埼玉県','石川県','奈良県','岡山県','大分県','宮崎県'])assert.ok(coastalMapGrowth.some(e=>e.prefecture===pref));for(const e of coastalMapGrowth){assert.ok(e.sources.length&&e.verifiedAt&&e.positionNote);assert.ok(e.note.length>30&&e.caution.length>=2);for(const m of e.methodSlugs??[])assert.ok(methodDetails[m],m);for(const g of e.guideSlugs??[])assert.ok(getGuide(g),g);assert.equal(fishingMapEntries.filter(s=>s.slug===e.slug).length,1);}assert.match(coastalMapGrowth.find(e=>e.slug==='tenkawa-winter-trout').status,/冬季/);assert.equal(coastalMapGrowth.find(e=>e.slug==='yomitan-uminchu-club').type,'boat');});

test('access growth adds distinct sourced destinations with valid internal links',()=>{const {accessMapGrowth}=require('../lib/fishing-map-access-growth'),{getGuide}=require('../lib/all-guides'),{methodDetails}=require('../lib/method-registry');assert.equal(accessMapGrowth.length,31);for(const e of accessMapGrowth){assert.ok(e.sources.length>=1&&e.positionNote&&e.verifiedAt);assert.ok(Number.isFinite(e.lat)&&Number.isFinite(e.lng));assert.equal(fishingMapEntries.filter(x=>x.slug===e.slug).length,1);for(const m of e.methodSlugs)assert.ok(methodDetails[m],m);for(const g of e.guideSlugs)assert.ok(getGuide(g),g);}assert.ok(accessMapGrowth.some(e=>e.prefecture==='沖縄県'));assert.ok(accessMapGrowth.some(e=>e.primaryType==='estuary'));assert.equal(accessMapGrowth.find(e=>e.slug==='umiusagi-kadena').lat,26.3619497);});
test('preparation images match existing steps and liver dishes stay in the four-card limit',()=>{for(const f of fishSpecies){for(const img of f.cooking?.prepImages??[]){assert.ok(Number.isInteger(img.step)&&img.step>=0&&img.step<f.cooking.prep.length);assert.ok(img.alt.length>10);assert.ok(fs.existsSync(path.join(root,'public',img.src)));assert.equal(f.cooking.prepImages.filter(x=>x.step===img.step).length,1);}}const f=fishSpecies.find(f=>f.base.slug==='kawahagi');assert.deepEqual(f.representativeRecipes,['sashimi','kimo-shoyu','kimo-ae','nitsuke']);assert.equal(f.cooking.prepImages.length,2);for(const slug of ['kawahagi','umazurahagi']){const p=fishSpecies.find(f=>f.base.slug===slug);for(const r of p.cooking.recipes.filter(r=>r.slug.startsWith('kimo-'))){assert.equal(r.preparation,'raw');assert.ok(r.steps.some(x=>x.includes('75℃')&&x.includes('1分')));assert.ok(r.image.includes(slug));}}});

test('national businesses stay distinct and evidence-backed',()=>{const {boatMapGrowth}=require('../lib/fishing-map-boat-growth'),{nationalTackleShopGrowth}=require('../lib/tackle-shops-national-growth'),{tackleShops}=require('../lib/tackle-shops');assert.ok(boatMapGrowth.length+nationalTackleShopGrowth.length>=100);for(const s of boatMapGrowth){assert.ok(s.sources.length>=2&&s.positionNote&&s.prefecture);assert.equal(s.primaryType,'boat');assert.equal(fishingMapEntries.filter(x=>x.slug===s.slug).length,1);}for(const s of nationalTackleShopGrowth){assert.equal(tackleShops.filter(x=>x.id===s.id).length,1);assert.ok(s.sources.length>=2&&s.address&&s.verifiedAt);assert.ok(!tackleShops.some(x=>x.id!==s.id&&x.lat===s.lat&&x.lng===s.lng));}});
test('homepage image derivatives cover all featured fish without client viewer imports',()=>{const {selectHomeFish}=require('../lib/home-selection'),images=require('../lib/home-images.json');for(let month=1;month<=12;month++){const featured=selectHomeFish(month);assert.equal(featured.length,10);for(const f of featured){const image=images[f.slug];assert.ok(image&&image.width>0&&image.height>0);for(const width of [320,640])assert.ok(fs.existsSync(path.join(root,'public/images/home',f.slug+'-'+width+'.webp')));}}const component=fs.readFileSync(path.join(root,'components/HomeFishImage.tsx'),'utf8');assert.ok(!component.includes('use client'));assert.ok(!component.includes('FishVisual;'));assert.match(component,/loading="lazy"/);});

test('favorites toggle persistently and preserve invalid or future storage',()=>{const {parseSpotFavorites,toggleSpotFavorite}=require('../lib/spot-favorites');const saved=toggleSpotFavorite(null,'mukogawa-ichimonji');assert.deepEqual(parseSpotFavorites(saved),['mukogawa-ichimonji']);assert.deepEqual(parseSpotFavorites(toggleSpotFavorite(saved,'mukogawa-ichimonji')),[]);for(const raw of ['bad','{"version":2,"slugs":[]}','{"version":1,"slugs":[1]}'])assert.throws(()=>toggleSpotFavorite(raw,'aji'));assert.deepEqual(parseSpotFavorites('{"version":1,"slugs":["spot","spot"]}'),['spot']);});
test('old map categories migrate without enabling shops or losing all-off state',()=>{const {readMapLayers}=require('../lib/map-session');assert.deepEqual(readMapLayers(JSON.stringify({types:['facility','park','shore'],shops:false})),{types:['sea-park','sea-pond','pier','other'],shops:false});assert.deepEqual(readMapLayers(JSON.stringify({types:[],shops:false})),{types:[],shops:false});});
test('zoom labels avoid collisions and prioritize selected locations',()=>{const {visibleSpotLabels}=require('../lib/spot-labels');const points=[{slug:'a',name:'釣り場',x:100,y:100},{slug:'b',name:'隣の釣り場',x:110,y:100},{slug:'c',name:'離れた釣り場',x:270,y:200},{slug:'d',name:'画面外',x:-10,y:100}];assert.equal(visibleSpotLabels(points,11,390,500).size,0);assert.deepEqual([...visibleSpotLabels(points,12,390,500,'b')],['b','c']);assert.deepEqual([...visibleSpotLabels(points,12,390,500)],['a','c']);});

test('western shops resolve once with distinct sourced locations and valid prefectures',()=>{const {westTackleShopGrowth}=require('../lib/tackle-shops-west-growth'),{tackleShops}=require('../lib/tackle-shops'),{distanceKm}=require('../lib/spot-distance');for(const s of westTackleShopGrowth){assert.equal(tackleShops.filter(x=>x.id===s.id).length,1);assert.ok(s.address.startsWith(s.prefecture));assert.ok(s.lat>24&&s.lat<36&&s.lng>128&&s.lng<136);assert.ok(s.sources.some(x=>x.url===s.officialUrl));assert.ok(!tackleShops.some(x=>x.id!==s.id&&distanceKm(s,x)<.015),s.name);}for(const pref of ['大阪府','兵庫県','和歌山県','京都府','広島県','福岡県'])assert.ok(westTackleShopGrowth.some(s=>s.prefecture===pref));});

test('coincident map locations separate visually without modifying geography',()=>{const {displaySpotPositions}=require('../lib/spot-marker-positions');const p=[{slug:'b',lat:34,lng:135},{slug:'a',lat:34,lng:135},{slug:'c',lat:35,lng:135}];const original=JSON.stringify(p),project=x=>({x:x.lng*100,y:x.lat*100});assert.deepEqual(displaySpotPositions(p,project,10).get('a'),project(p[0]));const shown=displaySpotPositions(p,project,11);assert.ok(Math.abs(shown.get('a').x-shown.get('b').x)>=40);assert.deepEqual(shown.get('c'),project(p[2]));assert.deepEqual(shown,displaySpotPositions([...p].reverse(),project,11));assert.equal(JSON.stringify(p),original);const many=Array.from({length:12},(_,i)=>({...p[0],slug:String(i)}));const positions=[...displaySpotPositions(many,project,15).values()];for(let i=0;i<positions.length;i++)for(let j=i+1;j<positions.length;j++)assert.ok(Math.hypot(positions[i].x-positions[j].x,positions[i].y-positions[j].y)>35.9);});

test('new species reuse the profile registry, recipe routes and QUEST policies',()=>{
 const {questFish}=require('../lib/quest/catalog'),{selectHomeFish}=require('../lib/home-selection');
 const slugs=['maeso','datsu','blackbass','bluegill','rouninaji','kihada','itou','akame','kurokajiki'];
 for(const slug of slugs){const f=fishSpecies.find(x=>x.base.slug===slug);assert.ok(f.detail&&f.launch&&f.media,slug);assert.ok(fs.existsSync(path.join(root,'public',f.media.image)));assert.ok(f.base.guideSlugs.length,slug);if(['itou','akame'].includes(slug)){assert.equal(f.cookingOmission.reason,'conservation');assert.ok(!questFish.some(x=>x.slug===slug));}else{assert.ok(questFish.some(x=>x.slug===slug));}if(f.cooking){assert.equal(f.cooking.recipes.length,4);assert.equal(getSpeciesTableGuide(f).dishes.length,4);for(const recipe of f.cooking.recipes){assert.ok(recipe.image.includes(slug));assert.ok(fs.existsSync(path.join(root,'public',recipe.image)));}}else{assert.equal(getSpeciesTableGuide(f),undefined);assert.ok(f.cookingOmission.sources.length);}}
 assert.equal(fishSpecies.find(x=>x.base.slug==='rouninaji').cookingOmission.reason,'food-safety');
 assert.equal(selectHomeFish(9).length,10);assert.ok(selectHomeFish(9).every(f=>!slugs.includes(f.slug)));
});
test('cooking omission rejects contradictory recipes and missing evidence',()=>{
 const {defineFishSpecies}=require('../lib/fish-species/define'),base=fishSpecies.find(x=>x.base.slug==='itou');
 assert.throws(()=>defineFishSpecies({...base,cooking:{prep:[],recipes:[]}}),/conflict/);
 assert.throws(()=>defineFishSpecies({...base,tableGuide:{lead:'test',dishes:[]}}),/conflict/);
 assert.throws(()=>defineFishSpecies({...base,cookingOmission:{...base.cookingOmission,note:' '}}),/reason and sources/);
 assert.throws(()=>defineFishSpecies({...base,cookingOmission:{...base.cookingOmission,sources:[]}}),/reason and sources/);
});
