import type {FacilityFormat} from './facility-parser';
import type {CatchSourceType,CatchSignal} from './activity';
export type ExternalCatch=CatchSignal&{sourceType:'official'|'external';summary:string;sourceUrl:string;area?:string;fishName?:string;sourceName?:string;count?:number;countScope?:'facility'|'boat'};
export type CatchSource={id:string;name:string;sourceType:Exclude<CatchSourceType,'user'>;format:FacilityFormat|'fishing-vision-html'|'json'|'naruohama-html'|'tottopark-html'|'anglers-html';endpoint:string;allowedHosts:string[];permissionUrl:string;enabled:boolean;spotSlug?:string;areaId?:string};
/** Each enabled source is reviewed for retrieval restrictions. Import facts only, never prose/images.
 * JSON partners use {catches:[{id,date,fishSlug,spotSlug,summary,sourceUrl,methodSlug?,sizeCm?}]}.
 */
export const catchSources:CatchSource[]=[
 {id:'fishing-vision-kansai-11248',name:'釣りビジョン',sourceType:'external',format:'fishing-vision-html',endpoint:'https://www.fishing-v.jp/choka/choka_detail.php?s=11248',allowedHosts:['www.fishing-v.jp'],permissionUrl:'https://www.fishing-v.jp/robots.txt',spotSlug:'kansai-boat-11248',enabled:true},
 {id:'fishing-vision-kansai-1570',name:'釣りビジョン',sourceType:'external',format:'fishing-vision-html',endpoint:'https://www.fishing-v.jp/choka/choka_detail.php?s=1570',allowedHosts:['www.fishing-v.jp'],permissionUrl:'https://www.fishing-v.jp/robots.txt',spotSlug:'kansai-boat-1570',enabled:true},
 {id:'fishing-vision-kansai-1608',name:'釣りビジョン',sourceType:'external',format:'fishing-vision-html',endpoint:'https://www.fishing-v.jp/choka/choka_detail.php?s=1608',allowedHosts:['www.fishing-v.jp'],permissionUrl:'https://www.fishing-v.jp/robots.txt',spotSlug:'kansai-boat-1608',enabled:true},
 {id:'fishing-vision-kansai-1938',name:'釣りビジョン',sourceType:'external',format:'fishing-vision-html',endpoint:'https://www.fishing-v.jp/choka/choka_detail.php?s=1938',allowedHosts:['www.fishing-v.jp'],permissionUrl:'https://www.fishing-v.jp/robots.txt',spotSlug:'kansai-boat-1938',enabled:true},
 {id:'fishing-vision-kansai-12800',name:'釣りビジョン',sourceType:'external',format:'fishing-vision-html',endpoint:'https://www.fishing-v.jp/choka/choka_detail.php?s=12800',allowedHosts:['www.fishing-v.jp'],permissionUrl:'https://www.fishing-v.jp/robots.txt',spotSlug:'kansai-boat-12800',enabled:true},
 {id:'fishing-vision-kansai-1759',name:'釣りビジョン',sourceType:'external',format:'fishing-vision-html',endpoint:'https://www.fishing-v.jp/choka/choka_detail.php?s=1759',allowedHosts:['www.fishing-v.jp'],permissionUrl:'https://www.fishing-v.jp/robots.txt',spotSlug:'kansai-boat-1759',enabled:true},
 {id:'fishing-vision-kansai-1748',name:'釣りビジョン',sourceType:'external',format:'fishing-vision-html',endpoint:'https://www.fishing-v.jp/choka/choka_detail.php?s=1748',allowedHosts:['www.fishing-v.jp'],permissionUrl:'https://www.fishing-v.jp/robots.txt',spotSlug:'kansai-boat-1748',enabled:true},
 {id:'fishing-vision-kansai-1732',name:'釣りビジョン',sourceType:'external',format:'fishing-vision-html',endpoint:'https://www.fishing-v.jp/choka/choka_detail.php?s=1732',allowedHosts:['www.fishing-v.jp'],permissionUrl:'https://www.fishing-v.jp/robots.txt',spotSlug:'kansai-boat-1732',enabled:true},
 {id:'fishing-vision-kansai-12190',name:'釣りビジョン',sourceType:'external',format:'fishing-vision-html',endpoint:'https://www.fishing-v.jp/choka/choka_detail.php?s=12190',allowedHosts:['www.fishing-v.jp'],permissionUrl:'https://www.fishing-v.jp/robots.txt',spotSlug:'kansai-boat-12190',enabled:true},
 {id:'fishing-vision-kansai-722',name:'釣りビジョン',sourceType:'external',format:'fishing-vision-html',endpoint:'https://www.fishing-v.jp/choka/choka_detail.php?s=722',allowedHosts:['www.fishing-v.jp'],permissionUrl:'https://www.fishing-v.jp/robots.txt',spotSlug:'shimotsu-pialand',enabled:true},
 {id:'fishing-vision-kansai-911',name:'釣りビジョン',sourceType:'external',format:'fishing-vision-html',endpoint:'https://www.fishing-v.jp/choka/choka_detail.php?s=911',allowedHosts:['www.fishing-v.jp'],permissionUrl:'https://www.fishing-v.jp/robots.txt',spotSlug:'growth-aono-outdoor-house',enabled:true},
 {id:'fishing-vision-kansai-1595',name:'釣りビジョン',sourceType:'external',format:'fishing-vision-html',endpoint:'https://www.fishing-v.jp/choka/choka_detail.php?s=1595',allowedHosts:['www.fishing-v.jp'],permissionUrl:'https://www.fishing-v.jp/robots.txt',spotSlug:'yoyomaru-fukuro',enabled:true},
 {id:'amagasaki-official',name:'尼崎市立魚つり公園',sourceType:'official',format:'amagasaki-html',endpoint:'https://amagasaki-uoturikouen.com/fishing/index.html',allowedHosts:['amagasaki-uoturikouen.com'],permissionUrl:'https://amagasaki-uoturikouen.com/robots.txt',spotSlug:'amagasaki-uoturi',enabled:true},
 {id:'fishing-vision-uoe',name:'釣りビジョン',sourceType:'external',format:'fishing-vision-html',endpoint:'https://www.fishing-v.jp/choka/choka_detail.php?s=669',allowedHosts:['www.fishing-v.jp'],permissionUrl:'https://www.fishing-v.jp/robots.txt',spotSlug:'boat-uoe',enabled:true},
 {id:'fishing-vision-bentenya',name:'釣りビジョン',sourceType:'external',format:'fishing-vision-html',endpoint:'https://www.fishing-v.jp/choka/choka_detail.php?s=190',allowedHosts:['www.fishing-v.jp'],permissionUrl:'https://www.fishing-v.jp/robots.txt',spotSlug:'hakkei-bentenya',enabled:true},
 {id:'fishing-vision-yoshikyu',name:'釣りビジョン',sourceType:'external',format:'fishing-vision-html',endpoint:'https://www.fishing-v.jp/choka/choka_detail.php?s=147',allowedHosts:['www.fishing-v.jp'],permissionUrl:'https://www.fishing-v.jp/robots.txt',spotSlug:'urayasu-yoshikyu',enabled:true},
 {id:'fishing-vision-yoshinoya',name:'釣りビジョン',sourceType:'external',format:'fishing-vision-html',endpoint:'https://www.fishing-v.jp/choka/choka_detail.php?s=146',allowedHosts:['www.fishing-v.jp'],permissionUrl:'https://www.fishing-v.jp/robots.txt',spotSlug:'urayasu-yoshinoya',enabled:true},
 {id:'fishing-vision-kairyumaru',name:'釣りビジョン',sourceType:'external',format:'fishing-vision-html',endpoint:'https://www.fishing-v.jp/choka/choka_detail.php?s=12117',allowedHosts:['www.fishing-v.jp'],permissionUrl:'https://www.fishing-v.jp/robots.txt',spotSlug:'kanazawa-kairyumaru',enabled:true},
 {id:'fishing-vision-shichifuku',name:'釣りビジョン',sourceType:'external',format:'fishing-vision-html',endpoint:'https://www.fishing-v.jp/choka/choka_detail.php?s=359',allowedHosts:['www.fishing-v.jp'],permissionUrl:'https://www.fishing-v.jp/robots.txt',spotSlug:'shichifuku-morozaki',enabled:true},
 {id:'naoetsu-official',name:'直江津港ハッピーフィッシング',sourceType:'official',format:'happy-html',endpoint:'https://happyfishing-n.jp/',allowedHosts:['happyfishing-n.jp'],permissionUrl:'https://happyfishing-n.jp/robots.txt',spotSlug:'naoetsu-happyfishing',enabled:true},
 {id:'yura-official',name:'由良海つり公園',sourceType:'official',format:'tottopark-html',endpoint:'https://minnaga.com/system/yurakouen/contents/fish/fish_listup.php',allowedHosts:['minnaga.com'],permissionUrl:'https://minnaga.com/robots.txt',spotSlug:'yura-wakayama-park',enabled:true},
 {id:'niigata-official',name:'新潟東港ハッピーフィッシング',sourceType:'official',format:'happy-html',endpoint:'https://happyfishing.jp/',allowedHosts:['happyfishing.jp'],permissionUrl:'https://happyfishing.jp/robots.txt',spotSlug:'niigata-happyfishing',enabled:true},
 {id:'ichihara-official',name:'オリジナルメーカー海づり公園',sourceType:'official',format:'ichihara-html',endpoint:'https://ichihara-umizuri.com/fishing/',allowedHosts:['ichihara-umizuri.com'],permissionUrl:'https://ichihara-umizuri.com/robots.txt',spotSlug:'ichihara-fishing',enabled:true},
 {id:'hiraiso-official',name:'平磯海づり公園',sourceType:'official',format:'hiraiso-html',endpoint:'https://kobeumiduri.jp/fishresult/',allowedHosts:['kobeumiduri.jp'],permissionUrl:'https://kobeumiduri.jp/robots.txt',spotSlug:'hira-isoumi',enabled:true},
 {id:'shimonoseki-official',name:'下関フィッシングパーク',sourceType:'official',format:'shimonoseki-html',endpoint:'https://shimonoseki-fishingpark.com/fishing/index.html',allowedHosts:['shimonoseki-fishingpark.com'],permissionUrl:'https://shimonoseki-fishingpark.com/robots.txt',spotSlug:'shimonoseki-fishing',enabled:true},
 {id:'fukuoka-official',name:'福岡市海づり公園',sourceType:'official',format:'fukuoka-html',endpoint:'https://umizuri.com/pages/30',allowedHosts:['umizuri.com'],permissionUrl:'https://umizuri.com/robots.txt',spotSlug:'fukuoka-fishing',enabled:true},
 {id:'anglers-amagasaki',name:'ANGLERS',sourceType:'external',format:'anglers-html',endpoint:'https://anglers.jp/areas/874',allowedHosts:['anglers.jp'],permissionUrl:'https://anglers.jp/terms/free',spotSlug:'amagasaki-uoturi',areaId:'874',enabled:true},
 {id:'anglers-mukogawa',name:'ANGLERS',sourceType:'external',format:'anglers-html',endpoint:'https://anglers.jp/areas/877',allowedHosts:['anglers.jp'],permissionUrl:'https://anglers.jp/terms/free',spotSlug:'mukogawa-ichimonji',areaId:'877',enabled:true},
 {id:'anglers-naruohama',name:'ANGLERS',sourceType:'external',format:'anglers-html',endpoint:'https://anglers.jp/areas/2335',allowedHosts:['anglers.jp'],permissionUrl:'https://anglers.jp/terms/free',spotSlug:'naruohama',areaId:'2335',enabled:true},
 {id:'tottopark-official',name:'とっとパーク小島',sourceType:'official',format:'tottopark-html',endpoint:'https://minnaga.com/system/totopark/contents/fish/fish_listup.php',allowedHosts:['minnaga.com'],permissionUrl:'https://minnaga.com/robots.txt',enabled:true},
 {id:'naruohama-official',name:'鳴尾浜海づり広場',sourceType:'official',format:'naruohama-html',endpoint:'https://www.naruohama-park.com/choka/',allowedHosts:['www.naruohama-park.com'],permissionUrl:'https://www.naruohama-park.com/robots.txt',enabled:true},
];
