'use client';
import ExternalCatchFeed from './ExternalCatchFeed';
import CatchFishSearch from './CatchFishSearch';
import LocalSpotCatches from './LocalSpotCatches';
import CatchCard from './CatchCard';
import {useCatchSession,loginHref} from './CatchSession';
import {useEffect,useRef,useState} from 'react';import Link from 'next/link';
import {catchTimes,parseCatch,type LocalCatch,type PublicCatch} from '@/lib/catches/types';import {saveLocalCatch,localCatches,deleteLocalCatch} from '@/lib/catches/local';import {preparePhoto} from '@/lib/photo-upload';import s from './Submission.module.css';
export type CatchOptions={fish:{slug:string;name:string;aliases?:string[]}[];spots:{slug:string;name:string}[];methods:{slug:string;name:string}[]};
export function CatchReports({spotSlug,options,canPost=true,scrollRequest=0}:{scrollRequest?:number;spotSlug:string;options:CatchOptions;canPost?:boolean}){
 const sectionRef=useRef<HTMLElement>(null);
 useEffect(()=>{if(scrollRequest){const frame=requestAnimationFrame(()=>sectionRef.current?.scrollIntoView({behavior:'smooth',block:'start'}));return()=>cancelAnimationFrame(frame);}},[scrollRequest]);
 const session=useCatchSession();const [reports,setReports]=useState<PublicCatch[]>([]),[mine,setMine]=useState<PublicCatch[]>([]),[available,setAvailable]=useState<boolean|null>(null),[error,setError]=useState(''),[more,setMore]=useState(false),[loading,setLoading]=useState(false),[revision,setRevision]=useState(0);
 useEffect(()=>{const update=()=>setRevision(n=>n+1);window.addEventListener('uolink-public-catch',update);return()=>window.removeEventListener('uolink-public-catch',update);},[]);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');setReports([]);setMine([]);Promise.all([fetch(`/api/catches?spot=${encodeURIComponent(spotSlug)}`,{signal:controller.signal}).then(async r=>{const v=await r.json();if(!r.ok)throw Error(v.error);setAvailable(v.available);setReports(v.reports);setMore(v.reports.length===10);}),session.user?fetch(`/api/catches?mine=1&spot=${encodeURIComponent(spotSlug)}`,{signal:controller.signal}).then(async r=>{const v=await r.json();if(!r.ok)throw Error(v.error);setMine(v.reports);}):Promise.resolve()]).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[spotSlug,session.user?.id,revision]);
 async function loadMore(){setLoading(true);try{const r=await fetch(`/api/catches?spot=${encodeURIComponent(spotSlug)}&offset=${reports.length}`);const v=await r.json();if(!r.ok)throw Error(v.error);setReports(prev=>[...prev,...v.reports]);setMore(v.reports.length===10);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 return <section ref={sectionRef} id="catches" className={`${s.panel} ${s.catchSection}`}><div className={s.catchHeading}><div><h2>最近の釣果</h2><p className={s.meta}>何が・いつ・どれくらい釣れた？</p></div>{canPost&&<a className={s.catchPostLink} href="#catch-form">＋ 投稿する</a>}</div><h3 className={s.sourceHeading}>UOLINKユーザー投稿</h3>{mine.filter(r=>r.status!=='approved').map(r=><CatchCard key={r.id} report={r} options={options} authenticated onDeleted={()=>setRevision(n=>n+1)}/>)}{reports.map(r=><CatchCard key={r.id} report={{...r,isOwn:mine.some(m=>m.id===r.id)}} options={options} publicCard authenticated={!!session.user} onDeleted={()=>setRevision(n=>n+1)}/>)}{!loading&&!reports.length&&!error&&<p className={s.empty}>UOLINKへの投稿はまだありません。{canPost&&<a href="#catch-form">この釣り場の最初の釣果を投稿する →</a>}</p>}{loading&&<p role="status">読み込み中…</p>}{error&&<p role="status" className={s.error}>{error}</p>}{more&&<button className={`${s.button} ${s.secondary}`} disabled={loading} onClick={loadMore}>釣果をもっと見る</button>}<ExternalCatchFeed hideEmpty spotView options={options} query={`spot=${encodeURIComponent(spotSlug)}`}/><LocalSpotCatches spotSlug={spotSlug} options={options}/>{canPost&&<CatchForm options={options} defaultSpot={spotSlug} publicAvailable={available===true}/>}</section>;
}
export function CatchForm({options,defaultSpot,publicAvailable=false}:{options:CatchOptions;defaultSpot?:string;publicAvailable?:boolean}){const session=useCatchSession();const [photos,setPhotos]=useState<string[]>([]),[photo,setPhoto]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[publish,setPublish]=useState(true);const identity=useRef<{id:string;deleteToken:string}|null>(null);const form=useRef<HTMLFormElement>(null);
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage('');try{const fields=new FormData(event.currentTarget);if(fields.get('website'))throw Error('送信できません。');identity.current??={id:crypto.randomUUID(),deleteToken:crypto.randomUUID()};const allowed={fish:new Set(options.fish.map(f=>f.slug)),spots:new Set(options.spots.map(s=>s.slug)),methods:new Set(options.methods.map(m=>m.slug))};const report=parseCatch({...Object.fromEntries(fields),id:identity.current.id,source:'real',count:Number(fields.get('count')),sizeCm:fields.get('sizeCm')?Number(fields.get('sizeCm')):undefined,photos,released:fields.get('released')==='on'?true:undefined},allowed);const local:LocalCatch={...report,deleteToken:identity.current.deleteToken,publicStatus:undefined};await saveLocalCatch(local);window.dispatchEvent(new Event('uolink-real-catch'));if(publish&&publicAvailable&&session.user){if(!session.user)throw Error('公開投稿するにはログインしてください。');const r=await fetch('/api/catches',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({report:{...report,photo:undefined},consent:fields.get('consent')==='on',website:''})});const v=await r.json();if(!r.ok)throw Error(`端末には保存しました。公開送信：${v.error}`);await saveLocalCatch({...local,publicStatus:v.status});setMessage('釣果を公開しました。上の「最近の釣果」で確認できます。');window.dispatchEvent(new Event('uolink-public-catch'));}else setMessage('この端末に実釣記録を保存しました。QUESTのマイ記録からも確認できます。');identity.current=null;form.current?.reset();setPhoto('');setPhotos([]);window.dispatchEvent(new Event('uolink-real-catch'));}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <form id="catch-form" ref={form} onSubmit={submit}>
  <h2>＋ 釣果を投稿</h2>{session.loading?<p>ログインを確認中…</p>:!session.user?<p><Link className={s.button} href={loginHref(defaultSpot?`/spots/${defaultSpot}#catch-form`:'/catches')}>ログインして投稿する</Link></p>:<p className={s.meta}>ログイン中 · <Link href="/catches">自分の公開投稿を見る</Link></p>}{session.error&&<p role="status">{session.error}</p>}<p>魚・匹数・日付だけで記録できます。写真や詳しい仕掛けは任意です。</p>
  {defaultSpot?<><input type="hidden" name="spotSlug" value={defaultSpot}/><p>釣り場：{options.spots.find(x=>x.slug===defaultSpot)?.name}</p></>:<label className={s.field}>釣り場<select name="spotSlug" required defaultValue=""><option value="">選択</option>{options.spots.map(x=><option key={x.slug} value={x.slug}>{x.name}</option>)}</select></label>}
  <div className={s.grid}>
   <CatchFishSearch fish={options.fish}/>
   <label className={s.field}>匹数<input name="count" type="number" min="1" max="999" defaultValue="1" inputMode="numeric" required/></label>
   <label className={s.field}>サイズ（cm・任意）<input name="sizeCm" type="number" min="0.1" max="500" step="0.1" inputMode="decimal"/></label>
   <label className={s.field}>釣行日<input name="date" type="date" required defaultValue={new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}/></label>
   <label className={s.field}>写真（最大3枚・任意）<input type="file" multiple accept="image/jpeg,image/png,image/webp,image/heic,image/heif" disabled={busy} onChange={async e=>{const files=Array.from(e.target.files??[]);if(!files.length)return;if(files.length>3){setMessage('写真は3枚まで選択してください。');e.target.value='';return;}setBusy(true);try{const prepared=[];for(const file of files)prepared.push(await preparePhoto(file));setPhotos(prepared);setPhoto(prepared[0]);setMessage('');}catch(err){setMessage((err as Error).message);}finally{setBusy(false);}}}/></label>
  </div>
  {photo&&<><div className={s.catchPhotos}>{photos.map((src,i)=><img key={i} src={src} width={600} height={450} alt={`投稿する写真 ${i+1}`}/>)}</div><button type="button" className={`${s.button} ${s.secondary}`} onClick={()=>{setPhoto('');setPhotos([]);}}>写真を外す</button></>}
  <label className={s.field}>魚名（「その他」の場合・任意）<input name="fishName" maxLength={50} placeholder="図鑑にない魚の名前"/></label><details><summary>釣り方などを追加する（任意）</summary><div className={s.grid}>
   <label className={s.field}>重さ・指幅など<input name="sizeLabel" maxLength={30} placeholder="例：650g、F3"/></label>
   <label className={s.field}>時間帯<select name="time" defaultValue="unknown">{Object.entries(catchTimes).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label>
   <label className={s.field}>釣り方<select name="methodSlug"><option value="">選択しない</option>{options.methods.map(m=><option key={m.slug} value={m.slug}>{m.name}</option>)}</select></label>
   <label className={s.field}>仕掛け<input name="rig" maxLength={100} placeholder="例：サビキ4号"/></label>
   <label className={s.field}>ルアー / 餌<input name="bait" maxLength={100} placeholder="例：アミエビ、エギ3号"/></label>
   <label><input type="checkbox" name="released"/> リリースした</label><label className={`${s.field} ${s.wide}`}>一言コメント<textarea name="comment" rows={3} maxLength={500} placeholder="棚や誘いなど。個人情報・秘密の場所・広告は書かないでください。"/></label>
  </div></details>
  <label className={s.trap} aria-hidden="true">Webサイト<input name="website" tabIndex={-1} autoComplete="off"/></label>
  <p className={s.meta}>ゲームの釣果は登録しないでください。写真は縮小して位置情報を除きます。端末のサイトデータを消すと端末内の記録も消えます。</p>
  {publicAvailable&&session.user?<><label className={s.consent}><input type="checkbox" checked={publish} onChange={e=>setPublish(e.target.checked)}/><span>この釣り場に公開投稿する（OFFで端末内の記録のみ）</span></label>{publish&&<label className={s.consent}><input name="consent" type="checkbox" required/><span>自分の釣果・写真で、個人情報を含まないことを確認し、釣り場・魚種・日付・本文・写真の公開に同意します。</span></label>}</>:<p className={s.meta}>{publicAvailable?'公開するにはログインしてください。ログインなしでも端末内に下書きを保存できます。':'公開受付は接続準備中です。端末内には記録できます。'}</p>}
  <button className={s.button} disabled={busy||session.loading}>{busy?'保存中…':publish&&session.user&&publicAvailable?'釣果を公開する':'この端末に記録する'}</button><p role="status">{message}</p><Link href="/catches">自分の実釣記録を見る →</Link>
 </form>;
}
export function RealCatchJournal({options}:{options:CatchOptions}){const [reports,setReports]=useState<LocalCatch[]>([]),[error,setError]=useState('');async function refresh(){try{setReports(await localCatches());}catch(e){setError((e as Error).message);}}useEffect(()=>{void refresh();const fn=()=>void refresh();window.addEventListener('uolink-real-catch',fn);return()=>window.removeEventListener('uolink-real-catch',fn);},[]);
 async function remove(report:LocalCatch){if(!window.confirm('この実釣記録を削除しますか？公開送信済みなら公開データも削除します。'))return;try{if(report.publicStatus){const r=await fetch('/api/catches',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:report.id,deleteToken:report.deleteToken})});if(!r.ok)throw Error('公開データを削除できません。端末の記録は残しています。');}await deleteLocalCatch(report.id);await refresh();}catch(e){setError((e as Error).message);}}
 return <section className={s.panel}><h2>実釣の記録</h2><p>この端末で登録した実際の釣果です。QUESTのゲーム内捕獲・XPとは別に保存します。</p>{error&&<p role="status" className={s.error}>{error}</p>}{!reports.length&&<p>まだ実釣記録はありません。釣り場ページから登録できます。</p>}{reports.slice(0,50).map(r=><div key={r.id}><CatchCard report={r} options={options}/><p className={s.meta}>{r.publicStatus?'公開送信済み（掲載状況は釣り場ページで確認）':'端末内のみ'}</p><button className={`${s.button} ${s.secondary}`} onClick={()=>remove(r)}>この記録を削除</button></div>)}{reports.length>50&&<p>最新50件を表示しています。全件は保存ファイルで確認できます。</p>}<div className={s.actions}><Link className={s.button} href="/spots">MAPから釣り場を選ぶ</Link>{reports.length>0&&<button className={`${s.button} ${s.secondary}`} onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(reports,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='uolink-real-catches.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>記録をファイルに保存</button>}</div><p className={s.meta}>保存ファイルには写真と公開データの削除キーが含まれます。他人へ渡さず保管してください。</p></section>;
}
