'use client';
import {useEffect,useRef,useState} from 'react';import Link from 'next/link';
import {unknownFishNames,catchTimes,parseCatch,type CatchReport,type LocalCatch} from '@/lib/catches/types';import {saveLocalCatch,localCatches,deleteLocalCatch} from '@/lib/catches/local';import {preparePhoto} from '@/lib/photo-upload';import s from './Submission.module.css';
export type CatchOptions={fish:{slug:string;name:string}[];spots:{slug:string;name:string}[];methods:{slug:string;name:string}[]};
function CatchCard({report,options}:{report:CatchReport;options:CatchOptions}){const fish=options.fish.find(f=>f.slug===report.fishSlug),spot=options.spots.find(s=>s.slug===report.spotSlug);return <article className={s.card}><h3>{fish?<Link href={`/fish/${report.fishSlug}`}>{fish.name}</Link>:unknownFishNames[report.fishSlug as keyof typeof unknownFishNames]??'魚種不明'} · {report.count}匹{report.sizeLabel?` · ${report.sizeLabel}`:report.sizeCm?` · ${report.sizeCm}cm`:''}</h3><p className={s.meta}>{report.date} · {catchTimes[report.time]} · <Link href={`/spots/${report.spotSlug}`}>{spot?.name??report.spotSlug}</Link></p>{report.photo&&<img loading="lazy" className={s.preview} src={report.photo} alt={`${fish?.name??'魚'}の釣果写真`}/>}<p>{report.methodSlug&&<Link href={`/methods/${report.methodSlug}`}>{options.methods.find(m=>m.slug===report.methodSlug)?.name??report.methodSlug}</Link>}{report.rig&&` / ${report.rig}`}{report.bait&&` / ${report.bait}`}</p>{report.comment&&<p>{report.comment}</p>}<div className={s.links}>{fish?<><Link href={`/guide?fish=${report.fishSlug}`}>釣り方のGUIDE →</Link><Link href={`/fish/${report.fishSlug}`}>魚の情報を詳しく →</Link></>:<Link href="/fish">図鑑で魚を調べる →</Link>}</div></article>}
export function CatchReports({spotSlug,options}:{spotSlug:string;options:CatchOptions}){const [ownReports,setOwnReports]=useState<LocalCatch[]>([]),[ownLimit,setOwnLimit]=useState(5);
 useEffect(()=>{let active=true;const refresh=()=>localCatches().then(rows=>{if(active)setOwnReports(rows.filter(r=>r.spotSlug===spotSlug));}).catch(()=>{});void refresh();window.addEventListener('uolink-real-catch',refresh);return()=>{active=false;window.removeEventListener('uolink-real-catch',refresh);};},[spotSlug]);
 const [reports,setReports]=useState<CatchReport[]>([]),[available,setAvailable]=useState<boolean|null>(null),[error,setError]=useState(''),[more,setMore]=useState(false),[loading,setLoading]=useState(false);const mounted=useRef(true);
 async function load(offset=0){setLoading(true);try{const r=await fetch(`/api/catches?spot=${encodeURIComponent(spotSlug)}&offset=${offset}`);const v=await r.json();if(!r.ok)throw Error(v.error);if(mounted.current){setAvailable(v.available);setReports(prev=>offset?[...prev,...v.reports]:v.reports);setMore(v.reports.length===10);}}catch(e){if(mounted.current)setError((e as Error).message);}finally{if(mounted.current)setLoading(false);}}
 useEffect(()=>{mounted.current=true;void load();return()=>{mounted.current=false;};},[spotSlug]);
 return <section id="catches" className={s.panel}><h2>最近の釣果</h2><p className={s.meta}>利用者から寄せられた実釣報告を確認後に掲載します。釣果は現在の釣り許可や次回の釣果を保証しません。</p>{available===false&&<p className={s.notice}>公開釣果の受付は準備中です。下のフォームで、この端末に実釣記録を保存できます。</p>}{ownReports.length>0&&<section aria-label="この釣り場での自分の釣果"><h3>あなたの最近の釣果</h3><p className={s.meta}>この端末に保存した記録です。公開審査中の記録もここで確認できます。</p>{ownReports.slice(0,ownLimit).map(r=><div key={r.id}><CatchCard report={r} options={options}/><p>{r.publicStatus?'公開送信済み・掲載状況は下の公開釣果で確認':'この端末のみ'}</p></div>)}{ownReports.length>ownLimit&&<button className={s.button} onClick={()=>setOwnLimit(n=>n+10)}>自分の釣果をもっと見る</button>}</section>}{reports.map(r=><CatchCard key={r.id} report={r} options={options}/>)}{available===true&&!reports.length&&<p className={s.empty}>公開済みの釣果はまだありません。</p>}{loading&&<p role="status">読み込み中…</p>}{error&&<p role="status" className={s.error}>{error}</p>}{more&&<button className={`${s.button} ${s.secondary}`} disabled={loading} onClick={()=>load(reports.length)}>以前の釣果を見る</button>}<CatchForm options={options} defaultSpot={spotSlug} publicAvailable={available===true}/></section>;
}
export function CatchForm({options,defaultSpot,publicAvailable=false}:{options:CatchOptions;defaultSpot?:string;publicAvailable?:boolean}){const [photo,setPhoto]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[publish,setPublish]=useState(false);const identity=useRef<{id:string;deleteToken:string}|null>(null);const form=useRef<HTMLFormElement>(null);
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage('');try{const fields=new FormData(event.currentTarget);if(fields.get('website'))throw Error('送信できません。');identity.current??={id:crypto.randomUUID(),deleteToken:crypto.randomUUID()};const allowed={fish:new Set(options.fish.map(f=>f.slug)),spots:new Set(options.spots.map(s=>s.slug)),methods:new Set(options.methods.map(m=>m.slug))};const report=parseCatch({...Object.fromEntries(fields),id:identity.current.id,source:'real',count:Number(fields.get('count')),sizeCm:fields.get('sizeCm')?Number(fields.get('sizeCm')):undefined,photo},allowed);const local:LocalCatch={...report,deleteToken:identity.current.deleteToken,publicStatus:undefined};await saveLocalCatch(local);window.dispatchEvent(new Event('uolink-real-catch'));if(publish){const r=await fetch('/api/catches',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({report,deleteToken:local.deleteToken,consent:true,website:''})});const v=await r.json();if(!r.ok)throw Error(`端末には保存しました。公開送信：${v.error}`);await saveLocalCatch({...local,publicStatus:v.status});setMessage('端末に保存し、公開審査へ送りました。確認後に釣り場へ掲載されます。');}else setMessage('この端末に実釣記録を保存しました。QUESTのマイ記録からも確認できます。');identity.current=null;form.current?.reset();setPhoto('');setPublish(false);window.dispatchEvent(new Event('uolink-real-catch'));}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <form ref={form} onSubmit={submit}>
  <h2>この釣り場で釣れた！</h2><p>魚・匹数・日付だけで記録できます。写真や詳しい仕掛けは任意です。</p>
  {defaultSpot?<><input type="hidden" name="spotSlug" value={defaultSpot}/><p>釣り場：{options.spots.find(x=>x.slug===defaultSpot)?.name}</p></>:<label className={s.field}>釣り場<select name="spotSlug" required defaultValue=""><option value="">選択</option>{options.spots.map(x=><option key={x.slug} value={x.slug}>{x.name}</option>)}</select></label>}
  <div className={s.grid}>
   <label className={s.field}>魚種<select name="fishSlug" required defaultValue=""><option value="">選択</option>{options.fish.map(x=><option key={x.slug} value={x.slug}>{x.name}</option>)}{Object.entries(unknownFishNames).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>
   <label className={s.field}>匹数<input name="count" type="number" min="1" max="999" defaultValue="1" inputMode="numeric" required/></label>
   <label className={s.field}>釣行日<input name="date" type="date" required defaultValue={new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}/></label>
   <label className={s.field}>写真（任意）<input type="file" accept="image/*" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);try{setPhoto(await preparePhoto(file));setMessage('');}catch(err){setMessage((err as Error).message);}finally{setBusy(false);}}}/></label>
  </div>
  {photo&&<><img className={s.preview} src={photo} alt="釣果に添える写真"/><button type="button" className={`${s.button} ${s.secondary}`} onClick={()=>setPhoto('')}>写真を外す</button></>}
  <details><summary>サイズ・釣り方などを追加する（任意）</summary><div className={s.grid}>
   <label className={s.field}>最大サイズ（cm）<input name="sizeCm" type="number" min="0.1" max="500" step="0.1" inputMode="decimal"/></label>
   <label className={s.field}>重さ・指幅など<input name="sizeLabel" maxLength={30} placeholder="例：650g、F3"/></label>
   <label className={s.field}>時間帯<select name="time" defaultValue="unknown">{Object.entries(catchTimes).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label>
   <label className={s.field}>釣り方<select name="methodSlug"><option value="">選択しない</option>{options.methods.map(m=><option key={m.slug} value={m.slug}>{m.name}</option>)}</select></label>
   <label className={s.field}>仕掛け<input name="rig" maxLength={100} placeholder="例：サビキ4号"/></label>
   <label className={s.field}>ルアー / 餌<input name="bait" maxLength={100} placeholder="例：アミエビ、エギ3号"/></label>
   <label className={`${s.field} ${s.wide}`}>一言コメント<textarea name="comment" rows={3} maxLength={500} placeholder="棚や誘いなど。個人情報・秘密の場所・広告は書かないでください。"/></label>
  </div></details>
  <label className={s.trap} aria-hidden="true">Webサイト<input name="website" tabIndex={-1} autoComplete="off"/></label>
  <p className={s.meta}>ゲームの釣果は登録しないでください。写真は縮小して位置情報を除きます。端末のサイトデータを消すと端末内の記録も消えます。</p>
  {publicAvailable&&<label className={s.consent}><input type="checkbox" checked={publish} onChange={e=>setPublish(e.target.checked)}/><span>自分の釣果と写真で、顔・ナンバー等の個人情報がないことを確認しました。釣り場・魚種・日付・本文・写真をUOLINKで公開することに同意して審査へ送ります。</span></label>}
  <button className={s.button} disabled={busy}>{busy?'保存中…':publish?'保存して公開審査へ送る':'この端末に記録する'}</button><p role="status">{message}</p><Link href="/catches">自分の実釣記録を見る →</Link>
 </form>;
}
export function RealCatchJournal({options}:{options:CatchOptions}){const [reports,setReports]=useState<LocalCatch[]>([]),[error,setError]=useState('');async function refresh(){try{setReports(await localCatches());}catch(e){setError((e as Error).message);}}useEffect(()=>{void refresh();const fn=()=>void refresh();window.addEventListener('uolink-real-catch',fn);return()=>window.removeEventListener('uolink-real-catch',fn);},[]);
 async function remove(report:LocalCatch){if(!window.confirm('この実釣記録を削除しますか？公開送信済みなら公開データも削除します。'))return;try{if(report.publicStatus){const r=await fetch('/api/catches',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:report.id,deleteToken:report.deleteToken})});if(!r.ok)throw Error('公開データを削除できません。端末の記録は残しています。');}await deleteLocalCatch(report.id);await refresh();}catch(e){setError((e as Error).message);}}
 return <section className={s.panel}><h2>実釣の記録</h2><p>この端末で登録した実際の釣果です。QUESTのゲーム内捕獲・XPとは別に保存します。</p>{error&&<p role="status" className={s.error}>{error}</p>}{!reports.length&&<p>まだ実釣記録はありません。釣り場ページから登録できます。</p>}{reports.slice(0,50).map(r=><div key={r.id}><CatchCard report={r} options={options}/><p className={s.meta}>{r.publicStatus?'公開審査へ送信済み（掲載状況は釣り場ページで確認）':'端末内のみ'}</p><button className={`${s.button} ${s.secondary}`} onClick={()=>remove(r)}>この記録を削除</button></div>)}{reports.length>50&&<p>最新50件を表示しています。全件は保存ファイルで確認できます。</p>}<div className={s.actions}><Link className={s.button} href="/spots">MAPから釣り場を選ぶ</Link>{reports.length>0&&<button className={`${s.button} ${s.secondary}`} onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(reports,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='uolink-real-catches.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>記録をファイルに保存</button>}</div><p className={s.meta}>保存ファイルには写真と公開データの削除キーが含まれます。他人へ渡さず保管してください。</p></section>;
}
