'use client';
import {deleteLocalCatch} from '@/lib/catches/local';
import {useState} from 'react';
import Link from 'next/link';
import {unknownFishNames,catchTimes,type PublicCatch} from '@/lib/catches/types';
import type {CatchOptions} from './CatchReports';
import {loginHref} from './CatchSession';
import s from './Submission.module.css';
export default function CatchCard({report,options,authenticated=false,onDeleted,publicCard=false}:{report:PublicCatch;options:CatchOptions;authenticated?:boolean;onDeleted?:()=>void;publicCard?:boolean}){
 const fish=options.fish.find(f=>f.slug===report.fishSlug),spot=options.spots.find(s=>s.slug===report.spotSlug);const [message,setMessage]=useState(''),[busy,setBusy]=useState(false),[reporting,setReporting]=useState(false);
 async function act(path:string,method:string,body:unknown){setBusy(true);try{const r=await fetch(path,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const v=await r.json();if(!r.ok)throw Error(v.error);return true;}catch(e){setMessage((e as Error).message);return false;}finally{setBusy(false);}}
 return <article className={s.card}><h3>{fish?<Link href={`/fish/${report.fishSlug}`}>{fish.name}</Link>:report.fishName||unknownFishNames[report.fishSlug as keyof typeof unknownFishNames]||'魚種不明'} · {report.count}匹{report.sizeLabel?` · ${report.sizeLabel}`:report.sizeCm?` · ${report.sizeCm}cm`:''}</h3><p className={s.meta}>{report.date} · {catchTimes[report.time]} · <Link href={`/spots/${report.spotSlug}`}>{spot?.name??report.spotSlug}</Link>{report.released?' · リリース':''}</p>{report.isOwn&&report.status&&<p className={s.meta}>{report.status==='pending'?'確認待ち（本人にのみ表示）':report.status==='approved'?'公開中':'非公開（本人にのみ表示）'}</p>}<div className={s.catchPhotos}>{(report.photos?.length?report.photos:report.photo?[report.photo]:[]).map((src,i)=><img key={i} loading="lazy" width={600} height={450} src={src} alt={`${fish?.name??'魚'}の釣果写真 ${i+1}`}/>)}</div><p>{report.methodSlug&&<Link href={`/methods/${report.methodSlug}`}>{options.methods.find(m=>m.slug===report.methodSlug)?.name??report.methodSlug}</Link>}{report.rig&&` / ${report.rig}`}{report.bait&&` / ${report.bait}`}</p>{report.comment&&<p>{report.comment}</p>}<div className={s.links}>{fish&&<Link href={`/guide?fish=${report.fishSlug}`}>この魚を狙うGUIDE →</Link>}{report.methodSlug&&<><Link href={`/methods/${report.methodSlug}`}>この釣法を見る →</Link><Link href={`/gear?method=${report.methodSlug}`}>必要な道具を見る →</Link></>}</div>
 {report.isOwn&&<button className={`${s.button} ${s.secondary}`} disabled={busy} onClick={async()=>{if(confirm('この釣果と投稿写真を削除しますか？'))if(await act('/api/catches','DELETE',{id:report.id})){await deleteLocalCatch(report.id).catch(()=>{});window.dispatchEvent(new Event('uolink-real-catch'));setMessage('削除しました。');onDeleted?.();window.dispatchEvent(new Event('uolink-public-catch'));}}}>自分の投稿を削除</button>}
 {publicCard&&!report.isOwn&&(authenticated?<button type="button" className={s.textButton} onClick={()=>setReporting(!reporting)}>不適切な投稿を報告</button>:<Link className={s.meta} href={loginHref(`/spots/${report.spotSlug}#catches`)}>ログインして投稿を報告</Link>)}
 {reporting&&<form onSubmit={async e=>{e.preventDefault();const reason=new FormData(e.currentTarget).get('reason');if(await act('/api/catches/report','POST',{id:report.id,reason})){setReporting(false);setMessage('運営へ報告しました。');}}}><label className={s.field}>報告理由<select name="reason"><option>個人情報が写っている</option><option>実釣ではない・内容に問題がある</option><option>無断転載・広告・迷惑投稿</option><option>危険行為・立入禁止場所の利用</option></select></label><button className={s.button} disabled={busy}>運営へ報告する</button></form>}<p role="status">{message}</p></article>;
}
