'use client';
import {useEffect,useRef,useState} from 'react';import Link from 'next/link';
import type {IdentificationResult} from '@/lib/fish-identification';import {preparePhoto} from '@/lib/photo-upload';import s from './Submission.module.css';
type FishOption={slug:string;name:string;danger?:boolean};
export default function FishIdentifier({fish}:{fish:FishOption[]}){const [image,setImage]=useState(''),[available,setAvailable]=useState<boolean|null>(null),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<IdentificationResult|null>(null);const sequence=useRef(0);
 useEffect(()=>{fetch('/api/identify').then(r=>r.json()).then(v=>setAvailable(v.available)).catch(()=>setAvailable(false));},[]);
 async function choose(file?:File){if(!file)return;const id=++sequence.current;setError('');setResult(null);setBusy(true);try{const photo=await preparePhoto(file);if(id===sequence.current)setImage(photo);}catch(e){setError((e as Error).message);}finally{if(id===sequence.current)setBusy(false);}}
 async function identify(){setBusy(true);setError('');setResult(null);try{const r=await fetch('/api/identify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image,consent}),signal:AbortSignal.timeout(55000)});const data=await r.json();if(!r.ok)throw Error(data.error);setResult(data);}catch(e){setError(e instanceof Error?e.message:'判別できませんでした。');}finally{setBusy(false);}}
 return <section className={s.panel}><h2>写真を選ぶ</h2><p>魚全体を横から、明るい場所で撮影してください。撮影のために魚へ触ったり、危険な場所へ近づいたりしないでください。</p><div className={s.actions}><label className={s.button}>カメラで撮影<input type="file" accept="image/*" capture="environment" onChange={e=>choose(e.target.files?.[0])} disabled={busy} className={s.fileInput}/></label><label className={`${s.button} ${s.secondary}`}>写真を選択<input type="file" accept="image/*" onChange={e=>choose(e.target.files?.[0])} disabled={busy} className={s.fileInput}/></label></div>{image&&<img className={s.preview} src={image} alt="判別する魚の写真"/>}<p className={s.meta}>選んだ写真は送信前に縮小し、位置情報等の付加情報を除きます。顔・車のナンバー・個人情報が写らない写真を使用してください。</p>{available===false&&<p className={s.notice}>画像判別は接続準備中です。写真はまだ送信されていません。<Link href="/fish">魚図鑑で特徴から探す →</Link></p>}<label className={s.consent}><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>この写真をOpenAIの画像解析サービスへ送信することに同意します。UOLINKのサーバーには写真を保存しません。外部サービスのデータの扱いは<Link href="/identify#privacy">こちら</Link>。</span></label><button className={s.button} onClick={identify} disabled={!image||!consent||busy||available!==true}>{busy?'写真を処理しています…':'魚の候補を調べる'}</button><p role="status" className={error?s.error:undefined}>{error}</p>{result&&<div aria-live="polite"><h2>魚種の候補</h2><p className={s.notice}>参考情報です。候補や確度は正解の保証ではなく、食べられるか・触ってよいかは判定できません。</p>{result.candidates.map((c,i)=>{const f=fish.find(f=>f.slug===c.slug);return f?<article key={c.slug} className={s.card}><h3>候補{i+1}：{f.name}</h3><p className={s.meta}>特徴の一致：{{high:'高め',medium:'中程度',low:'低め'}[c.confidence]}（AIの目安）</p><p>{c.reason}</p><p>確認する特徴：{c.check}</p>{f.danger&&<p className={s.notice}>危険部位があります。素手で触らず図鑑の注意を確認してください。</p>}<Link href={`/fish/${c.slug}`}>{f.name}の見分け方・注意を見る →</Link></article>:null;})}{!result.candidates.length&&<p>登録図鑑の中に十分な根拠のある候補を見つけられませんでした。</p>}<p>{result.uncertain}</p><Link href="/fish">図鑑でほかの魚を探す →</Link></div>}</section>;
}
