import type {FishingMapEntry} from './fishing-map-data';

const common={type:'spot' as const,verifiedAt:'2026-09-15',season:'季節・開放期間は公式案内を確認',beginner:true,kids:true,parking:false,toilet:false,guideSlugs:['fishing-first-checklist'],timing:'当日の開場・天候・釣果を確認して計画する。',tips:['受付で当日の利用範囲と釣り方を確認する'],bestFor:['管理された場所での海釣り']};
export const nationalSpots:FishingMapEntry[]=[
 {positionNote:"地理院地図・航空写真と施設案内を照合した釣りエリアの代表位置。ピンは駐車場や入口ではありません。利用区画は現地の案内で確認してください。",...common,slug:'tomakomai-ippon',name:'苫小牧港海釣り施設 一本防波堤',prefecture:'北海道',area:'北海道・苫小牧',terrain:'pier',lat:42.613244,lng:141.776397,kids:false,parking:true,toilet:true,fish:['サバ','ブリ','アイナメ'],fishSlugs:['saba','buri','ainame'],methods:['サビキ'],methodSlugs:['sabiki'],note:'苫小牧東港の指定区間を開放する有料施設。未就学児は入場できないため、年齢条件を確認して計画します。',googleQuery:'苫小牧 一本防波堤 海釣り施設',access:'苫小牧市字弁天。公式アクセス図の経路と管理棟での受付に従う。',field:'防波堤の指定された東側。西側の胸壁からの釣りは禁止。',caution:['救命胴衣必須。危険表示ラインを越えない','開放日は公式の最新告知を確認。港全域の釣り許可を意味しない'],sources:[{label:'運営者：利用案内',url:'https://ippon-b.com/guide/'},{label:'公式アクセス',url:'https://ippon-b.com/access/'},{"label":"国土地理院：釣りエリアの位置を照合（2026-09-18）","url":"https://maps.gsi.go.jp/#18/42.613244/141.776397/&base=std&ls=std&disp=1"}]},
 {positionNote:"地理院地図・航空写真と施設案内を照合した釣りエリアの代表位置。ピンは駐車場や入口ではありません。利用区画は現地の案内で確認してください。",...common,slug:'asamushi-umizuri',name:'浅虫海づり公園',prefecture:'青森県',area:'青森・浅虫',terrain:'pier',lat:40.890466,lng:140.857558,toilet:true,fish:['アイナメ','アジ','サバ','ウマヅラハギ','スズキ'],fishSlugs:['ainame','aji','saba','umazurahagi','suzuki'],methods:['釣台からの餌釣り'],methodSlugs:[],note:'陸奥湾に突き出た釣台と、釣具・餌を扱う管理棟があります。スタッフによる釣り指導と救命胴衣の貸出が案内されています。',googleQuery:'浅虫海づり公園',access:'青森市浅虫。公園入口はスロープ。最新の開園期間を市の案内で確認。',field:'管理棟と釣台を備える海釣り施設。',sourceUpdatedAt:'2026-06-17',caution:['10歳未満は保護者または引率者の付き添いが必要','持込竿は2本まで。臨時休園や当日の指示を優先'],sources:[{label:'青森市：施設・対象魚・利用条件',url:'https://www.city.aomori.aomori.jp/bunka_sports_kankou/kankou/1005230/1005243/1005246.html'},{"label":"国土地理院：釣りエリアの位置を照合（2026-09-18）","url":"https://maps.gsi.go.jp/#18/40.890466/140.857558/&base=std&ls=std&disp=1"}]},
 {...common,slug:'honmoku-fishing',name:'本牧海づり施設',prefecture:'神奈川県',area:'神奈川・横浜・東京湾',terrain:'pier',parking:true,toilet:true,fish:[],methods:['利用可能な釣法は施設へ確認'],note:'横浜市中区本牧ふ頭の海釣り施設。駐車場、多目的トイレ、入口脇のスロープが市の施設情報で確認できます。',googleQuery:'本牧海づり施設',access:'横浜市中区本牧ふ頭1。市バス「海づり桟橋」方面のアクセスを確認。',field:'港に出入りする船を眺められる釣り施設。釣座ごとの利用条件は運営案内を確認。',sourceUpdatedAt:'2025-12-05',caution:['混雑・天候・釣座により利用条件が変わるため、運営者の最新案内を確認','魚種と釣法の詳細は最新の釣果・ルールを確認'],sources:[{label:'横浜市：設備情報',url:'https://www.city.yokohama.lg.jp/kenko-iryo-fukushi/fukushi-kaigo/fuku-machi/barrierfree/shisetsu/shisetsu/06094.html'},{label:'施設公式サイト',url:'https://yokohama-fishingpiers.jp/honmoku/'}]},
 {positionNote:"地理院地図・航空写真と施設案内を照合した釣りエリアの代表位置。ピンは駐車場や入口ではありません。利用区画は現地の案内で確認してください。",...common,slug:'niigata-happyfishing',name:'新潟東港第2東防波堤 管理釣り場',prefecture:'新潟県',area:'新潟・聖籠町',terrain:'pier',lat:38.008556,lng:139.239864,beginner:false,kids:false,fish:['アオリイカ'],fishSlugs:['aoriika'],methods:['釣法・釣座は管理者へ確認'],note:'NPO法人ハッピーフィッシングが運営する開放釣り場。東港の他の防波堤へ自由に立ち入れるわけではありません。',googleQuery:'ハッピーフィッシング 新潟東港',access:'新潟東港第2東防波堤。公式アクセス図と受付手順に従う。',field:'開放日・開放区間を管理する防波堤。強風などで早期閉鎖する場合がある。',caution:['対象年齢・救命胴衣・入場ルールを運営者ページで確認','開放区間以外の防波堤は立入禁止'],sources:[{label:'運営者：開放状況・釣果',url:'https://happyfishing.jp/'},{label:'新潟県：開放区間と立入禁止',url:'https://www.pref.niigata.lg.jp/sec/niigata_kouwan/1356860445805.html'},{label:'公式アクセス',url:'https://happyfishing.jp/access/'},{"label":"国土地理院：釣りエリアの位置を照合（2026-09-18）","url":"https://maps.gsi.go.jp/#18/38.008556/139.239864/&base=std&ls=std&disp=1"}]},
 {positionNote:"地理院地図・航空写真と施設案内を照合した釣りエリアの代表位置。ピンは駐車場や入口ではありません。利用区画は現地の案内で確認してください。",...common,slug:'atami-port-fishing',name:'熱海港海釣り施設',prefecture:'静岡県',area:'静岡・熱海・伊豆',terrain:'pier',lat:35.093138,lng:139.08052,parking:true,toilet:true,fish:['アジ','ヒラメ','カワハギ','アオリイカ','シイラ','サバ','ウルメイワシ','メジナ','ブリ','ボラ'],fishSlugs:['aji','hirame','kawahagi','aoriika','shiira','saba','urume','mejina','buri','bora'],methods:['エギング','フカセ'],methodSlugs:['eging','fukase'],note:'熱海港外防波堤の内海側を利用する管理施設。貸竿・餌販売があり、季節ごとに多様な魚が対象になります。',googleQuery:'熱海港海釣り施設',access:'熱海後楽園方面のバスと徒歩。入場は管理棟で受付。',field:'湾内側の指定区間。外側は立入禁止。',caution:['泳がせ釣り・ヤエン・生き餌のウキ釣りは禁止','夜間侵入は禁止。花火開催日・荒天時の変更は運営者告知を優先'],sources:[{label:'熱海市：設備・対象魚',url:'https://www.city.atami.lg.jp/shisetsu/bunka/1002029/1002032.html'},{label:'運営者：最新ルール・休園情報',url:'https://www5d.biglobe.ne.jp/atami/'},{"label":"国土地理院：釣りエリアの位置を照合（2026-09-18）","url":"https://maps.gsi.go.jp/#18/35.093138/139.08052/&base=std&ls=std&disp=1"}]},
 {positionNote:"地理院地図・航空写真と施設案内を照合した釣りエリアの代表位置。ピンは駐車場や入口ではありません。利用区画は現地の案内で確認してください。",...common,slug:'shimonoseki-fishing',name:'下関フィッシングパーク',prefecture:'山口県',area:'山口・下関・響灘',terrain:'pier',lat:34.060588,lng:130.901113,fish:[],methods:['サビキ'],methodSlugs:['sabiki'],note:'下関市吉見古宿町にある桟橋型の釣り施設。施設公式サイトで釣り教室や利用案内を確認できます。',googleQuery:'下関フィッシングパーク',access:'下関市吉見古宿町10-1。運営者のアクセスと受付案内を確認。',field:'響灘へ張り出す釣り桟橋。',caution:['当日の開園状況・釣法の制限を運営者へ確認','小さな子どもから目を離さず、救命胴衣を着用'],sources:[{label:'施設公式：利用・アクセス',url:'https://shimonoseki-fishingpark.com/index.html'},{"label":"国土地理院：釣りエリアの位置を照合（2026-09-18）","url":"https://maps.gsi.go.jp/#18/34.060588/130.901113/&base=std&ls=std&disp=1"}]},
 {...common,slug:'naruto-okazaki',name:'岡崎海岸（釣り）',prefecture:'徳島県',area:'徳島・鳴門',terrain:'shore',lat:34.182421,lng:134.623069,toilet:true,fish:['スズキ','アジ','カサゴ','アオリイカ','タチウオ','シロギス','クロダイ','メジナ'],fishSlugs:['suzuki','aji','kasago','aoriika','tachiuo','kisu','chinu','mejina'],methods:['当日の利用範囲と釣法を現地確認'],note:'紀伊水道と小鳴門海峡に面する海岸。徳島県の観光案内では季節別の魚種とトイレ・休憩スペースが紹介されています。',googleQuery:'岡崎海岸 鳴門',access:'鳴門市撫養町岡崎。鳴門駅から車で約5分の案内。',field:'海岸沿いの足場。ポールがあっても転落防止は自己管理が必要。',caution:['現地の釣り・立入禁止表示と漁業作業を優先','潮が速く風波の影響を受ける。子どもの釣座は慎重に選ぶ'],sources:[{label:'徳島県観光情報 阿波ナビ',url:'https://www.awanavi.jp/archives/spot/1527'}]},
 {...common,slug:'kamoike-umizuri',name:'鴨池海づり公園',prefecture:'鹿児島県',area:'鹿児島・錦江湾',terrain:'pier',parking:true,fish:['マダイ','カサゴ','アジ','カンパチ','コロダイ'],fishSlugs:['madai','kasago','aji','kanpachi'],methods:['サビキ','胴突き'],methodSlugs:['sabiki','douzuki'],note:'錦江湾で釣りを楽しむ鹿児島市の管理施設。足元に水深があり、道具とオモリは施設の案内に合わせます。',googleQuery:'鴨池海づり公園',access:'鹿児島市与次郎2-9-12。有料駐車場あり。',field:'市の案内では水深20〜25m、潮が比較的速い釣り場。',waterDepth:'20〜25m（鹿児島市案内）',sourceUpdatedAt:'2025-04-01',caution:['投げ釣り禁止。撒き餌はアミカゴによるものを除き禁止','竿数・所定の釣り場所・係員の指示を守る'],sources:[{label:'鹿児島市：対象魚・仕掛け・禁止事項',url:'https://www.city.kagoshima.lg.jp/seisanryutu/shisetsu/kanko/017.html'}]},
 {...common,slug:'motobu-ikada',name:'本部釣りイカダ',prefecture:'沖縄県',area:'沖縄・本部町',terrain:'raft',lat:26.670498,lng:127.880707,parking:true,toilet:true,fish:[],methods:['イカダ釣り体験'],note:'本部町のイカダ釣り体験。手ぶら向けの案内があり、夜釣りは予約が必要です。地図の点は受付側の参考位置です。',googleQuery:'本部釣りイカダ',access:'本部町谷茶29-72の受付。利用時間・渡船・予約を事業者に確認。',field:'沖のイカダを利用する体験。集合場所と実際の釣座は異なる場合がある。',nightFishing:'夜釣りは要予約（公式観光案内）',caution:['大時化などで中止。乗船条件と救命胴衣を確認','魚種と持ち帰り・調理条件は予約時に事業者へ確認'],sources:[{label:'沖縄北部公式観光サイト：施設情報',url:'https://yambaru-tour.net/spot/1230/'}]}
];
