import type {FishingMapEntry} from './fishing-map-data';
// Source dates and actual waterfront positions reviewed 2026-09-19. No address geocoding.
export const kansaiReopeningEntries:FishingMapEntry[]=[
 {
 slug:'kamome-bridge-wavebreak',type:'spot',name:'かもめ大橋下の波止',area:'大阪市住之江区・南港',prefecture:'大阪府',primaryType:'pier',terrain:'pier',lat:34.61085,lng:135.41968,parking:false,toilet:false,beginner:false,kids:false,
 fish:['マアジ','チヌ','タチウオ','スズキ'],methods:['アジング','ウキ釣り'],methodSlugs:['ajing','uki'],season:'回遊魚は夏〜秋、チヌ・スズキは季節に応じて',
 note:'かもめ大橋の南西側、白灯のある波止。2026年7月の現地投稿で補修後の再開と階段整備が報告されています。駐車場はありません。橋周辺すべてではなく、開放された波止を利用する釣り場です。',
 googleQuery:'かもめ大橋 下 波止',access:'徒歩・自転車等で橋下の開放部へ。路上や港湾作業用地へ駐車しない。',field:'大和川河口側へ延びる波止。橋の道路上や対岸の業務用岸壁ではありません。',bestFor:['アジング','潮の変化を見ながらのウキ釣り'],timing:'明るいうちに入口・足場を確認。濁りや風、潮の速さで釣り方を調整。',
 tips:['軽いジグヘッドで表層から沈める時間を変え、アジの棚を探る。','船が通る時は仕掛けを回収し、航路へ投げ続けない。'],caution:['駐車・トイレ設備のない場所。車の来訪先として案内する地点ではありません。','柵・閉鎖表示のある隣接護岸へ入らず、開放範囲内で利用。増水や強風時は避ける。'],
 verifiedAt:'2026-09-19',sourceUpdatedAt:'2026-07',positionNote:'国土地理院地図で橋の南西側の細い波止上へ配置。道路中央の位置とは分けています。',sources:[{label:'osakaajing：補修後の開放・階段・駐車場なしの現地報告',url:'https://www.instagram.com/p/DauDz8oP8t0/'},{label:'国土地理院：橋下の波止',url:'https://maps.gsi.go.jp/#18/34.61085/135.41968/&base=std&ls=std&disp=1'}]
 },
 {
 slug:'minamiashiya-east-shore',type:'spot',name:'南芦屋浜 東護岸（北側）',area:'芦屋市・海洋町',prefecture:'兵庫県',primaryType:'pier',terrain:'pier',lat:34.71115,lng:135.32209,beginner:false,kids:false,
 fish:['マアジ','サヨリ','チヌ','タチウオ'],methods:['サビキ釣り','ウキ釣り','アジング'],methodSlugs:['sabiki','uki','ajing'],season:'小魚の回遊は夏〜秋中心。チヌは水温と潮に応じて',
 note:'芦屋マリーナの外側、水道に面した東護岸の北側区間。2026年8月の釣具店現地報告で東護岸の開放が確認できます。南護岸の利用条件とは区別して探す場所です。',googleQuery:'南芦屋浜 東護岸 北側',access:'公共駐車場等から徒歩で東護岸へ。ホテルやマリーナの専用駐車場を無断利用しない。',field:'水道に面した護岸で、足元に敷石が入る区間があります。',bestFor:['小魚の回遊探し','チヌのウキ釣り'],timing:'朝夕の回遊と潮の動く時間を目安に。花火・イベント時は臨時規制があります。',
 tips:['足元の敷石へ掛けないよう、仕掛けは手前まで引きずらず早めに回収する。','サヨリは水面付近、アジは中層〜底寄りも探り分ける。'],caution:['転落防止柵のない区間があるため救命胴衣を着用。','南護岸・ビーチ・マリーナ内を同じ利用範囲と考えず、区間の表示に従う。'],verifiedAt:'2026-09-19',positionNote:'芦屋マリーナ外側の東護岸へ配置。南ベランダとは別地点。',sources:[{label:'フィッシングマックス：2026年8月2日の開放状況',url:'https://fishingmax.co.jp/fishingpost/1667229'},{label:'芦屋市：南芦屋浜の区間別利用状況',url:'https://www.city.ashiya.lg.jp/gairoju/minamniryokuchi.html'},{label:'国土地理院：東護岸',url:'https://maps.gsi.go.jp/#17/34.71115/135.32209/&base=std&ls=std&disp=1'}]
 },
 {
 slug:'hanaichiba-park-shore',type:'spot',name:'花市場公園前の護岸',area:'泉大津市・小津島町',prefecture:'大阪府',primaryType:'pier',terrain:'pier',lat:34.52050,lng:135.40110,beginner:true,kids:false,parking:true,toilet:true,
 fish:['チヌ','スズキ','マアジ'],methods:['ウキ釣り','サビキ釣り'],methodSlugs:['uki','sabiki'],season:'エビ撒きは春など、小魚は回遊次第',note:'泉大津大橋の北側にある公園前の短い親水護岸。2026年3月にも釣具店のエビ撒き釣果報告があります。助松ふ頭の物流岸壁全体を利用できる場所ではありません。',googleQuery:'花市場公園 泉大津',access:'小津島町の公園側から徒歩。駐車場の利用時間と閉門を確認して入る。',field:'公園前の限られた護岸。周囲の作業岸壁・フェリー施設と区別する。',bestFor:['エビ撒きのウキ釣り','短時間のサビキ'],timing:'潮が動く時間と、釣り座に入れる公園の利用時間を合わせる。',tips:['ウキの流れる方向を見て、少量ずつ同じ筋へ餌を入れる。','係船ロープや作業船から十分離れて竿を出す。'],caution:['物流施設・フェリー岸壁・柵の先へ立ち入らない。','公園利用者の通行を妨げず、針と餌を残さない。'],verifiedAt:'2026-09-19',positionNote:'公園中央や駐車場ではなく、泉大津大橋北側の水際へ配置。',sources:[{label:'フィッシングマックス：なぎさ公園・花市場公園の釣果',url:'https://fishingmax.co.jp/fishingpost/1591801'},{label:'釣り場案内図：公園前護岸と周辺制限',url:'https://www.taikobo.net/place/map/pdf/sensyu1.pdf'},{label:'国土地理院：公園前の護岸',url:'https://maps.gsi.go.jp/#17/34.52050/135.40110/&base=std&ls=std&disp=1'}]
 },
 {
 slug:'izumiotsu-nagisa-shore',type:'spot',name:'泉大津なぎさ公園の護岸',area:'泉大津市・なぎさ町',prefecture:'大阪府',primaryType:'pier',terrain:'pier',lat:34.50953,lng:135.39844,beginner:true,kids:true,parking:true,toilet:true,
 fish:['マアジ','カタクチイワシ','チヌ','スズキ'],methods:['サビキ釣り','ウキ釣り'],methodSlugs:['sabiki','uki'],season:'サビキは夏〜秋の回遊時、ウキ釣りは潮と水温次第',note:'港奥にある公園の海側テラス。柵の内側からサビキやウキ釣りをする候補で、泉大津の市街地から訪ねやすい釣り場です。広い沖向きの岸壁とは潮の流れ方が異なります。',googleQuery:'泉大津 なぎさ公園',access:'なぎさ町の公園へ入り、海側のテラスへ。公園駐車場は満車・閉門に注意。',field:'港の奥に面した護岸。公園に隣接する港湾施設は釣り場に含めない。',bestFor:['親子のサビキ','エビ撒きのウキ釣り'],timing:'小魚の群れが入る朝夕。船の往来と公園行事にも配慮。',tips:['アジが見えなければ、同じ位置で棚を少しずつ変える。','釣れた小魚は手返しよく外し、足元の餌を洗い流してから帰る。'],caution:['柵に登らず、小さな子どもは保護者がそばに付く。','公園行事や工事で使用できない区画に入らない。'],verifiedAt:'2026-09-19',positionNote:'町の住所の中心ではなく、海側テラスの位置へ補正。',sources:[{label:'フィッシングマックス：現地釣果',url:'https://fishingmax.co.jp/fishingpost/1591801'},{label:'護岸・設備の案内',url:'https://www.taikobo.net/place/map/pdf/sensyu1.pdf'},{label:'国土地理院：海側テラス',url:'https://maps.gsi.go.jp/#18/34.50953/135.39844/&base=std&ls=std&disp=1'}]
 },
 {
 slug:'rinku-marble-beach',type:'spot',name:'りんくう公園 マーブルビーチ',area:'泉佐野市・田尻町',prefecture:'大阪府',primaryType:'beach',terrain:'beach',lat:34.40315,lng:135.28860,parking:true,toilet:true,beginner:false,kids:false,
 fish:['シロギス','メバル','マアジ'],methods:['投げ釣り','アジング','メバリング'],methodSlugs:['choinage','ajing','mebaring'],season:'キスは初夏〜秋、メバルは低水温期など',note:'りんくう公園の南側に続く玉石の海岸。公園北側の内海とは別の外海側で、釣り場案内には投げ釣りやライトゲームの実績が掲載されています。散策・イベント利用と譲り合って利用します。',googleQuery:'りんくう マーブルビーチ 田尻町',access:'りんくう公園の駐車場や公共交通から徒歩。田尻町側のマーブルビーチへ。',field:'白い玉石が敷かれた海岸。田尻漁港の岸壁や内海と分けて扱う。',bestFor:['投げ釣りで砂地を探る','外海側のライトゲーム'],timing:'海岸が空いていて波風の弱い時間。イベント開催中は利用区画を優先。',tips:['後方の散策者を確認してから投げ、近くに人が来たら中断する。','玉石が濡れて滑る時は水際へ下りず、荒天では撤退する。'],caution:['りんくう公園の内海は釣り禁止。内海や閉鎖区画へ誘導する地点ではありません。','園内の工事・イベント規制に従う。海水浴は禁止されており、急に深くなる。'],verifiedAt:'2026-09-19',officialUrl:'https://rinku.osaka-park.or.jp/',positionNote:'田尻町の位置情報と地理院地図でマーブルビーチの水際を照合。',sources:[{label:'田尻町：マーブルビーチと所在地',url:'https://www.town.tajiri.osaka.jp/kakukanojoho/jigyobu/sangyoshinkoka/3/1/633.html'},{label:'釣り場案内：マーブルビーチ',url:'https://www.taikobo.net/place/map/pdf/sensyu5.pdf'},{label:'公園管理者：内海の釣り禁止',url:'https://rinku.osaka-park.or.jp/playingsand'},{label:'国土地理院：玉石海岸の位置',url:'https://maps.gsi.go.jp/#17/34.40315/135.28860/&base=std&ls=std&disp=1'}]
 },
 {
 slug:'jgreen-offshore-wall',type:'spot',name:'J-GREEN堺前の波止（渡船）',area:'堺市・堺浜',prefecture:'大阪府',primaryType:'pier',terrain:'pier',lat:34.60378,lng:135.43954,beginner:false,kids:false,
 fish:['チヌ'],methods:['チヌ落とし込み','フカセ釣り'],methodSlugs:['fukase'],season:'チヌを季節に応じた餌と棚で狙う',note:'J-GREEN堺の海側から離れた細い波止。チヌの落とし込みで知られ、2026年にも渡船を利用した釣行報告があります。サッカー施設や陸側の護岸から歩いて入る釣り場ではありません。',googleQuery:'Jグリーン 波止 渡船',access:'渡船業者へJ-GREEN行きの運航・渡堤可否を事前確認。出島側の夢フィッシング等から乗船する。',field:'陸側護岸との間に水路を挟む独立した波止。',bestFor:['チヌの落とし込み','護岸際のフカセ'],timing:'渡船の運航時間内。迎えの便と強風時の撤収を船長と確認。',tips:['柱や継ぎ目の際を、餌が自然に落ちる速度で探る。','水路側と沖側で水深が違うので、同じ棚のまま釣り続けない。'],caution:['救命胴衣・玉網を持参し、渡船が認めた区画だけを利用する。','J-GREEN敷地やフェンスを越えて陸から入らない。'],verifiedAt:'2026-09-19',positionNote:'釣行記の空撮と地理院地図を照合し、陸側ではなく離れた波止上に配置。',sources:[{label:'2026年の夢フィッシング利用釣行',url:'https://ameblo.jp/mikioshin/entry-12964537019.html'},{label:'波止と陸側護岸の形状・空撮',url:'https://ameblo.jp/futochinu/entry-12430934839.html'},{label:'国土地理院：独立した波止',url:'https://maps.gsi.go.jp/#18/34.60378/135.43954/&base=std&ls=std&disp=1'}]
 },
 {
 slug:'yachiyomaru-tarui',type:'boat',name:'八千代丸',area:'泉南市・樽井',prefecture:'大阪府',primaryType:'boat',terrain:'boat',port:'樽井漁港',lat:34.38073824,lng:135.25819466,parking:true,toilet:true,beginner:true,kids:false,
 fish:['タチウオ','マアジ','メバル'],methods:['船タチウオテンヤ','船サビキ'],methodSlugs:['tachiuo-tenya','sabiki'],season:'季節の乗合便に合わせて釣り物が変わる',note:'樽井漁港から出船する釣り船。タチウオやアジなど、その時期の便を選んで予約します。電動配線・トイレを備え、釣り物に合わせた仕掛けを事前に揃えると準備がスムーズです。',googleQuery:'八千代丸 樽井漁港',officialUrl:'https://osaka.tsurisoku.com/yachiyomaru/',access:'漁港のスロープを下り右奥の指定駐車場所から乗船場へ。予約時の集合案内を優先。',field:'樽井漁港の乗船場所を示す地点。釣りをする海域は便により異なる。',bestFor:['大阪湾の船タチウオ','季節のアジ・メバル便'],timing:'出船カレンダーで釣り物を選び、集合時刻は予約時に確認。',tips:['テンヤ・オモリの号数と電動リール使用可否を予約時に確認する。','竿を置く時も仕掛けの針先を周囲へ向けない。'],caution:['料金・出船時刻・仕掛けは船宿の最新指定を優先。','救命胴衣を着用し、出船・中止の連絡を確認する。'],verifiedAt:'2026-09-19',positionNote:'船宿公式アクセス地図の地点を樽井漁港の乗船側で照合。',sources:[{label:'八千代丸：アクセス・乗船場',url:'https://osaka.tsurisoku.com/yachiyomaru/access/'},{label:'八千代丸：船内設備',url:'https://osaka.tsurisoku.com/yachiyomaru/about/'}]
 },
 {
 slug:'minatomaru-okadaura',type:'boat',name:'湊丸',area:'泉南市・岡田浦',prefecture:'大阪府',primaryType:'boat',terrain:'boat',port:'岡田浦漁港',lat:34.38937,lng:135.27343,parking:true,beginner:true,kids:false,
 fish:['タチウオ','マアジ','クログチ','マダコ'],methods:['船タチウオテンヤ','船タコ釣り'],methodSlugs:['tachiuo-tenya','tako-egi'],season:'釣り物は出船予定表に合わせて変わる',note:'岡田浦漁港を拠点に大阪湾へ出る釣り船。タチウオ・アジ・クログチ・タコなどの便を案内しています。魚種だけでなく、その日の釣り方と指定の仕掛けを確認して予約します。',googleQuery:'湊丸 岡田浦',officialUrl:'http://www.minatomaru.sakura.ne.jp/index.html',access:'岡田浦漁港の朝市側へ。船宿案内の経路で指定駐車場へ入り、階段から乗船場所へ。',field:'岡田浦漁港の乗船岸壁付近。自由に陸釣りをする場所の案内ではありません。',bestFor:['大阪湾の季節の船釣り','船タチウオ'],timing:'予約した便の集合時間に合わせる。釣り物は予定表で確認。',tips:['餌の用意・販売とオモリの号数を前日までに確認する。','タコ便と魚の便では針・竿が異なるので予約便に合わせる。'],caution:['船宿指定の集合場所・仕掛けを優先。','漁港の荷揚げと朝市の通行を妨げない。'],verifiedAt:'2026-09-19',positionNote:'船宿の乗船案内図と地理院地図の港奥岸壁を照合。',sources:[{label:'湊丸：公式案内',url:'http://www.minatomaru.sakura.ne.jp/index.html'},{label:'湊丸：乗船・駐車経路図',url:'http://www.minatomaru.sakura.ne.jp/route.html'}]
 },
 {
 slug:'yume-fishing-dejima',type:'boat',name:'夢フィッシング（堺出島）',area:'堺市・出島漁港',prefecture:'大阪府',primaryType:'boat',terrain:'boat',port:'堺出島漁港',lat:34.57570,lng:135.45758,parking:true,beginner:false,kids:false,
 fish:['チヌ','タチウオ','マアジ'],methods:['チヌ落とし込み','ウキ釣り','アジング'],methodSlugs:['uki','ajing'],season:'渡堤先と魚の回遊に応じて',note:'堺出島漁港とれとれ市内を拠点とする渡船。沖の波止や護岸へ渡り、チヌなどを狙う釣行に利用します。釣り船の船上釣りとは違い、渡った先で釣るスタイルです。',googleQuery:'堺出島 夢フィッシング',officialUrl:'https://yumefishing.web.fc2.com/',access:'堺出島漁港とれとれ市内の指定集合場所へ。公式アクセス図で進入路を確認。',field:'出島漁港の渡船乗船場所。運航先と上陸区画は船長の案内で決まります。',bestFor:['渡船でのチヌ釣り','沖波止の回遊魚狙い'],timing:'公式釣果ページの営業日と運航便を確認して予約・来場。',tips:['渡堤先の足場に合う靴と玉網、飲料を乗船前に揃える。','迎えの時刻と悪天候時の連絡方法を確認する。'],caution:['救命胴衣は持参。公式案内ではレンタルなし。','上陸できない場所へ自己判断で移動しない。'],verifiedAt:'2026-09-19',positionNote:'公式渡船図の出島漁港乗り場と水際を照合。駐車場中心から港側へ調整。',sources:[{label:'夢フィッシング：渡船・装備の案内',url:'https://yumefishing.web.fc2.com/system.html'},{label:'夢フィッシング：アクセス',url:'https://yumefishing.web.fc2.com/access.html'}]
 }
];
