import type {GuideArticle} from '@/lib/guide-articles';

export const extraGuideArticles5:GuideArticle[]=[
 {slug:'fishing-wind-limit',title:'釣りは風速何mまでできる？堤防・船の目安',query:'釣り 風速 何mまで',summary:'釣行判断で迷いやすい風速の目安を、堤防と船で整理。',answer:'堤防は風速5m/s前後から釣りづらさが増え、7〜8m/s以上では中止も検討。船は船宿判断が最優先。数字だけでなく風向き・波・足場を合わせて判断する。',category:'釣行準備',sections:[{heading:'堤防は5m/s前後が境目',body:'軽い仕掛けやエギング、アジングは特に風の影響を受けやすい。向かい風では飛距離と操作性が大きく落ちる。'},{heading:'7〜8m/s以上は慎重に',body:'キャストが難しくなり、道具が飛ぶ、転倒するなど安全面のリスクも上がる。'},{heading:'風向きで体感は変わる',body:'追い風や風裏では釣りやすくても、横風や向かい風では同じ風速でも難易度が高い。'},{heading:'船は船長判断',body:'沖は陸より風が強いことも多い。出船可否・ポイント変更は船宿の判断を優先。'}],related:[{label:'釣りスポットを見る',href:'/spots'},{label:'海釣り初心者の道具',href:'/guide/beginner-sea-fishing-setup'}]},
 {slug:'fishing-rain',title:'雨の日は魚が釣れる？海釣りで雨が有利・不利になる条件',query:'雨の日 釣り 釣れる',summary:'雨の日の海釣りで魚の活性や安全面がどう変わるかを解説。',answer:'小雨は水面の光量を落とし、魚の警戒心が下がることもある。一方で大雨・雷・強風は中止。雨そのものより、濁り・水温・風・雷をセットで見る。',category:'釣行準備',sections:[{heading:'小雨がプラスになる場面',body:'光量低下で魚が浅場へ出やすくなることがある。人が少なくプレッシャーが下がるのも利点。'},{heading:'大雨後の濁り',body:'河口では濁りと淡水流入が強くなり、魚種によって好不調が分かれる。'},{heading:'雷は即撤収',body:'釣竿は長く高い導体。遠雷でも無理せず釣りを中止する。'},{heading:'装備',body:'レインウェア、滑りにくい靴、防水バッグを準備。傘を差しながらの釣りは避ける。'}],related:[{label:'初心者向け道具',href:'/guide/beginner-sea-fishing-setup'},{label:'釣りスポット',href:'/spots'}]},
 {slug:'fishing-tide-best',title:'釣りは大潮が一番釣れる？潮回りの見方',query:'釣り 大潮 小潮 どっち',summary:'大潮・中潮・小潮で何が変わるのか、初心者向けに整理。',answer:'大潮だから必ず釣れるわけではない。潮が速すぎる場所では小潮が釣りやすいこともある。重要なのは潮回りの名前より、実際に潮が動く時間と流れ方。',category:'釣行準備',sections:[{heading:'大潮',body:'干満差が大きく潮が動きやすい。一方、海峡部では速すぎて釣りにくくなることも。'},{heading:'小潮',body:'流れが緩く、底取りや軽い仕掛けが扱いやすい場面がある。'},{heading:'時合いを見る',body:'満潮・干潮そのものより、潮が動き始める時間に反応が出ることも多い。'},{heading:'魚種ごとに相性が違う',body:'タイラバ、エギング、サビキなど釣法によって扱いやすい潮は変わる。'}],related:[{label:'タイラバ',href:'/methods/tai-rubber'},{label:'エギング',href:'/methods/eging'}]},
 {slug:'fishing-before-after-high-tide',title:'満潮と干潮どっちが釣れる？狙う時間の考え方',query:'釣り 満潮 干潮 どっち',summary:'満潮前後・干潮前後の特徴と、釣りやすい時間帯の見つけ方。',answer:'「満潮なら釣れる」「干潮は釣れない」とは限らない。潮位より、潮が動いているか・狙うポイントに水深があるかが重要。まず満潮前後2時間を基準に試すと分かりやすい。',category:'釣行準備',sections:[{heading:'満潮前後',body:'岸際まで魚が入りやすい場所があり、堤防・河口では狙いやすいことが多い。'},{heading:'干潮前後',body:'地形が見えやすく、ブレイクや溝を把握できるメリットがある。'},{heading:'潮止まり',body:'完全に流れが止まると反応が落ちることもある。潮が再び動き始める時間に注目。'},{heading:'同じ場所で記録',body:'釣れた潮位と時間を残すと、そのポイント独自のパターンが見えてくる。'}],related:[{label:'釣りGUIDE',href:'/guide'},{label:'釣りスポット',href:'/spots'}]},
 {slug:'fg-knot-vs-pr-knot',title:'FGノットとPRノットどっちがいい？使い分けを比較',query:'FGノット PRノット どっち',summary:'PEとリーダーの結束で定番のFGとPRを、用途別に比較。',answer:'岸釣りや汎用性ならFGノット、太いPE・太リーダーを強く安定して結ぶ船釣りならPRノットが有力。どちらも結束強度より「正しく組める方」を選ぶ。',category:'釣具・仕掛け',sections:[{heading:'FGノット',body:'道具なしでも組め、ショアジギング・エギング・シーバスなど幅広く使える。'},{heading:'PRノット',body:'ボビンを使い、太いラインでも密な巻き付けを作りやすい。大型青物や船釣り向き。'},{heading:'ガイド抜け',body:'どちらも結び目を細く整えることが重要。余分な焼きコブや端糸が大きいとトラブルの原因。'},{heading:'練習優先',body:'理論上の強度差より、毎回同じ品質で組めることの方が実釣では重要。'}],related:[{label:'ショアジギングPE',href:'/guide/shore-jigging-pe'},{label:'ブリのノマセリーダー',href:'/guide/nomase-leader'}]},
 {slug:'leader-length-general',title:'ショックリーダーは何m必要？釣り方別の長さ目安',query:'ショックリーダー 長さ 何m',summary:'PEに結ぶリーダーの長さを、エギング・ショアジギング・船で比較。',answer:'ライトゲームやエギングは1〜2m、ショアジギングは1〜3m、根ズレが多い船青物では数m以上を使うこともある。長ければ正解ではなく、擦れ対策とキャスト性のバランス。',category:'釣具・仕掛け',sections:[{heading:'1〜2m',body:'エギングやライトゲームで扱いやすく、結束部をガイド外へ出しやすい。'},{heading:'ショアジギング',body:'1〜3m前後を基準に、磯やテトラでは長めへ。'},{heading:'船青物',body:'魚が船底や根へ擦れる可能性が高い釣りでは長めが安心。'},{heading:'交換の判断',body:'先端が傷んだら切り詰める。短くなりすぎたら結び直す。'}],related:[{label:'ショアジギングのリーダー長',href:'/guide/shore-jigging-leader-length'},{label:'釣具を見る',href:'/gear'}]},
 {slug:'pe-line-how-much',title:'PEラインは何m巻けばいい？堤防・船の必要量',query:'PEライン 何m 必要',summary:'150m・200m・300mのどれを選ぶか、釣り方別に整理。',answer:'堤防ルアーは150〜200mで足りることが多く、船の深場や大型青物は200〜300m以上が安心。水深だけでなく高切れ・潮流・ライン角度の余裕も見る。',category:'釣具・仕掛け',sections:[{heading:'150m',body:'エギングや近距離のライトゲームなどで使いやすい。'},{heading:'200m',body:'ショアジギングや多くの船釣りで汎用性が高い。'},{heading:'300m以上',body:'深場、速潮、大型青物などライン放出量が増える釣りで安心。'},{heading:'下巻き',body:'スプール容量が余る場合はナイロン下巻きで調整し、PEを適正位置まで巻く。'}],related:[{label:'ショアジギングPE',href:'/guide/shore-jigging-pe'},{label:'タイラバPE',href:'/guide/tairaba-pe'}]},
 {slug:'spinning-reel-size',title:'海釣りのリールは2500番？3000番？4000番？',query:'海釣り リール 2500 3000 4000 違い',summary:'スピニングリール番手の違いと、初心者の選び方を解説。',answer:'ライトゲームは2000〜2500番、サビキ・エギング・万能用途は2500〜3000番、ショアジギングや強めの釣りは4000番前後が目安。迷ったら3000番が汎用的。',category:'釣具・仕掛け',sections:[{heading:'2500番',body:'エギング、軽いサビキ、ライトなちょい投げなどに扱いやすい。'},{heading:'3000番',body:'ライン容量と重さのバランスがよく、最初の万能機として使いやすい。'},{heading:'4000番',body:'太めPEと重いルアーに対応しやすく、青物狙いで安心感がある。'},{heading:'メーカー差',body:'同じ番手でもメーカー・シリーズでスプール径や重量が違う。実際のライン容量を見る。'}],related:[{label:'初心者の道具',href:'/guide/beginner-sea-fishing-setup'},{label:'釣具を見る',href:'/gear'}]},
 {slug:'rod-length-beginner',title:'海釣り初心者の竿は何mが使いやすい？',query:'海釣り 初心者 竿 長さ',summary:'2m台・3m台・4m台の竿を、用途別に比較。',answer:'堤防の万能用途なら2.4〜3m前後が扱いやすい。遠投やウキ釣りは長め、穴釣りは短め。最初の一本は軽くて取り回しやすい長さを優先。',category:'初心者',sections:[{heading:'2〜3m',body:'サビキ、ちょい投げ、簡単なルアーなど幅広く使いやすい。'},{heading:'4m以上',body:'ウキ釣りや磯竿では便利だが、初心者には取り回しが難しいことも。'},{heading:'短竿',body:'穴釣りや船では短い方が操作しやすい。'},{heading:'重さも重要',body:'長さだけでなく自重と持ち重りを確認する。'}],related:[{label:'初心者の道具',href:'/guide/beginner-sea-fishing-setup'},{label:'釣具を見る',href:'/gear'}]},
 {slug:'cooler-size-fishing',title:'釣り用クーラーボックスは何L？10・20・30Lの選び方',query:'釣り クーラーボックス 何リットル',summary:'釣行時間・魚サイズ・人数でクーラー容量を選ぶ方法。',answer:'徒歩の短時間釣行は10〜15L、堤防の半日〜1日は20〜25L、船や大型魚は30L以上が使いやすい。容量だけでなく魚の長さと車載性も確認。',category:'釣行準備',sections:[{heading:'10〜15L',body:'アジングや短時間のサビキなど、荷物を軽くしたい釣行向き。'},{heading:'20〜25L',body:'飲み物と魚を入れやすく、堤防釣りの汎用サイズ。'},{heading:'30L以上',body:'船釣り、大型魚、家族分の魚を持ち帰る時に安心。'},{heading:'内寸を見る',body:'容量が同じでも形状で魚の入り方が違う。狙う魚の全長と内寸を確認する。'}],related:[{label:'魚の締め方',href:'/guide/fish-ikejime-basics'},{label:'釣具を見る',href:'/gear'}]},
 {slug:'ice-amount-cooler',title:'釣りの氷はどれくらい必要？クーラーの冷やし方',query:'釣り クーラー 氷 量',summary:'釣行時間と季節に合わせた氷量の考え方を解説。',answer:'夏はクーラー容量の2〜3割程度を氷・保冷剤に使う意識。冬は少なめでも持つ。魚を冷やす氷と飲み物用を分け、帰宅まで冷却を切らさない。',category:'釣行準備',sections:[{heading:'夏は多め',body:'炎天下ではクーラー本体も熱を持つ。出発前から予冷すると保冷が長持ち。'},{heading:'海水氷',body:'釣った魚を素早く冷やすなら氷＋海水で作る冷海水が便利。真水だけへ長時間浸けない。'},{heading:'保冷剤',body:'繰り返し使えて扱いやすいが、魚の隙間へ密着しにくい。氷との併用も有効。'},{heading:'帰路まで考える',body:'釣行終了時ではなく、自宅到着まで保冷できる量を準備する。'}],related:[{label:'クーラー容量の選び方',href:'/guide/cooler-size-fishing'},{label:'魚の持ち帰り方',href:'/guide/fish-carry-home'}]},
 {slug:'fish-ikejime-basics',title:'魚は釣ったらどう締める？血抜き・氷締めの基本',query:'魚 釣ったら 締め方 血抜き',summary:'釣った魚をおいしく持ち帰るための基本処理を魚サイズ別に整理。',answer:'小型魚は氷締め、大型魚は活け締め＋血抜きが基本。処理後はしっかり冷却。魚種によって最適な方法が違うため、無理に同じ処理へ統一しない。',category:'魚の扱い',sections:[{heading:'小型魚',body:'アジ・イワシなど数が多い魚は冷海水で一気に冷やすと手返しが良い。'},{heading:'大型魚',body:'脳締めやエラ切りで血抜きを行い、魚体を冷やす。'},{heading:'血抜き時間',body:'長時間海水へ放置せず、血が抜けたら冷却へ移す。'},{heading:'安全',body:'ナイフやハサミを使う時は魚を固定し、船上では特に手元に注意。'}],related:[{label:'魚の持ち帰り方',href:'/guide/fish-carry-home'},{label:'魚図鑑',href:'/fish'}]},
 {slug:'fish-carry-home',title:'釣った魚の持ち帰り方は？クーラーで鮮度を落とさない方法',query:'釣った魚 持ち帰り方 クーラー',summary:'血抜き後の魚をクーラーでどう冷やすかを解説。',answer:'魚は処理後すぐ冷やす。氷へ直接長時間当てて凍らせるより、袋やトレーを使って低温を保つ。小型魚は冷海水、大型魚は氷を効かせたクーラーへ。',category:'魚の扱い',sections:[{heading:'温度を上げない',body:'釣ってから帰宅まで低温を保つことが最優先。炎天下へ置かない。'},{heading:'真水へ浸けっぱなしにしない',body:'氷が溶けた真水へ長時間浸かると身が水っぽくなることがある。'},{heading:'魚と氷を分ける',body:'袋やスノコを使い、魚体が溶け水へ沈み続けないようにする方法も有効。'},{heading:'帰宅後',body:'できるだけ早く内臓処理・水分除去を行い、冷蔵または冷凍へ。'}],related:[{label:'魚の締め方',href:'/guide/fish-ikejime-basics'},{label:'クーラー容量',href:'/guide/cooler-size-fishing'}]},
 {slug:'fish-freeze-how-long',title:'釣った魚は冷凍で何日もつ？家庭冷凍の目安',query:'釣った魚 冷凍 何日',summary:'魚を家庭用冷凍庫で保存する時の目安と劣化を抑える方法。',answer:'家庭冷凍はできるだけ2〜3週間以内に食べると品質を保ちやすい。脂の多い魚ほど酸化しやすい。水分を拭き、空気を抜いて密封して冷凍する。',category:'魚の扱い',sections:[{heading:'鮮度が良いうちに冷凍',body:'数日冷蔵してから冷凍するより、食べない分は早めに凍らせる。'},{heading:'空気を遮断',body:'ラップ＋保存袋や真空包装で乾燥と酸化を抑える。'},{heading:'小分け',body:'一食分ずつ分けると解凍・再冷凍を避けられる。'},{heading:'解凍',body:'冷蔵庫でゆっくり解凍するとドリップを抑えやすい。'}],related:[{label:'魚の持ち帰り方',href:'/guide/fish-carry-home'},{label:'魚図鑑',href:'/fish'}]},
 {slug:'night-fishing-light',title:'夜釣りのライトは何ルーメン必要？ヘッドライトの選び方',query:'夜釣り ヘッドライト 何ルーメン',summary:'夜の堤防で使うヘッドライトの明るさと機能を解説。',answer:'手元作業なら100〜200lmでも足りるが、移動や安全確認を考えると300lm前後以上が扱いやすい。明るさより、赤色灯・防水・長時間駆動も重要。',category:'釣行準備',sections:[{heading:'手元',body:'仕掛け交換や餌付けは強すぎる光でなくても十分。'},{heading:'移動',body:'足場確認には広角で明るいモードが便利。'},{heading:'赤色灯',body:'周囲へ眩しさを与えにくく、夜目を保ちやすい。'},{heading:'予備電源',body:'長時間の夜釣りでは予備電池かモバイルバッテリーを用意。'}],related:[{label:'堤防タチウオテンヤ',href:'/methods/tachiuo-tenya-shore'},{label:'メバリング',href:'/methods/mebaring'}]},
 {slug:'life-jacket-type',title:'釣りのライフジャケットは腰巻き？肩掛け？',query:'釣り ライフジャケット 腰巻き 肩掛け',summary:'膨張式と固定式、腰巻きと肩掛けの違いを初心者向けに比較。',answer:'船は船宿・法令に適合する認証品を選ぶ。堤防でも肩掛け式は浮力姿勢が安定しやすい。腰巻きは動きやすいが、使用条件と装着方法を理解して使う。',category:'釣行準備',sections:[{heading:'肩掛け膨張式',body:'装着状態が分かりやすく、船釣りで使われることが多い。'},{heading:'腰巻き式',body:'上半身が自由で暑い時期も快適。ただし正しい位置で装着する必要がある。'},{heading:'固定式',body:'落水時に膨張機構へ依存せず、磯や子ども向けで選ばれることが多い。'},{heading:'船は規格確認',body:'遊漁船では桜マーク等、求められる基準があるため船宿へ確認する。'}],related:[{label:'初心者の道具',href:'/guide/beginner-sea-fishing-setup'},{label:'釣りスポット',href:'/spots'}]},
 {slug:'boat-fishing-seasick',title:'船釣りの酔い対策は？前日からできること',query:'船釣り 船酔い 対策',summary:'船酔いを減らすための食事・睡眠・乗船後のコツを整理。',answer:'前日は睡眠を十分に取り、空腹・満腹を避ける。酔い止めは用法を守って早めに服用。船では遠くを見る、下を向き続けない、臭いの強い場所を避ける。',category:'釣行準備',sections:[{heading:'睡眠不足を避ける',body:'寝不足は船酔いを悪化させやすい。早朝便でも前夜の睡眠を優先。'},{heading:'食事',body:'脂っこい食事や食べ過ぎを避け、軽く食べて乗る。'},{heading:'酔い止め',body:'医薬品の表示・用法を守り、運転予定がある場合は眠気にも注意。'},{heading:'船上',body:'水平線を見る、風に当たる、スマホや細かい手元作業を長時間続けない。'}],related:[{label:'船キス',href:'/methods/boat-kisu'},{label:'タイラバ',href:'/methods/tai-rubber'}]},
 {slug:'bait-keep-alive-aji',title:'ノマセ用の活きアジを弱らせない方法は？',query:'ノマセ 活きアジ 弱らせない',summary:'活かしバケツ・海水交換・エアポンプの使い方を整理。',answer:'過密にしない、海水温を上げない、酸素を切らさない。この3点が基本。小型バケツへ大量に入れず、エアポンプと定期的な海水交換で元気を保つ。',category:'釣具・仕掛け',sections:[{heading:'過密を避ける',body:'魚数が多いほど酸欠と水質悪化が早い。容器に余裕を持たせる。'},{heading:'水温',body:'夏の直射日光で海水が温まると急激に弱る。日陰へ置く。'},{heading:'エアポンプ',body:'連続運転できる電池容量と予備電池を準備。'},{heading:'針付け',body:'餌を長持ちさせるには刺す位置と扱いを丁寧に。強く握らない。'}],related:[{label:'ノマセ釣り',href:'/methods/nomase'},{label:'ノマセのアジサイズ',href:'/guide/nomase-bait-size'}]},
 {slug:'snag-release',title:'根掛かりしたらどうする？外し方と切る判断',query:'釣り 根掛かり 外し方',summary:'ルアー・仕掛けが根掛かりした時の安全な外し方。',answer:'まずラインを緩めて角度を変える。次に軽く弾く。それでも外れなければ無理に竿をあおらず、ラインを一直線にして切る。ロッドで強引に引くのは破損の原因。',category:'初心者',sections:[{heading:'すぐ引っ張らない',body:'掛かった直後に強く引くと針が深く刺さる。まずテンションを抜く。'},{heading:'角度を変える',body:'左右へ移動できる場所なら、違う方向から軽く引く。'},{heading:'竿を曲げすぎない',body:'根掛かり外しでロッドを満月状に曲げると折損しやすい。'},{heading:'最後は切る',body:'ラインブレーカー等を使い、竿やリールへ無理な負荷を掛けず切る。'}],related:[{label:'穴釣り',href:'/methods/ana'},{label:'ちょい投げ',href:'/methods/choinage'}]},
 {slug:'fishing-line-twist',title:'釣り糸がヨレる原因は？スピニングリールの糸ヨレ対策',query:'釣り糸 ヨレ 原因 スピニング',summary:'糸ヨレ・ライントラブルの原因と予防方法を解説。',answer:'ドラグが出ている時にハンドルを巻く、ルアーや仕掛けが回転する、巻き取り方向が合っていないのが主因。ヨレたラインは一度伸ばして戻す。',category:'釣具・仕掛け',sections:[{heading:'ドラグ中に巻かない',body:'魚がラインを出している最中にハンドルを回すとヨレが増える。'},{heading:'仕掛けの回転',body:'餌やルアーが曲がると水中で回転し、ラインへヨレが伝わる。'},{heading:'巻き替え',body:'新品ラインをスプールへ移す時も向きを確認する。'},{heading:'定期的に解消',body:'仕掛けを外し、ラインだけを水中で引いてヨレを抜く方法もある。'}],related:[{label:'海釣りのリール番手',href:'/guide/spinning-reel-size'},{label:'釣具を見る',href:'/gear'}]}
];
