import type {GuideArticle} from '@/lib/guide-articles';

export const extraGuideArticles7:GuideArticle[]=[
 {slug:'tairaba-pe-06-08-1',title:'タイラバPEは0.6・0.8・1号どれ？強度と底取りで比較',query:'タイラバ PE 0.6 0.8 1号 違い',summary:'タイラバで迷いやすいPE0.6・0.8・1号を水深・潮・強度から比較。',answer:'迷ったらPE0.8号が最も無難。浅場と感度重視なら0.6号、強度と安心感を優先するなら1号。船宿指定がある場合はそれを最優先。',category:'釣具・仕掛け',sections:[{heading:'0.6号',body:'細く潮受けが少ないため深場でも底を取りやすい一方、傷や高切れへの余裕は小さくなる。'},{heading:'0.8号',body:'感度・強度・扱いやすさのバランスがよく、近海タイラバの基準にしやすい。'},{heading:'1号',body:'大型魚や根ズレへの安心感が増すが、速潮では0.8号より潮を受けやすい。'},{heading:'買う前に',body:'リールの糸巻量と船宿指定、狙う水深を確認して200m以上を基準に選ぶ。'}],related:[{label:'タイラバPEの基本',href:'/guide/tairaba-pe'},{label:'タイラバ用リール',href:'/guide/tairaba-reel-beginner'}]},
 {slug:'shore-jigging-pe-15-vs-2',title:'ショアジギングPEは1.5号と2号どっち？青物サイズで選ぶ',query:'ショアジギング PE 1.5 2号 どっち',summary:'ショアジギングで定番のPE1.5号と2号を飛距離・強度から比較。',answer:'40g前後のジグと中型青物中心なら1.5号、根が荒い場所や大型青物まで見るなら2号が安心。ロッドとリールの適合範囲も合わせて判断する。',category:'釣具・仕掛け',sections:[{heading:'1.5号の強み',body:'飛距離と操作性を確保しやすく、4000番クラスとも合わせやすい。'},{heading:'2号の強み',body:'擦れと大型魚への余裕が増す。5000番前後や強めロッドとの相性がよい。'},{heading:'釣り場で変える',body:'足場の高い堤防、テトラ、根の荒い場所では太めが安心。'},{heading:'買う前に',body:'200m前後の巻量を確保し、リーダーとの強度差も極端にしない。'}],related:[{label:'ショアジギングPEの基本',href:'/guide/shore-jigging-pe'},{label:'4000番と5000番',href:'/guide/shore-jigging-reel-size'}]},
 {slug:'eging-pe-06-vs-08',title:'エギングPEは0.6号と0.8号どっち？初心者向け比較',query:'エギング PE 0.6 0.8 どっち',summary:'エギングのPE0.6号と0.8号を飛距離・風・強度から比較。',answer:'秋イカや飛距離重視なら0.6号、初心者や春の大型まで考えるなら0.8号が扱いやすい。迷ったら0.8号が安心。',category:'釣具・仕掛け',sections:[{heading:'0.6号',body:'細くて飛距離が出やすく、風と潮の影響も抑えやすい。'},{heading:'0.8号',body:'強度に余裕があり、根掛かりや大型イカへの安心感が高い。'},{heading:'リーダー',body:'PE号数だけでなくリーダーとのバランスも重要。1.75〜2.5号前後を釣り場に合わせる。'},{heading:'買う前に',body:'150〜200m巻きを基準に、使用リールの浅溝スプール容量を確認する。'}],related:[{label:'エギングリール',href:'/guide/eging-reel-size'},{label:'エギングロッド',href:'/guide/eging-rod-length'}]},
 {slug:'nomase-pe3-vs4',title:'ブリのノマセPEは3号と4号どっち？船釣りの基準',query:'ブリ ノマセ PE 3号 4号 どっち',summary:'船のブリノマセで使うPE3号・4号を強度と潮受けから比較。',answer:'船宿指定がなければPE3号は扱いやすく、4号は大型魚と根ズレへの安心感が高い。最終的には船宿指定とリール容量を優先。',category:'釣具・仕掛け',sections:[{heading:'PE3号',body:'潮受けを抑えながら十分な強度を確保しやすく、近海青物で使いやすい。'},{heading:'PE4号',body:'大型ブリや根の荒いポイントで強度に余裕が出る。'},{heading:'リール容量',body:'太くなるほど同じスプールに巻ける長さが減る。200m以上を確保できるか確認。'},{heading:'買う前に',body:'船宿指定、リーダー号数、ロッドの強さまでセットで合わせる。'}],related:[{label:'ノマセ用リール',href:'/guide/nomase-reel-choice'},{label:'ブリのリーダー',href:'/guide/nomase-leader'}]},
 {slug:'cooler-15-vs-32',title:'釣りクーラー15Lと32Lどっち？持ち運びと魚サイズで比較',query:'釣り クーラー 15L 32L どっち',summary:'15Lと32Lのクーラーを堤防・船・魚サイズ別に比較。',answer:'アジ・キス中心で車から離れるなら15L、船釣り・タチウオ・青物まで使うなら32Lが安心。保冷力よりまず魚が入る内寸と持ち運びを優先する。',category:'釣具・仕掛け',sections:[{heading:'15Lが向く人',body:'小型魚の日帰り、電車釣行、車から歩く釣り場では軽さが大きな利点。'},{heading:'32Lが向く人',body:'船釣り、大型魚、複数人の釣果、氷を多めに使う時に余裕がある。'},{heading:'内寸が重要',body:'同じ容量でも形状で入る魚の長さが違う。長物は横幅を確認する。'},{heading:'買う前に',body:'外寸、自重、キャスター、車載スペースまで確認する。'}],related:[{label:'クーラーサイズの基本',href:'/guide/cooler-size-fishing'},{label:'魚の持ち帰り方',href:'/guide/fish-carry-home'}]},
 {slug:'tairaba-ic-reel-necessary',title:'タイラバにICカウンターは必要？なしでも釣れる？',query:'タイラバ IC カウンター 必要',summary:'タイラバ用リールのICカウンターが必要な人・不要な人を整理。',answer:'必須ではないが、釣れた水深を再現したい初心者や深場ではかなり便利。浅場中心で底から一定巻きだけならカウンターなしでも成立する。',category:'釣具・仕掛け',sections:[{heading:'ICの利点',body:'水深と巻き上げ距離が分かり、釣れたレンジを再現しやすい。'},{heading:'不要な場面',body:'浅場で底から数十回巻くパターンが中心なら、感覚でも十分対応できる。'},{heading:'初心者ほど便利',body:'棚を数字で管理できるため、釣れた人のレンジを真似しやすい。'},{heading:'買う前に',body:'表示機能だけでなくPE容量、自重、ギア比を優先して選ぶ。'}],related:[{label:'タイラバ用リール',href:'/guide/tairaba-reel-beginner'},{label:'タイラバ底取り',href:'/guide/tairaba-bottom-contact'}]},
 {slug:'tachiuo-pg-vs-hg',title:'タチウオテンヤはPGとHGどっち？手巻きリールの選び方',query:'タチウオテンヤ PG HG どっち',summary:'タチウオテンヤのPGとHGを巻き上げ力・手返しで比較。',answer:'40号テンヤを楽に巻きたいならPG、回収速度を重視するならHG。初心者は巻き重りが少ないPG寄りが扱いやすい。',category:'釣具・仕掛け',sections:[{heading:'PG',body:'巻き上げ力があり、重いテンヤと魚を楽に回収しやすい。'},{heading:'HG',body:'仕掛け回収が速く、時合いで手返しを上げやすい。'},{heading:'水深で差が出る',body:'深場ほど回収速度の差が大きくなる一方、負荷も増える。'},{heading:'買う前に',body:'PE容量、ハンドル長、カウンター有無まで確認する。'}],related:[{label:'タチウオ用リール',href:'/guide/tachiuo-tenya-reel-choice'},{label:'テンヤのアクション',href:'/guide/tachiuo-tenya-action'}]},
 {slug:'fishing-reel-2500-vs4000',title:'海釣りリール2500番と4000番どっち？できる釣りを比較',query:'リール 2500 4000 どっち 海釣り',summary:'2500番と4000番で対応できる海釣りを比較。',answer:'エギング・サビキ・小物中心なら2500番、青物や重いルアーまで使うなら4000番。1台で全部を完全に兼用するより用途を分けた方が快適。',category:'釣具・仕掛け',sections:[{heading:'2500番',body:'軽く、エギング・小物釣り・ライトなサビキに向く。'},{heading:'4000番',body:'ライン容量と巻き上げ力に余裕があり、ショアジギングまで対応しやすい。'},{heading:'兼用の限界',body:'4000番は小物釣りでは重く、2500番は大型青物では余裕が少ない。'},{heading:'買う前に',body:'番手より実重量と糸巻量を確認し、使うロッドと合わせる。'}],related:[{label:'リール番手の基本',href:'/guide/spinning-reel-size'},{label:'ショアジギング用リール',href:'/guide/shore-jigging-reel-size'}]},
 {slug:'fluoro-leader-size-guide',title:'フロロリーダーは何号を買う？2〜7号の使い分け',query:'フロロ リーダー 何号 海釣り',summary:'フロロリーダー2〜7号を釣り方別に整理。',answer:'ライトゲームは2〜3号、エギングは2号前後、タイラバは2〜4号、青物は5〜7号以上が基準。対象魚だけでなく根ズレとメインPE号数で決める。',category:'釣具・仕掛け',sections:[{heading:'2〜3号',body:'アジ・エギング・タイラバなど細めラインの釣りで使いやすい。'},{heading:'4〜5号',body:'強めのルアー釣りや中型青物で安心感を増やしたい時に。'},{heading:'6〜7号',body:'ショアジギングや船青物など擦れと強度を重視する場面で使う。'},{heading:'買う前に',body:'太ければよいわけではない。ノットの通り、ルアー動作、PEとのバランスを見る。'}],related:[{label:'フロロとナイロン',href:'/guide/leader-fluoro-vs-nylon'},{label:'リーダーの長さ',href:'/guide/leader-length-general'}]},
 {slug:'pe-line-size-guide',title:'PEラインは何号を買う？0.6〜3号を釣り方別に整理',query:'PEライン 何号 海釣り',summary:'PE0.6〜3号をエギング・タイラバ・ショアジギング・船青物別に整理。',answer:'0.6〜0.8号はエギング・タイラバ、1〜1.5号は強めのルアー釣り、2号はショア青物、3号は船青物が一つの目安。最終的にはロッド・リール・船宿指定に合わせる。',category:'釣具・仕掛け',sections:[{heading:'0.6〜0.8号',body:'エギングやタイラバで潮受けを抑えたい時に使いやすい。'},{heading:'1〜1.5号',body:'ライトショアジギングややや強めの海ルアーで汎用性が高い。'},{heading:'2〜3号',body:'青物や船ノマセなど強度を優先する釣り向け。'},{heading:'買う前に',body:'必要な長さ、編み数、リールの糸巻量まで確認する。'}],related:[{label:'PEは何m必要？',href:'/guide/pe-line-how-much'},{label:'4本編みと8本編み',href:'/guide/pe-line-4-vs-8-strand'}]}
];
