import type {GuideArticle} from './guide-articles';
export const quickGuides:GuideArticle[]=[
 {slug:'sabiki-rig-too-long',title:'サビキ仕掛けが竿より長いとき、そのまま使っていい？',query:'サビキ 仕掛け 長すぎる',category:'サビキ',editorial:{articleType:'QUICK GUIDE',topic:'tackle',gearTags:['rig','rod'],parentGuide:'aji-sabiki-depth'},summary:'魚を手元へ寄せられない仕掛けは、短い完成仕掛けへ交換。針数より扱える長さを優先します。',answer:'竿を立ててもカゴが手元へ届かず、魚を外すために後ろへ下がる必要があるなら長すぎます。最初は短い完成サビキを選び、針数を増やすより安全に投入・回収できる組み合わせにします。',sections:[
 {heading:'なぜ長いと扱いにくい？',body:'仕掛け上端の金具は竿先のガイドへ巻き込めません。仕掛けが長いほど、竿先からカゴまでの距離が残ります。針が足元や服に触れる状態で持ち替えないでください。'},
 {heading:'その場で確認する順番',body:'周囲に人がいない安全な場所で、針を保護した状態で長さを確認します。',steps:[{title:'まず全長を見る',body:'パッケージの全長を確認。針の号数と仕掛け全長は別の情報です。'},{title:'手元に寄せられる組み合わせにする',body:'短い竿にはショート仕掛けを選びます。堤防の縁から離れて取り込めるか、同行者にも確認してもらいます。'},{title:'無理な加工より完成品を使う',body:'途中で切ると端の結束を作り直す必要があります。結びに慣れていない場合は、短い完成仕掛けに替える方が確実です。'}]},
 {heading:'針が少ないと釣れない？',body:'針数だけで釣果は決まりません。群れのいる棚に仕掛けを入れ、絡まずに回収することを優先。船では針数・全長・カゴの指定があるため、船宿指定を優先します。'}],related:[{label:'アジ図鑑',href:'/fish/aji'},{label:'サビキの仕掛け図',href:'/methods/sabiki'},{label:'釣り場を探す',href:'/spots?q=%E3%82%A2%E3%82%B8'}],sources:[{label:'DAIWA：サビキ仕掛けで釣る',url:'https://www.daiwa.com/jp/beginner/place/sabiki'}],verifiedAt:'2026-09-16'},
 {slug:'leader-knot-catching-guide',title:'PEとリーダーの結び目がガイドに引っかかる。巻き続けていい？',query:'リーダー 結び目 ガイド 引っかかる',category:'ライン',editorial:{articleType:'QUICK GUIDE',topic:'tackle',gearTags:['line'],parentGuide:'leader-drag-first-check'},summary:'引っかかりを力で通さず、端糸・結束・ガイドを順に点検。結び直しと長さ調整を使い分けます。',answer:'強く巻いて無理に通すのはやめます。針やルアーを安全に固定してから、端糸の突出、結束のほつれ、ガイドの傷を確認。傷んだ結び目は作り直し、結束方式は使う糸とガイド径に合わせます。',sections:[
 {heading:'どこで止まるかを分ける',body:'結び目がガイドに当たるのか、スプール上の糸へ食い込むのかで点検箇所が異なります。キャスト中に異音が出た場合も、まず回収して傷を見ます。',table:{caption:'症状と先に見る場所',headers:['症状','点検すること'],rows:[['結び目だけが止まる','端糸の向き・余分なこぶ・結束径'],['結び目以外でもざらつく','糸とガイドの傷。疑わしいガイドは販売店へ相談'],['スプールから糸が急に止まる','糸の食い込みや重なり。結び目だけの問題と決めつけない']]}},
 {heading:'細くするために結びを省略しない',body:'編み込み回数や仕上げを自己流で減らすと、抜ける原因になります。メーカーが示す手順で結び直し、手に糸を巻かず安全に強度を確認。端糸は結び方で必要量が違うため、根元まで一律に切らないでください。'},
 {heading:'リーダーを短くすれば解決？',body:'投げる釣りでは結び目をガイド外へ出せる長さが選択肢になりますが、根ズレ対策に必要な長さまで削らないこと。太いリーダーを使う船釣りでは、竿や結束との適合を船宿・販売店へ確認します。'}],related:[{label:'FGとPRの使い分け',href:'/guide/fg-knot-vs-pr-knot'},{label:'タイラバの基本',href:'/guide/tairaba-bottom-contact'},{label:'タイラバの仕掛け',href:'/methods/tai-rubber'},{label:'釣り場MAP',href:'/spots'}],sources:[{label:'Seaguar：各種ノットの結び方',url:'https://www.seaguar.ne.jp/knot/index.html'}],verifiedAt:'2026-09-16'},
 {slug:'eging-crosswind-line',title:'横風でエギの着底が分からない。重いエギに替える前に何をする？',query:'エギング 横風 着底 分からない',category:'エギング',editorial:{articleType:'QUICK GUIDE',topic:'fishing',gearTags:['lure','line'],parentGuide:'eging-shakuri-count'},summary:'風で膨らむラインを減らし、短い距離で沈下を確認。重さを増やす前に安全と糸の状態を見直します。',answer:'まず風で膨らんだ余分な糸を少しずつ回収し、竿先を低くして風を受ける糸を減らします。それでも分からなければ飛距離を抑えて確認。足元が不安定になる風や波なら、エギを替えて続けず撤退します。',sections:[
 {heading:'風がエギを引いていることがある',body:'横風でラインが弓なりになると、その張りがエギを引き、沈下やアタリを読みづらくします。糸を強く巻き続けると自分でもエギを引いてしまうため、余分なたるみだけを取ります。'},
 {heading:'変える順番は一つずつ',body:'安全に立てる位置から、まず短い距離で沈下の変化を観察します。',points:['竿先を低くして、空中のラインを減らす。','投げる距離を短くし、ラインを見失わない。','それでも沈下を把握できなければ、竿の適合内で沈下速度の速いエギを検討。'],diagram:{kind:'drift',labels:['横風で糸が膨らむ','余分な糸を少し回収','短い距離で沈下を確認']}},
 {heading:'着底を決めつけない',body:'風が弱まっただけでもラインはたるみます。一度たるんだから底と決めず、同じ投点で変化を見比べます。秒数だけを水深へ換算せず、分からないまま放置して根掛かりさせないことを優先します。'}],related:[{label:'アオリイカ図鑑',href:'/fish/aoriika'},{label:'エギングの仕掛け',href:'/methods/eging'},{label:'釣り場を探す',href:'/spots?q=%E3%82%A2%E3%82%AA%E3%83%AA%E3%82%A4%E3%82%AB'}],sources:[{label:'YAMASHITA：横風が強い時の対処法',url:'https://www.yamaria.com/movies/20'}],verifiedAt:'2026-09-16'}
];
