import type {GuideArticle} from '@/lib/guide-articles';

export const extraGuideArticles4:GuideArticle[]=[
 {slug:'tokyobay-march-fish',title:'東京湾で3月に釣れる魚は？',query:'東京湾 3月 釣れる魚',summary:'3月の東京湾で狙いやすいメバル・シーバス・クロダイを整理。',answer:'3月はメバル・シーバス・クロダイが中心。水温はまだ低く、朝夕より夜のライトゲームや港湾部のストラクチャー狙いが組みやすい。',category:'季節・釣り場',sections:[{heading:'メバル',body:'夜の常夜灯や壁際をスローに探る。'},{heading:'シーバス',body:'河口や運河でベイトの有無を確認。'},{heading:'クロダイ',body:'水温上昇に合わせて動きが出る。'},{heading:'寒暖差に注意',body:'暖かい日が続いた後でも冷え込みで活性が落ちることがある。'}],related:[{label:'メバリング',href:'/methods/mebaring'},{label:'魚図鑑',href:'/fish'}]},
 {slug:'tokyobay-april-fish',title:'東京湾で4月に釣れる魚は？',query:'東京湾 4月 釣れる魚',summary:'4月の東京湾で狙いたい魚を岸・船で整理。',answer:'4月はクロダイ・シーバス・メバルが狙いやすく、後半はアジやシロギスの気配も増える。春らしく魚種が広がり始める時期。',category:'季節・釣り場',sections:[{heading:'クロダイ',body:'乗っ込みを意識した魚が動く時期。'},{heading:'シーバス',body:'ベイトが入る河口や港湾部が有力。'},{heading:'メバル',body:'夜のライトゲームはまだ好機。'},{heading:'船釣り',body:'アジ・シロギスなど初心者向け魚種も増える。'}],related:[{label:'メバリング',href:'/methods/mebaring'},{label:'ちょい投げ',href:'/methods/choinage'}]},
 {slug:'tokyobay-may-fish',title:'東京湾で5月に釣れる魚は？',query:'東京湾 5月 釣れる魚',summary:'5月の東京湾で狙いやすいアジ・シロギス・クロダイを紹介。',answer:'5月はアジ・シロギス・クロダイが狙いやすい。サビキ、ちょい投げ、落とし込みと初心者向けの選択肢が増える。',category:'季節・釣り場',sections:[{heading:'アジ',body:'朝夕の回遊をサビキで狙いやすい。'},{heading:'シロギス',body:'砂地でちょい投げの好機。'},{heading:'クロダイ',body:'護岸際や河口で有力。'},{heading:'ファミリー向け',body:'気候が安定しやすく、日中の短時間釣行にも向く。'}],related:[{label:'サビキ釣り',href:'/methods/sabiki'},{label:'ちょい投げ',href:'/methods/choinage'}]},
 {slug:'tokyobay-june-fish',title:'東京湾で6月に釣れる魚は？',query:'東京湾 6月 釣れる魚',summary:'梅雨時の東京湾で狙いやすい魚を紹介。',answer:'6月はアジ・シロギス・クロダイが有力。雨後は河口の濁りが強くなるため、港内や潮通しの良い場所を選ぶ。',category:'季節・釣り場',sections:[{heading:'アジ',body:'サビキ・アジングともに狙いやすくなる。'},{heading:'シロギス',body:'水温上昇で浅場へ入る個体が増える。'},{heading:'クロダイ',body:'濁りが入ると警戒心が下がることも。'},{heading:'梅雨対策',body:'滑りやすい足場と急な雷雨に注意。'}],related:[{label:'アジング',href:'/methods/ajing'},{label:'ちょい投げ',href:'/methods/choinage'}]},
 {slug:'tokyobay-july-fish',title:'東京湾で7月に釣れる魚は？',query:'東京湾 7月 釣れる魚',summary:'真夏前半の東京湾で狙いやすい魚を整理。',answer:'7月はアジ・サバ・シロギスが安定しやすく、船ではタチウオも人気。岸は朝夕、船は日中でも狙い目がある。',category:'季節・釣り場',sections:[{heading:'アジ・サバ',body:'朝夕のサビキで狙いやすい。'},{heading:'シロギス',body:'砂地を広く探る。'},{heading:'タチウオ',body:'船釣りで人気が高まる時期。'},{heading:'熱中症対策',body:'日中は休憩と水分を多めに取る。'}],related:[{label:'タチウオテンヤ',href:'/methods/tachiuo-tenya'},{label:'サビキ釣り',href:'/methods/sabiki'}]},
 {slug:'tokyobay-august-fish',title:'東京湾で8月に釣れる魚は？',query:'東京湾 8月 釣れる魚',summary:'8月の東京湾で人気のアジ・タチウオ・シロギスを紹介。',answer:'8月はアジ・タチウオ・シロギスが有力。暑さが厳しいため、岸は朝夕中心、船は飲料と日除けを十分に準備。',category:'季節・釣り場',sections:[{heading:'アジ',body:'朝夕の港湾部で回遊待ち。'},{heading:'タチウオ',body:'船では代表的な夏ターゲット。'},{heading:'シロギス',body:'浅場〜中距離をちょい投げで探る。'},{heading:'夕立に注意',body:'雷の予報がある日は早めに撤収する。'}],related:[{label:'アジ図鑑',href:'/fish/aji'},{label:'タチウオ図鑑',href:'/fish/tachiuo'}]},
 {slug:'tokyobay-september-fish',title:'東京湾で9月に釣れる魚は？',query:'東京湾 9月 釣れる魚',summary:'初秋の東京湾で狙いやすい魚を紹介。',answer:'9月はアジ・サバ・タチウオ・シーバスが有力。秋の回遊魚シーズンへ入り、岸も船も選択肢が増える。',category:'季節・釣り場',sections:[{heading:'アジ・サバ',body:'港でのサビキが引き続き有力。'},{heading:'タチウオ',body:'船を中心に人気。'},{heading:'シーバス',body:'河口や運河でベイトを追う。'},{heading:'台風後',body:'濁りや漂流物に注意。'}],related:[{label:'サビキ釣り',href:'/methods/sabiki'},{label:'ウキ釣り',href:'/methods/uki'}]},
 {slug:'tokyobay-october-fish',title:'東京湾で10月に釣れる魚は？',query:'東京湾 10月 釣れる魚',summary:'10月の東京湾で狙いたい魚をまとめて紹介。',answer:'10月はアジ・シーバス・タチウオ・青物が狙い目。秋の最盛期で、ベイトの入り方次第では岸から回遊魚も期待できる。',category:'季節・釣り場',sections:[{heading:'アジ',body:'良型が混じりやすくなる。'},{heading:'シーバス',body:'河口・運河で秋のハイシーズン。'},{heading:'青物',body:'ベイト次第でイナダやサワラが入る。'},{heading:'タチウオ',body:'船では引き続き人気。'}],related:[{label:'ショアジギング',href:'/methods/shore-jigging'},{label:'アジング',href:'/methods/ajing'}]},
 {slug:'tokyobay-november-fish',title:'東京湾で11月に釣れる魚は？',query:'東京湾 11月 釣れる魚',summary:'晩秋の東京湾で狙いやすい魚を整理。',answer:'11月はシーバス・アジ・タチウオが有力。水温低下で日ごとの差が大きくなるため、直近の釣果を優先して魚種を決める。',category:'季節・釣り場',sections:[{heading:'シーバス',body:'ベイトが残る河口はまだ有力。'},{heading:'アジ',body:'良型が期待できる一方、群れの移動も早い。'},{heading:'タチウオ',body:'船で狙いやすい時期が続く。'},{heading:'防寒準備',body:'朝夕は冷え込むため手袋と防風着を用意。'}],related:[{label:'アジング',href:'/methods/ajing'},{label:'タチウオテンヤ',href:'/methods/tachiuo-tenya'}]},
 {slug:'tokyobay-december-fish',title:'東京湾で12月に釣れる魚は？',query:'東京湾 12月 釣れる魚',summary:'冬入りした東京湾で狙いやすい魚を紹介。',answer:'12月はメバル・カサゴ・シーバスが岸の中心。船ではアジなど深場の魚が有力。回遊魚が減るほど根魚と船釣りが安定。',category:'季節・釣り場',sections:[{heading:'メバル',body:'夜の港湾部で狙いやすい。'},{heading:'カサゴ',body:'足元の障害物周りを丁寧に探る。'},{heading:'シーバス',body:'ベイトが残る河口が候補。'},{heading:'船アジ',body:'岸が厳しい時期の選択肢。'}],related:[{label:'メバリング',href:'/methods/mebaring'},{label:'穴釣り',href:'/methods/ana'}]},
 {slug:'tokyobay-january-fish',title:'東京湾で1月に釣れる魚は？',query:'東京湾 1月 釣れる魚',summary:'真冬の東京湾で狙える魚を整理。',answer:'1月はメバル・カサゴ・シーバスが岸の本命。船ならアジなどが候補。短時間で狙いを絞る冬型の釣りが向く。',category:'季節・釣り場',sections:[{heading:'メバル',body:'夜の常夜灯や壁際で有力。'},{heading:'カサゴ',body:'胴突き・穴釣りで狙いやすい。'},{heading:'シーバス',body:'温排水や河口などベイトが残る場所を探す。'},{heading:'短時間勝負',body:'寒さを避け、潮の動く時間を絞る。'}],related:[{label:'メバリング',href:'/methods/mebaring'},{label:'カサゴ図鑑',href:'/fish/kasago'}]},
 {slug:'tokyobay-february-fish',title:'東京湾で2月に釣れる魚は？',query:'東京湾 2月 釣れる魚',summary:'厳寒期の東京湾で狙いやすい魚を紹介。',answer:'2月はメバル・カサゴが安定しやすく、シーバスはベイト次第。岸が厳しい日は船アジも選択肢。',category:'季節・釣り場',sections:[{heading:'メバル',body:'小型ワームでスローに探る。'},{heading:'カサゴ',body:'底を外さず足元を探る。'},{heading:'シーバス',body:'河口や温排水などを優先。'},{heading:'春待ちの時期',body:'月末は水温の上向きで魚の動きが変わることもある。'}],related:[{label:'メバリング',href:'/methods/mebaring'},{label:'穴釣り',href:'/methods/ana'}]},
 {slug:'kanagawa-pier-beginner',title:'神奈川の堤防釣り、初心者は何を狙う？',query:'神奈川 堤防 釣り 初心者',summary:'神奈川県沿岸で初心者が始めやすい魚と釣り方を整理。',answer:'春〜秋はサビキのアジ・サバ、砂地ではシロギス、冬はメバル・カサゴが始めやすい。まず釣り可能な公園・施設から選ぶ。',category:'季節・釣り場',sections:[{heading:'サビキ',body:'魚が回れば釣果を得やすい。'},{heading:'ちょい投げ',body:'砂地がある場所でシロギス狙い。'},{heading:'冬の根魚',body:'足元を短時間で探れる。'},{heading:'釣り禁止確認',body:'都市部は立入禁止・釣り禁止区画も多い。'}],related:[{label:'初心者の道具',href:'/guide/beginner-sea-fishing-setup'},{label:'サビキ釣り',href:'/methods/sabiki'}]},
 {slug:'chiba-pier-beginner',title:'千葉の堤防釣り、初心者は何を狙う？',query:'千葉 堤防 釣り 初心者',summary:'千葉の港・堤防で初心者向けの魚種を紹介。',answer:'千葉ではアジ・サバのサビキ、シロギスのちょい投げ、秋のアオリイカが人気。外房・内房で海況が大きく違うため、風向きでエリアを選ぶ。',category:'季節・釣り場',sections:[{heading:'内房',body:'比較的穏やかな港湾部が多く、サビキ向き。'},{heading:'外房',body:'外洋に面し、波やうねりへ注意。'},{heading:'秋アオリ',body:'港や藻場でエギングが人気。'},{heading:'初心者は施設優先',body:'足場・駐車・トイレのある場所を選ぶ。'}],related:[{label:'サビキ釣り',href:'/methods/sabiki'},{label:'エギング',href:'/methods/eging'}]},
 {slug:'aichi-bay-autumn-fish',title:'愛知・知多半島で秋に釣れる魚は？',query:'知多半島 秋 釣れる魚',summary:'知多半島周辺の秋に狙いやすい魚を整理。',answer:'秋の知多半島はアジ・ハゼ・青物・アオリイカが候補。港・河口・潮通しの良い堤防を魚種で使い分ける。',category:'季節・釣り場',sections:[{heading:'アジ',body:'港のサビキやアジングが定番。'},{heading:'ハゼ',body:'河口や汽水域で狙いやすい。'},{heading:'青物',body:'回遊があればメタルジグ。'},{heading:'アオリイカ',body:'秋の小型をエギングで狙える。'}],related:[{label:'アジング',href:'/methods/ajing'},{label:'エギング',href:'/methods/eging'}]},
 {slug:'miura-autumn-fish',title:'三浦半島で秋に釣れる魚は？',query:'三浦半島 秋 釣れる魚',summary:'三浦半島で秋に人気の青物・アオリイカ・根魚を紹介。',answer:'秋の三浦半島は青物・アオリイカ・根魚が有力。潮通しの良い場所は青物、港や藻場はエギング、岩礁帯は根魚。',category:'季節・釣り場',sections:[{heading:'青物',body:'朝まずめの回遊狙い。'},{heading:'アオリイカ',body:'2.5〜3号エギで秋の新子を狙う。'},{heading:'根魚',body:'岩礁周りをワームや胴突きで探る。'},{heading:'磯の安全',body:'波と風が強い日は入らない。'}],related:[{label:'ショアジギング',href:'/methods/shore-jigging'},{label:'エギング',href:'/methods/eging'}]},
 {slug:'awaji-autumn-fish',title:'淡路島で秋に釣れる魚は？',query:'淡路島 秋 釣れる魚',summary:'淡路島で秋に狙いやすいアジ・青物・アオリイカを整理。',answer:'秋の淡路島はアジ・青物・アオリイカが人気。港ではサビキ、潮通しの良い場所でショアジギング、藻場・港周りでエギングが組みやすい。',category:'季節・釣り場',sections:[{heading:'アジ',body:'朝夕のサビキと夜のアジング。'},{heading:'青物',body:'ベイトが接岸すればチャンス。'},{heading:'アオリイカ',body:'秋は数釣りしやすい。'},{heading:'潮流を見る',body:'明石海峡周辺など速い場所は無理に軽い仕掛けを使わない。'}],related:[{label:'ショアジギング',href:'/methods/shore-jigging'},{label:'エギング',href:'/methods/eging'}]},
 {slug:'wakayama-autumn-fish',title:'和歌山で秋に釣れる魚は？',query:'和歌山 秋 釣れる魚',summary:'和歌山沿岸の秋に人気のアジ・青物・タチウオ・アオリイカを紹介。',answer:'秋の和歌山はアジ・青物・タチウオ・アオリイカと魚種豊富。朝は青物、日中はアオリ、夕方からタチウオのように一日で組み立てやすい。',category:'季節・釣り場',sections:[{heading:'アジ',body:'港内のサビキ・アジングが有力。'},{heading:'青物',body:'朝まずめにメタルジグ。'},{heading:'タチウオ',body:'夕まずめ〜夜の堤防が人気。'},{heading:'アオリイカ',body:'秋は小型中心でエギング向き。'}],related:[{label:'タチウオテンヤ（堤防）',href:'/methods/tachiuo-tenya-shore'},{label:'エギング',href:'/methods/eging'}]},
 {slug:'fukuoka-beginner-fish',title:'福岡で初心者が狙いやすい魚は？',query:'福岡 海釣り 初心者',summary:'福岡沿岸で初心者が始めやすい魚と釣り方を紹介。',answer:'春〜秋はアジ・サバのサビキ、砂地ではキス、秋はサゴシなど回遊魚も候補。まず港内の安全な場所でサビキから始めると分かりやすい。',category:'季節・釣り場',sections:[{heading:'サビキ',body:'アジ・サバの回遊時は初心者向き。'},{heading:'キス',body:'砂地でちょい投げ。'},{heading:'回遊魚',body:'秋はサゴシなどが入ることも。'},{heading:'風向きで場所選び',body:'玄界灘側は風で荒れやすい。'}],related:[{label:'サビキ釣り',href:'/methods/sabiki'},{label:'ちょい投げ',href:'/methods/choinage'}]},
 {slug:'sendai-bay-autumn-fish',title:'仙台湾で秋に釣れる魚は？',query:'仙台湾 秋 釣れる魚',summary:'仙台湾周辺の秋に狙いやすい魚を整理。',answer:'秋の仙台湾はアジ・サバ・ヒラメ・青物が候補。港はサビキ、砂浜はヒラメ、回遊があれば青物狙い。水温低下は西日本より早め。',category:'季節・釣り場',sections:[{heading:'アジ・サバ',body:'港湾部でサビキが有力。'},{heading:'ヒラメ',body:'サーフで秋の人気魚。'},{heading:'青物',body:'ベイトが入れば回遊を狙える。'},{heading:'季節進行が早い',body:'冷え込みで魚種が変わるため直近釣果を確認。'}],related:[{label:'サーフルアー',href:'/methods/surf-lure'},{label:'サビキ釣り',href:'/methods/sabiki'}]}
];
