import type {GuideArticle} from '@/lib/guide-articles';

export const extraGuideArticles3:GuideArticle[]=[
 {slug:'tokyobay-spring-fish',title:'東京湾で春に釣れる魚は？3〜5月の狙い目',query:'東京湾 春 釣れる魚',summary:'東京湾の春に狙いやすい魚を、岸釣りと船に分けて整理。',answer:'春の東京湾はメバル・シーバス・クロダイが狙いやすく、季節が進むとアジやシロギスも上向く。岸釣りは港湾部、船はアジ・シロギス・マダイ系が候補。',category:'季節・釣り場',sections:[{heading:'3月は根魚とシーバス',body:'水温がまだ低い時期はメバルなどの根魚とシーバスが中心。夜の常夜灯、護岸際、潮の当たる場所を丁寧に探る。'},{heading:'4〜5月は魚種が増える',body:'水温上昇とともにアジ、シロギス、クロダイの選択肢が増える。日中のちょい投げやサビキも成立しやすくなる。'},{heading:'船は湾内の安定感',body:'湾内の船釣りではアジやシロギスなど初心者向け魚種も豊富。船宿ごとの旬魚種を確認する。'},{heading:'春は風に注意',body:'南風が強まる日もあるため、風向きと釣り場の向きを確認。'}],related:[{label:'アジ図鑑',href:'/fish/aji'},{label:'メバリング',href:'/methods/mebaring'}]},
 {slug:'tokyobay-summer-fish',title:'東京湾で夏に釣れる魚は？6〜8月のおすすめ',query:'東京湾 夏 釣れる魚',summary:'夏の東京湾で狙いやすいアジ・シロギス・タチウオなどを整理。',answer:'夏の東京湾はアジ・シロギス・クロダイが安定しやすく、船ではタチウオも人気。岸では朝夕のサビキ、日中のちょい投げ、夜のライトゲームが組みやすい。',category:'季節・釣り場',sections:[{heading:'岸はアジとシロギス',body:'朝夕はアジの回遊、日中は砂地でシロギス。ファミリーフィッシングと相性が良い季節。'},{heading:'クロダイも夏の本命',body:'護岸や河口部ではクロダイが活発。フカセ、落とし込み、ルアーなど選択肢が多い。'},{heading:'船タチウオ',body:'夏〜秋は東京湾タチウオの代表シーズン。テンヤや天秤など船宿指定の釣法を確認する。'},{heading:'暑さ対策',body:'昼の堤防は高温になる。飲料、帽子、日除け、氷を多めに用意。'}],related:[{label:'サビキ釣り',href:'/methods/sabiki'},{label:'タチウオ図鑑',href:'/fish/tachiuo'}]},
 {slug:'tokyobay-autumn-fish',title:'東京湾で秋に釣れる魚は？9〜11月は何を狙う？',query:'東京湾 秋 釣れる魚',summary:'東京湾の秋に強い回遊魚・アジ・タチウオ・シーバスを整理。',answer:'秋の東京湾は一年でも魚種が多い時期。アジ・サバ・タチウオ・シーバスが有力で、場所によって青物回遊も期待できる。まず直近のベイト情報を確認。',category:'季節・釣り場',sections:[{heading:'アジ・サバが狙いやすい',body:'沿岸へベイトが寄る時期。朝夕のサビキやアジングで数釣りを狙いやすい。'},{heading:'タチウオ',body:'船を中心に人気が高く、岸へ寄る年・場所もある。夜釣りでは歯対策を徹底。'},{heading:'シーバス',body:'河口や運河ではベイトを追うシーバスが有力。潮位変化と流れが出る時間を意識する。'},{heading:'青物は回遊次第',body:'イナダやサワラなどが入ることもあるが、日による差が大きい。'}],related:[{label:'ショアジギング',href:'/methods/shore-jigging'},{label:'アジング',href:'/methods/ajing'}]},
 {slug:'tokyobay-winter-fish',title:'東京湾で冬に釣れる魚は？12〜2月の狙い目',query:'東京湾 冬 釣れる魚',summary:'冬の東京湾で狙いやすい根魚・シーバス・船アジを紹介。',answer:'冬の東京湾はメバル・カサゴ・シーバスが岸の本命。船ではアジなどが安定する日も多い。寒期は回遊魚より、居着く魚や深場を狙うと組み立てやすい。',category:'季節・釣り場',sections:[{heading:'メバル・カサゴ',body:'夜の港湾部、護岸際、ストラクチャー周りが狙い目。軽量ルアーや胴突きが使いやすい。'},{heading:'冬シーバス',body:'河口や温排水周辺など、ベイトが集まる場所を探す。'},{heading:'船アジ',body:'岸から厳しい時期でも船で深場を狙えばアジが期待できる。'},{heading:'防寒と安全',body:'北風で体感温度が下がる。防寒・滑りにくい靴・ライフジャケットを準備。'}],related:[{label:'メバリング',href:'/methods/mebaring'},{label:'カサゴ図鑑',href:'/fish/kasago'}]},
 {slug:'yokohama-beginner-fish',title:'横浜周辺で初心者が狙いやすい魚は？',query:'横浜 釣り 初心者 魚',summary:'横浜の海釣りで初心者が狙いやすい魚と釣り方を整理。',answer:'横浜周辺ならアジ・サバのサビキ、シロギスのちょい投げ、メバル・カサゴの根魚狙いが始めやすい。季節ごとに魚種を替えるのがコツ。',category:'季節・釣り場',sections:[{heading:'春〜秋はサビキ',body:'アジやサバの回遊がある時期は最も手軽。針サイズを魚に合わせる。'},{heading:'砂地ではシロギス',body:'投げられる場所ではちょい投げが有力。5〜10号前後の軽いオモリで探れる。'},{heading:'冬は根魚',body:'足元のストラクチャー周りでメバル・カサゴを狙う。'},{heading:'施設ルールを確認',body:'横浜周辺は釣り禁止・立入禁止エリアも多い。必ず現地ルールを確認。'}],related:[{label:'初心者の道具',href:'/guide/beginner-sea-fishing-setup'},{label:'サビキ釣り',href:'/methods/sabiki'}]},
 {slug:'chiba-uchibo-autumn-fish',title:'千葉・内房で秋に釣れる魚は？',query:'内房 秋 釣れる魚',summary:'内房の秋に狙いやすいアジ・青物・アオリイカなどを整理。',answer:'秋の内房はアジ・サバ・青物・アオリイカが候補。港内はサビキとアジング、潮通しの良い場所はショアジギング、岩礁や藻場はエギングが狙い目。',category:'季節・釣り場',sections:[{heading:'港はアジ',body:'朝夕のサビキや夜のアジングが定番。小型中心なら針とジグヘッドを軽くする。'},{heading:'青物回遊',body:'ベイトが入ればイナダやサワラなどが回遊。遠投だけでなく手前のベイトも確認する。'},{heading:'秋アオリ',body:'小型が多く2.5〜3号エギでテンポよく探りやすい。'},{heading:'風向きを見る',body:'東京湾側は風向きで釣りやすさが大きく変わる。'}],related:[{label:'エギング',href:'/methods/eging'},{label:'ショアジギング',href:'/methods/shore-jigging'}]},
 {slug:'chiba-sotobo-autumn-fish',title:'千葉・外房で秋に釣れる魚は？',query:'外房 秋 釣れる魚',summary:'外房で秋に狙えるアジ・青物・ヒラメを中心に整理。',answer:'秋の外房はアジ・青物・ヒラメが有力。港ではアジ、潮通しの良い磯・堤防では青物、砂浜ではヒラメ・マゴチを狙える。海況が荒れやすいため安全優先。',category:'季節・釣り場',sections:[{heading:'港のアジ',body:'朝夕や夜の常夜灯周りが狙い目。'},{heading:'青物',body:'潮通しの良い場所でベイト回遊を待つ。波が高い日は無理をしない。'},{heading:'サーフ',body:'離岸流やブレイクを探しながらヒラメ・マゴチを狙う。'},{heading:'外洋の安全',body:'うねりが入りやすい。低い磯・テトラ・波打ち際へ無理に近づかない。'}],related:[{label:'サーフルアー',href:'/methods/surf-lure'},{label:'ヒラメ図鑑',href:'/fish/hirame'}]},
 {slug:'shonan-summer-fish',title:'湘南で夏に釣れる魚は？サーフと堤防の狙い目',query:'湘南 夏 釣れる魚',summary:'湘南エリアの夏に狙いやすい魚をサーフ・港に分けて紹介。',answer:'湘南の夏はシロギス・マゴチ・小型青物が有力。砂浜ではちょい投げとサーフルアー、港ではサビキが組みやすい。朝夕の涼しい時間を中心に。',category:'季節・釣り場',sections:[{heading:'シロギス',body:'砂浜の代表魚。ちょい投げ〜投げ釣りで広く探る。'},{heading:'マゴチ',body:'水温が高い時期のサーフ本命。ワームやミノーで底付近を通す。'},{heading:'小型青物',body:'ベイト次第でワカシなどが接岸。軽めのメタルジグも有効。'},{heading:'海水浴エリアに注意',body:'夏は遊泳区域や時間規制がある場所も多い。釣り可能エリアを確認。'}],related:[{label:'サーフルアー',href:'/methods/surf-lure'},{label:'ちょい投げ',href:'/methods/choinage'}]},
 {slug:'shonan-autumn-fish',title:'湘南で秋に釣れる魚は？青物・アオリ・ヒラメ',query:'湘南 秋 釣れる魚',summary:'湘南の秋に狙いやすい人気魚をまとめて紹介。',answer:'秋の湘南は青物・アオリイカ・ヒラメが狙い目。港ではアジ、サーフでは青物とフラットフィッシュ、岩礁・港湾部ではエギングが候補。',category:'季節・釣り場',sections:[{heading:'青物',body:'朝まずめにベイトが寄ればチャンス。20〜40g程度のジグから開始。'},{heading:'秋アオリ',body:'小型中心で数釣りしやすい。2.5〜3号のエギが扱いやすい。'},{heading:'ヒラメ',body:'サーフのブレイクや離岸流を重点的に探る。'},{heading:'混雑対策',body:'人気ポイントは混雑しやすい。無理な割り込みや横切るキャストを避ける。'}],related:[{label:'エギング',href:'/methods/eging'},{label:'サーフルアー',href:'/methods/surf-lure'}]},
 {slug:'izu-autumn-fish',title:'伊豆で秋に釣れる魚は？堤防・磯の人気ターゲット',query:'伊豆 秋 釣れる魚',summary:'伊豆半島で秋に狙いやすいアオリイカ・青物・根魚を整理。',answer:'秋の伊豆はアオリイカ・青物・根魚が有力。水深のある堤防では回遊魚、岩礁帯ではエギングと根魚狙いが組みやすい。',category:'季節・釣り場',sections:[{heading:'アオリイカ',body:'秋は小型が多く、港内や藻場周辺をテンポよく探る。'},{heading:'青物',body:'潮通しと水深のある場所で回遊待ち。'},{heading:'根魚',body:'カサゴなどは岩礁帯の足元を穴釣り・ワームで狙える。'},{heading:'磯は装備優先',body:'滑りにくい靴とライフジャケットを使用。高波時は入らない。'}],related:[{label:'エギング',href:'/methods/eging'},{label:'穴釣り',href:'/methods/ana'}]},
 {slug:'surugabay-summer-fish',title:'駿河湾で夏に釣れる魚は？',query:'駿河湾 夏 釣れる魚',summary:'駿河湾沿岸の夏に狙いやすい魚と釣り方を紹介。',answer:'夏の駿河湾はアジ・サバ・青物・シロギスが候補。深場が近い地域では岸からでも回遊魚が入りやすい場所があり、朝まずめの情報収集が重要。',category:'季節・釣り場',sections:[{heading:'港はサビキ',body:'アジ・サバが回る時期は初心者でも数釣りが狙える。'},{heading:'青物',body:'ベイト回遊時はメタルジグやプラグが有効。'},{heading:'砂浜',body:'シロギスやマゴチを狙える場所も多い。'},{heading:'水深の変化',body:'急深の場所は軽すぎる仕掛けでは底取りしにくい。'}],related:[{label:'ショアジギング',href:'/methods/shore-jigging'},{label:'ちょい投げ',href:'/methods/choinage'}]},
 {slug:'isebay-autumn-fish',title:'伊勢湾で秋に釣れる魚は？',query:'伊勢湾 秋 釣れる魚',summary:'伊勢湾で秋に狙いやすいアジ・ハゼ・青物・タチウオを整理。',answer:'秋の伊勢湾はアジ・ハゼ・青物が狙いやすく、地域や年によってタチウオも候補。河口はハゼ、港はサビキ、潮通しの良い場所は青物。',category:'季節・釣り場',sections:[{heading:'アジ',body:'港湾部のサビキやアジングが定番。'},{heading:'ハゼ',body:'河口や汽水域で秋の人気ターゲット。'},{heading:'青物',body:'ベイト次第でハマチなどの回遊がある。'},{heading:'湾奥と湾口で違う',body:'水深・潮流・塩分が違うため、同じ伊勢湾でも狙い魚が変わる。'}],related:[{label:'サビキ釣り',href:'/methods/sabiki'},{label:'ショアジギング',href:'/methods/shore-jigging'}]},
 {slug:'wakasa-autumn-fish',title:'若狭湾で秋に釣れる魚は？アオリ・青物・アジ',query:'若狭湾 秋 釣れる魚',summary:'若狭湾の秋に狙いやすいアオリイカ・青物・アジを整理。',answer:'秋の若狭湾はアオリイカ・アジ・青物が人気。港ではサビキ、岩礁・藻場ではエギング、潮通しの良い堤防ではショアジギングが候補。',category:'季節・釣り場',sections:[{heading:'秋アオリ',body:'新子狙いのエギングが盛ん。2.5〜3号を基準にする。'},{heading:'アジ',body:'港内の朝夕や夜が狙いやすい。'},{heading:'青物',body:'ベイト接岸時は朝まずめを優先。'},{heading:'日本海の風',body:'北寄りの風で急に荒れることがある。予報を早めに確認。'}],related:[{label:'エギング',href:'/methods/eging'},{label:'アジング',href:'/methods/ajing'}]},
 {slug:'setouchi-autumn-fish',title:'瀬戸内海で秋に釣れる魚は？',query:'瀬戸内海 秋 釣れる魚',summary:'瀬戸内海の秋に人気のマダイ・アジ・青物・タチウオを紹介。',answer:'秋の瀬戸内海はマダイ・アジ・青物が有力で、地域によってタチウオも人気。潮流が強い場所では仕掛け重量を現地基準に合わせる。',category:'季節・釣り場',sections:[{heading:'マダイ',body:'船タイラバの人気シーズン。潮の速い海域では重めヘッドを準備。'},{heading:'アジ',body:'港や船で良型が狙える時期。'},{heading:'青物',body:'瀬や潮目で回遊を狙う。船ジギング・ノマセも人気。'},{heading:'潮流対策',body:'海峡部では潮が非常に速い。船宿指定のオモリ・PEを守る。'}],related:[{label:'タイラバ',href:'/methods/tai-rubber'},{label:'ジギング',href:'/methods/jigging'}]},
 {slug:'hakata-bay-autumn-fish',title:'博多湾で秋に釣れる魚は？',query:'博多湾 秋 釣れる魚',summary:'博多湾の秋に狙いやすいアジ・シーバス・青物などを整理。',answer:'秋の博多湾はアジ・シーバスが狙いやすく、場所によってサゴシなどの回遊魚も候補。港湾部と河口を使い分ける。',category:'季節・釣り場',sections:[{heading:'アジ',body:'港内のサビキやアジングが定番。'},{heading:'シーバス',body:'河口や流れ込みでベイトを追う個体を狙う。'},{heading:'回遊魚',body:'ベイトが多い年はサゴシなどが入ることもある。'},{heading:'潮位差を見る',body:'湾奥は潮位変化で釣りやすい場所が変わる。'}],related:[{label:'アジング',href:'/methods/ajing'},{label:'ブレードジギング',href:'/methods/blade-jig'}]},
 {slug:'osakabay-february-fish',title:'大阪湾で2月に釣れる魚は？',query:'大阪湾 2月 釣れる魚',summary:'厳寒期の大阪湾で狙いやすい魚を整理。',answer:'2月はカサゴ・メバルが本命。回遊魚は少なくなりやすく、足元の根魚や夜のライトゲームを中心に組むと安定。',category:'季節・釣り場',sections:[{heading:'カサゴ',body:'穴釣り・胴突きで日中も狙いやすい。'},{heading:'メバル',body:'夜の常夜灯や藻場で狙う。'},{heading:'アジは場所次第',body:'水温の高い深場や港で残ることもある。'},{heading:'短時間勝負',body:'寒さが厳しいため、時合いを絞って釣るのも有効。'}],related:[{label:'穴釣り',href:'/methods/ana'},{label:'メバリング',href:'/methods/mebaring'}]},
 {slug:'osakabay-march-fish',title:'大阪湾で3月に釣れる魚は？春の始まり',query:'大阪湾 3月 釣れる魚',summary:'3月の大阪湾で狙いやすい根魚・メバル・チヌを紹介。',answer:'3月はメバル・カサゴに加え、チヌが意識しやすい時期。水温はまだ低いため、回遊魚より根魚と湾奥魚種を中心に。',category:'季節・釣り場',sections:[{heading:'メバル',body:'春へ向けて好シーズン。夜のライトゲームが有力。'},{heading:'カサゴ',body:'引き続き安定したターゲット。'},{heading:'チヌ',body:'乗っ込み前後で動きが出る地域もある。'},{heading:'水温差を見る',body:'同じ3月でも年ごとに水温差が大きい。直近釣果で判断する。'}],related:[{label:'メバリング',href:'/methods/mebaring'},{label:'フカセ釣り',href:'/methods/fukase'}]},
 {slug:'osakabay-april-fish',title:'大阪湾で4月に釣れる魚は？',query:'大阪湾 4月 釣れる魚',summary:'春本番の大阪湾で狙いやすい魚を整理。',answer:'4月はメバル・チヌ・カサゴが安定しやすく、後半になるほどアジなど回遊魚の気配も増える。春の海は日ごとの差が大きい。',category:'季節・釣り場',sections:[{heading:'メバル',body:'夜の本命。表層〜中層を丁寧に探る。'},{heading:'チヌ',body:'フカセや落とし込みで人気。'},{heading:'アジの兆し',body:'暖かい年は小型アジの回遊が早まる。'},{heading:'風を避ける',body:'春は風が変わりやすい。風裏候補を用意。'}],related:[{label:'メバリング',href:'/methods/mebaring'},{label:'落とし込み',href:'/methods/otoshikomi'}]},
 {slug:'osakabay-may-fish',title:'大阪湾で5月に釣れる魚は？',query:'大阪湾 5月 釣れる魚',summary:'5月の大阪湾で狙いやすいアジ・キス・チヌなどを紹介。',answer:'5月はアジ・シロギス・チヌの選択肢が広がる。初心者はサビキとちょい投げ、夜はメバル・アジングも候補。',category:'季節・釣り場',sections:[{heading:'アジ',body:'小型回遊が始まればサビキの好機。'},{heading:'シロギス',body:'砂地でちょい投げが楽しくなる時期。'},{heading:'チヌ',body:'堤防や河口で引き続き有力。'},{heading:'日中も釣りやすい',body:'暑すぎず初心者の釣行にも向く。'}],related:[{label:'サビキ釣り',href:'/methods/sabiki'},{label:'ちょい投げ',href:'/methods/choinage'}]}
];
