import type {GuideEditorial} from './guide-taxonomy';
// Explicit editorial classification of the existing 216 articles; not inferred from length.
export const guideEditorial:Record<string,GuideEditorial>={
  'fishing-map-permission-check': {"articleType":"GUIDE","topic":"safety","gearTags":[]},
  'first-charter-boat-reservation': {"articleType":"GUIDE","topic":"basics","gearTags":[]},
  'tachiuo-tenya-action': {"articleType":"GUIDE","topic":"fishing","gearTags":["rig"]},
  'aji-sabiki-depth': {"articleType":"GUIDE","topic":"fishing","gearTags":["rig"]},
  'tairaba-bottom-contact': {"articleType":"GUIDE","topic":"fishing","gearTags":["lure"]},
  'shore-jigging-jig-weight': {"articleType":"GUIDE","topic":"fishing","gearTags":["lure"]},
  'eging-shakuri-count': {"articleType":"GUIDE","topic":"fishing","gearTags":["lure"]},
  'kisu-retrieve-speed': {"articleType":"GUIDE","topic":"fishing","gearTags":[]},
  'kasago-ana-rig': {"articleType":"GUIDE","topic":"fishing","gearTags":["rig"]},
  'chinu-field-notes': {"articleType":"GUIDE","topic":"fishing","gearTags":[]},
  'saba-sabiki-cooling': {"articleType":"GUIDE","topic":"fishing","gearTags":["cooler"]},
  'hirame-livebait-observation': {"articleType":"GUIDE","topic":"fishing","gearTags":[]},
  'suzuki-field-notes': {"articleType":"GUIDE","topic":"fishing","gearTags":["lure"]},
  'dangerous-fish-first-check': {"articleType":"GUIDE","topic":"safety","gearTags":[]},
  'sayori-starting-guide': {"articleType":"GUIDE","topic":"fishing","gearTags":[]},
  'gomasaba-starting-guide': {"articleType":"GUIDE","topic":"fishing","gearTags":[]},
  'kurosoi-starting-guide': {"articleType":"GUIDE","topic":"fishing","gearTags":[]},
  'ishidai-starting-guide': {"articleType":"GUIDE","topic":"fishing","gearTags":[]},
  'ishigarei-starting-guide': {"articleType":"GUIDE","topic":"fishing","gearTags":[]},
  'akaamadai-starting-guide': {"articleType":"GUIDE","topic":"fishing","gearTags":[]},
  'kinmedai-starting-guide': {"articleType":"GUIDE","topic":"fishing","gearTags":[]},
  'akamutsu-starting-guide': {"articleType":"GUIDE","topic":"fishing","gearTags":[]},
  'kuromutsu-starting-guide': {"articleType":"GUIDE","topic":"fishing","gearTags":[]},
  'medai-starting-guide': {"articleType":"GUIDE","topic":"fishing","gearTags":[]},
  'tackle-connection-basics': {"articleType":"GUIDE","topic":"tackle","gearTags":["rod","rig"]},
  'tackle-spec-reading': {"articleType":"GUIDE","topic":"tackle","gearTags":["rod","reel","rig"]},
  'leader-drag-first-check': {"articleType":"GUIDE","topic":"tackle","gearTags":["reel","line"]},
  'fishing-first-checklist': {"articleType":"GUIDE","topic":"basics","gearTags":[]},
  'pliers-fishgrip-basics': {"articleType":"GUIDE","topic":"handling","gearTags":["rig","tools"]},
  'fishing-cooler-plan': {"articleType":"GUIDE","topic":"cooking","gearTags":["cooler"]},
  'night-fishing-kit': {"articleType":"GUIDE","topic":"safety","gearTags":[]},
  'akakamas-starting-guide': {"articleType":"GUIDE","topic":"fishing","gearTags":[]},
  'katakuchi-starting-guide': {"articleType":"GUIDE","topic":"fishing","gearTags":[]},
  'urume-starting-guide': {"articleType":"GUIDE","topic":"fishing","gearTags":[]},
  'konoshiro-starting-guide': {"articleType":"GUIDE","topic":"fishing","gearTags":[]},
  'bora-starting-guide': {"articleType":"GUIDE","topic":"fishing","gearTags":[]},
  'shiira-starting-guide': {"articleType":"GUIDE","topic":"fishing","gearTags":[]},
  'makogarei-starting-guide': {"articleType":"GUIDE","topic":"fishing","gearTags":[]},
  'umazurahagi-starting-guide': {"articleType":"GUIDE","topic":"fishing","gearTags":[]},
  'kidai-starting-guide': {"articleType":"GUIDE","topic":"fishing","gearTags":[]},
  'kensakiika-starting-guide': {"articleType":"GUIDE","topic":"fishing","gearTags":[]},
  'mejina-field-notes': {"articleType":"QUICK GUIDE","topic":"fishing","gearTags":[]},
  'haze-field-notes': {"articleType":"GUIDE","topic":"fishing","gearTags":[]},
  'ainame-field-notes': {"articleType":"QUICK GUIDE","topic":"fishing","gearTags":[]},
  'kijihata-field-notes': {"articleType":"QUICK GUIDE","topic":"fishing","gearTags":[]},
  'akahata-field-notes': {"articleType":"QUICK GUIDE","topic":"fishing","gearTags":[]},
  'oomonhata-field-notes': {"articleType":"QUICK GUIDE","topic":"fishing","gearTags":[]},
  'houbo-field-notes': {"articleType":"GUIDE","topic":"fishing","gearTags":["rig"]},
  'itoyoridai-field-notes': {"articleType":"GUIDE","topic":"handling","gearTags":[]},
  'kouika-field-notes': {"articleType":"QUICK GUIDE","topic":"fishing","gearTags":["lure"]},
  'yariika-field-notes': {"articleType":"QUICK GUIDE","topic":"fishing","gearTags":["rig"]},
  'iwashi-field-notes': {"articleType":"GUIDE","topic":"fishing","gearTags":[]},
  'kanpachi-field-notes': {"articleType":"QUICK GUIDE","topic":"fishing","gearTags":[]},
  'isaki-field-notes': {"articleType":"QUICK GUIDE","topic":"fishing","gearTags":["rig"]},
  'anago-field-notes': {"articleType":"GUIDE","topic":"fishing","gearTags":["rig"]},
  'ayu-field-notes': {"articleType":"GUIDE","topic":"fishing","gearTags":[]},
  'nijimasu-field-notes': {"articleType":"QUICK GUIDE","topic":"fishing","gearTags":["lure"]},
  'amago-field-notes': {"articleType":"GUIDE","topic":"fishing","gearTags":[]},
  'magochi-field-notes': {"articleType":"QUICK GUIDE","topic":"fishing","gearTags":[]},
  'sawara-blade-range': {"articleType":"GUIDE","topic":"fishing","gearTags":[]},
  'madako-bottom-rules': {"articleType":"GUIDE","topic":"fishing","gearTags":["lure"]},
  'quest-bite-reading': {"articleType":"QUICK GUIDE","topic":"basics","gearTags":[]},
  'osakabay-september-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'tachiuo-tenya-40-vs-50': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["rig"]},
  'tairaba-pe': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["line","lure"]},
  'aji-sabiki-hook-size': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["rig"]},
  'nomase-leader': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["line"]},
  'eging-pe': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["line","lure"]},
  'sabiki-cage-weight': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["rig"]},
  'tachiuo-leader': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["line"]},
  'tairaba-weight': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["lure"]},
  'kisu-hook-size': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["rig"]},
  'kawahagi-hook': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["rig"]},
  'mebaring-jighead': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["lure"]},
  'aoriika-egi-size': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["lure"]},
  'buri-nomase-drag': {"articleType":"QUICK GUIDE","topic":"fishing","gearTags":["reel"]},
  'blade-jig-leader': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["line"]},
  'osakabay-october-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'beginner-sea-fishing-setup': {"articleType":"GUIDE","topic":"basics","gearTags":[]},
  'tairaba-leader': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["line","lure"]},
  'aji-boat-leader': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["line"]},
  'tachiuo-shore-tenya-weight': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["rod","rig","lure"]},
  'tachiuo-tenya-bait': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["rig"]},
  'tachiuo-float-depth': {"articleType":"QUICK GUIDE","topic":"fishing","gearTags":[]},
  'ajing-jighead-weight': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["lure"]},
  'ajing-line': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["line"]},
  'sabiki-best-time': {"articleType":"QUICK GUIDE","topic":"fishing","gearTags":[]},
  'sabiki-amiebi-amount': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":[]},
  'tairaba-retrieve-speed': {"articleType":"QUICK GUIDE","topic":"fishing","gearTags":["lure"]},
  'tairaba-color': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["lure"]},
  'nomase-bait-size': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":[]},
  'nomase-hook-size': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["rig"]},
  'shore-jigging-pe': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["line"]},
  'eging-leader': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["line","lure"]},
  'kasago-best-bait': {"articleType":"QUICK GUIDE","topic":"fishing","gearTags":[]},
  'kisu-sinker-weight': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["rig"]},
  'kawahagi-asari-bait': {"articleType":"QUICK GUIDE","topic":"fishing","gearTags":[]},
  'akashi-tairaba-weight': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["lure"]},
  'osakabay-november-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'osakabay-december-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'tachiuo-hooking-timing': {"articleType":"QUICK GUIDE","topic":"fishing","gearTags":["rig"]},
  'tairaba-hook-size': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["rig","lure"]},
  'aji-sabiki-skin-color': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":[]},
  'ajing-worm-color': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":[]},
  'shore-jigging-leader-length': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["line"]},
  'shore-jigging-best-time': {"articleType":"QUICK GUIDE","topic":"fishing","gearTags":[]},
  'eging-best-time': {"articleType":"QUICK GUIDE","topic":"fishing","gearTags":["lure"]},
  'kisu-best-bait': {"articleType":"QUICK GUIDE","topic":"fishing","gearTags":[]},
  'kawahagi-sinker': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["rig"]},
  'mebaring-line': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["line"]},
  'kasago-size-limit': {"articleType":"QUICK GUIDE","topic":"safety","gearTags":[]},
  'surf-lure-weight': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["lure"]},
  'surf-best-time': {"articleType":"QUICK GUIDE","topic":"fishing","gearTags":[]},
  'boat-kisu-sinker': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["rig"]},
  'osakabay-january-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'tokyobay-spring-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'tokyobay-summer-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'tokyobay-autumn-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'tokyobay-winter-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'yokohama-beginner-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'chiba-uchibo-autumn-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'chiba-sotobo-autumn-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'shonan-summer-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'shonan-autumn-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'izu-autumn-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'surugabay-summer-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'isebay-autumn-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'wakasa-autumn-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'setouchi-autumn-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'hakata-bay-autumn-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'osakabay-february-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'osakabay-march-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'osakabay-april-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'osakabay-may-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'tokyobay-march-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'tokyobay-april-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'tokyobay-may-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'tokyobay-june-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'tokyobay-july-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'tokyobay-august-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'tokyobay-september-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'tokyobay-october-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'tokyobay-november-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'tokyobay-december-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'tokyobay-january-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'tokyobay-february-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'kanagawa-pier-beginner': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'chiba-pier-beginner': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'aichi-bay-autumn-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'miura-autumn-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'awaji-autumn-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'wakayama-autumn-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'fukuoka-beginner-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'sendai-bay-autumn-fish': {"articleType":"QUICK GUIDE","topic":"season","gearTags":[]},
  'fishing-wind-limit': {"articleType":"QUICK GUIDE","topic":"safety","gearTags":[]},
  'fishing-rain': {"articleType":"QUICK GUIDE","topic":"basics","gearTags":[]},
  'fishing-tide-best': {"articleType":"QUICK GUIDE","topic":"basics","gearTags":[]},
  'fishing-before-after-high-tide': {"articleType":"QUICK GUIDE","topic":"basics","gearTags":[]},
  'fg-knot-vs-pr-knot': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["line"]},
  'leader-length-general': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["line"]},
  'pe-line-how-much': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["line"]},
  'spinning-reel-size': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["reel"]},
  'rod-length-beginner': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["rod"]},
  'cooler-size-fishing': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["cooler"]},
  'ice-amount-cooler': {"articleType":"QUICK GUIDE","topic":"cooking","gearTags":["cooler"]},
  'fish-ikejime-basics': {"articleType":"GUIDE","topic":"handling","gearTags":["cooler"]},
  'fish-carry-home': {"articleType":"GUIDE","topic":"cooking","gearTags":["cooler"]},
  'fish-freeze-how-long': {"articleType":"QUICK GUIDE","topic":"cooking","gearTags":[]},
  'night-fishing-light': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["safety"]},
  'life-jacket-type': {"articleType":"QUICK GUIDE","topic":"safety","gearTags":["safety"]},
  'boat-fishing-seasick': {"articleType":"QUICK GUIDE","topic":"safety","gearTags":[]},
  'bait-keep-alive-aji': {"articleType":"QUICK GUIDE","topic":"fishing","gearTags":[]},
  'snag-release': {"articleType":"QUICK GUIDE","topic":"basics","gearTags":[]},
  'fishing-line-twist': {"articleType":"QUICK GUIDE","topic":"basics","gearTags":["reel","line"]},
  'tairaba-reel-beginner': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["reel","lure"]},
  'tairaba-rod-beginner': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["rod","lure"]},
  'tairaba-tungsten-worth-it': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["lure"]},
  'shore-jigging-reel-size': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["reel"]},
  'shore-jigging-rod-power': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["rod"]},
  'eging-reel-size': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["reel","lure"]},
  'eging-rod-length': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["rod","lure"]},
  'ajing-rod-solid-tubular': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["rod"]},
  'ajing-reel-size': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["reel"]},
  'sabiki-rod-choice': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["rod"]},
  'sabiki-reel-size': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["reel"]},
  'nomase-reel-choice': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["reel"]},
  'nomase-rod-choice': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["rod"]},
  'tachiuo-tenya-rod-choice': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["rod","rig"]},
  'tachiuo-tenya-reel-choice': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["reel","rig"]},
  'kawahagi-rod-choice': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["rod"]},
  'kawahagi-reel-choice': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["reel"]},
  'boat-kisu-rod-choice': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["rod"]},
  'boat-kisu-reel-choice': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["reel"]},
  'fishing-cooler-15-vs-30': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["cooler"]},
  'fishing-cooler-vacuum-panel': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["cooler"]},
  'life-jacket-waist-vs-shoulder': {"articleType":"QUICK GUIDE","topic":"safety","gearTags":["safety"]},
  'fishing-headlight-lumens': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["safety"]},
  'fishing-pliers-choice': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["line","tools"]},
  'fish-grip-choice': {"articleType":"QUICK GUIDE","topic":"handling","gearTags":["tools"]},
  'landing-net-length': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["tools"]},
  'pe-line-4-vs-8-strand': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["line"]},
  'leader-fluoro-vs-nylon': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["line"]},
  'bobbin-winder-light-heavy': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["line","safety"]},
  'fishing-bag-hard-vs-soft': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["tools"]},
  'polarized-sunglasses-fishing': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["safety"]},
  'fishing-rainwear-choice': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["safety"]},
  'tairaba-pe-06-08-1': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["line","lure"]},
  'shore-jigging-pe-15-vs-2': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["line"]},
  'eging-pe-06-vs-08': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["line","lure"]},
  'nomase-pe3-vs4': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["line"]},
  'cooler-15-vs-32': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["cooler"]},
  'tairaba-ic-reel-necessary': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["lure"]},
  'tachiuo-pg-vs-hg': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["reel","rig"]},
  'fishing-reel-2500-vs4000': {"articleType":"QUICK GUIDE","topic":"tackle","gearTags":["reel"]},
  'fluoro-leader-size-guide': {"articleType":"GUIDE","topic":"tackle","gearTags":["line"]},
  'pe-line-size-guide': {"articleType":"GUIDE","topic":"tackle","gearTags":["line"]},
};
