import type {FishingMapEntry} from './fishing-map-data';
export type SpotPrimaryType='boat'|'facility'|'park'|'port'|'pier'|'beach'|'rock'|'estuary'|'fresh'|'area'|'shore';
// Editorial audit of every existing record: managed fishing facilities are distinct from structure/terrain.
const facilities=new Set(['tomakomai-ippon','asamushi-umizuri','honmoku-fishing','niigata-happyfishing','atami-port-fishing','shimonoseki-fishing','kamoike-umizuri','motobu-ikada','yura-yamagata-fishing','shimizu-port-park','mikata-sea-fishing','yura-wakayama-park','waita-fishing-pier','sakurajima-umizuri','takashima-tobishima','akita-north','shinchi-park','kashima-fishing','wakasu-fishing','daikoku-fishing','isogo-fishing','ichihara-fishing','ishida-fisherina','shinmaiko-fishing','toyohama-pier','arai-benten','suma-fishing','fukuoka-fishing','amagasaki-uoturi','minamiawaji-megafloat','saikazaki-seapark','naruohama','miyazu-sea-fishing','hira-isoumi','tottopark-kojima','nanko-fishing-park']);
const parks=new Set(['oi-nagisa-fishing','yokosuka-umibe','yumeminato-park','maizuru-shinkai']);
export function spotPrimaryType(e:Pick<FishingMapEntry,'slug'|'type'|'terrain'|'primaryType'>):SpotPrimaryType{
 if(e.primaryType)return e.primaryType;if(e.type==='boat')return 'boat';if(facilities.has(e.slug))return 'facility';if(parks.has(e.slug))return 'park';if(e.slug==='kada-port')return 'port';
 switch(e.terrain){case 'port':return 'port';case 'pier':return 'pier';case 'park':return 'park';case 'sea-pond':return 'facility';case 'beach':return 'beach';case 'rock':return 'rock';case 'estuary':return 'estuary';case 'river':case 'lake':case 'pond':return 'fresh';case 'boat':return 'area';default:return 'shore';}
}
export function classifySpot(e:FishingMapEntry):FishingMapEntry{return {...e,primaryType:spotPrimaryType(e),features:[...new Set([...(e.features??[]),...(({pier:['堤防・桟橋'],shore:['護岸・海岸'],park:['公園'],port:['港'],raft:['イカダ'],rock:['磯']} as Record<string,string[]>)[e.terrain??'']??[]),...(e.parking?['駐車場']:[]),...(e.toilet?['トイレ']:[])])]};}
