export const englishCookingFish=['tachiuo','aji','madai','buri','kisu','kasago','saba','kawahagi','mebaru','aoriika'];
export const englishDishes:Record<string,{name:string;description:string;steps:string[]}>={
 sashimi:{name:'Sashimi / thin-sliced raw fish',description:'A traditional way to appreciate texture. Freshness alone does not establish that a catch is safe to eat raw.',steps:['Have species identification and suitability for raw consumption assessed by a qualified fish professional.','Use professional parasite-control and cold-chain procedures; this is not a home raw-fish safety protocol.','For an uncertain recreational catch, choose an appropriate thoroughly cooked dish instead.']},
 shioyaki:{name:'Shioyaki — salt-grilled',description:'Salt and dry surface skin bring out the character of the fish without a heavy sauce.',steps:['Scale where needed, remove gills and guts, clean briefly and dry carefully. For squid, clean and portion the mantle instead.','Salt lightly and wipe away released moisture.','Grill until cooked through, turning carefully; serve with citrus.']},
 tempura:{name:'Tempura',description:'A light batter suits delicate whiting, hairtail and squid.',steps:['Prepare boneless portions and dry their surfaces.','Coat lightly with flour and cold tempura batter.','Fry in small batches until cooked through; drain before serving. Keep wet utensils away from hot oil.']},
 nitsuke:{name:'Nitsuke — soy-simmered',description:'Gentle simmering keeps delicate flesh together while seasoning it with soy, sake and ginger.',steps:['Clean the fish and score thick skin where appropriate.','Bring water, soy sauce, sake and a little sugar to a simmer; add the fish and ginger.','Cook through with a drop lid or spooned-over sauce, moving the fish as little as possible.']},
 'aji-fry':{name:'Aji fry — breaded horse mackerel',description:'Boned horse mackerel in a crisp breadcrumb coating.',steps:['Remove scutes, head, innards and bones; open the fish or use fillets.','Dry, season lightly, then coat with flour, beaten egg and panko.','Fry until cooked through and drain; check carefully for remaining bones when serving children.']},
 namero:{name:'Namerō — chopped fish with miso',description:'A regional raw-fish preparation with miso, ginger and aromatic herbs. Miso does not make raw fish parasite-safe.',steps:['Use only fish professionally assessed and prepared for raw consumption.','The traditional preparation chops the fish with miso and aromatics.','Keep it chilled; use a thoroughly cooked preparation if raw-fish suitability is uncertain.']},
 chazuke:{name:'Tai chazuke — seabream over rice',description:'Seabream is served over rice with broth or tea. A cooked-fish version is practical for recreational catches.',steps:['Cook boneless seabream portions through.','Arrange over warm rice with sesame and nori.','Pour over hot stock or tea and serve promptly; pouring hot liquid over raw fish alone is not a reliable cooking step.']},
 teriyaki:{name:'Buri teriyaki',description:'Amberjack steaks glazed with a sweet soy sauce.',steps:['Dry boneless steaks and season lightly.','Pan-cook both sides until cooked through.','Add soy sauce, mirin and sake, then reduce briefly to coat without burning.']},
 shabu:{name:'Buri shabu-shabu',description:'Thin amberjack slices are cooked in a light broth and served with dipping sauce.',steps:['Prepare thin boneless slices and separate utensils for raw and cooked food.','Bring kombu broth and vegetables to a simmer.','Cook each slice through; do not rely on a very brief dip for an uncertain catch.']},
 daikon:{name:'Buri daikon — amberjack with radish',description:'Fish and daikon absorb a ginger-scented soy broth.',steps:['Cut daikon and pre-cook until beginning to soften.','Clean fish portions and briefly blanch and rinse away surface scum.','Simmer with daikon, ginger, water, soy sauce and sake until fish is cooked and radish tender.']},
 nanbanzuke:{name:'Nanbanzuke — fried fish in sweet vinegar',description:'Fried fish is dressed with onion and a light sweet-vinegar marinade.',steps:['Prepare small boneless portions and dry well.','Coat lightly and fry until cooked through.','Add to a prepared vinegar dressing with sliced vegetables; chill promptly if storing. Vinegar is seasoning, not parasite control.']},
 karaage:{name:'Karaage — crisp fried fish',description:'A flour or starch coating gives firm fish a crisp exterior.',steps:['Clean and portion the fish, removing bones and spines as needed.','Dry thoroughly and coat lightly with starch.','Fry in small batches until cooked through. Large bones are not made edible simply by frying.']},
 misoshiru:{name:'Fish miso soup',description:'Clean fish pieces add flavour to a simple soup.',steps:['Remove gills, innards and blood, and rinse cleaned pieces briefly.','Simmer in water or stock, skimming as needed, until fish is cooked through.','Lower the heat, dissolve miso and serve, clearly identifying any bones.']},
 shimesaba:{name:'Shime-saba — cured mackerel',description:'Salt-and-vinegar curing creates a distinctive flavour but does not reliably kill parasites.',steps:['Use fish professionally assessed and processed for this raw-style dish.','Salt and vinegar are culinary steps, not a substitute for validated parasite control.','For a recreational catch with uncertain handling, choose salt-grilling or miso simmering instead.']},
 misoni:{name:'Saba misoni — miso-simmered mackerel',description:'Ginger and miso balance the rich flavour of mackerel.',steps:['Use promptly chilled fish; cooking does not undo earlier histamine formation.','Clean and portion, then simmer with ginger, water and sake.','Dissolve miso into the broth and finish cooking gently.']},
 tatsutaage:{name:'Tatsuta-age — ginger-soy fried mackerel',description:'A short ginger-soy seasoning and starch coating suit mackerel pieces.',steps:['Use properly chilled fish and remove bones.','Season briefly with ginger, soy sauce and sake, then drain and coat with starch.','Fry until cooked through and serve promptly.']},
 nabe:{name:'Fish hot pot',description:'Filefish and vegetables are cooked together in a light broth.',steps:['Remove the tough skin, clean the fish and portion carefully.','Bring stock and firm vegetables to a simmer.','Add fish and softer vegetables and cook through; keep raw-fish utensils separate.']},
 'kimo-shoyu':{name:'Filefish sashimi with liver-soy sauce',description:'Liver is a characteristic part of kawahagi cuisine. Raw liver carries risks and needs professional assessment.',steps:['Use an experienced fish professional for species identification, safe liver handling and raw-fish suitability.','A cooked-liver sauce can be paired with an appropriately prepared dish; cooking the sauce does not make raw flesh safe.','This page describes the food culture, not a home protocol for serving raw liver.']},
 'kimo-ae':{name:'Filefish dressed with liver',description:'Kimo-ae brings the rich liver flavour to filefish. It should not be interpreted as permission to eat an unassessed catch raw.',steps:['Ask a qualified professional to assess and prepare the fish and liver.','Use a fully cooked preparation when raw suitability is uncertain.','Keep prepared food chilled and raw and cooked utensils separate.']},
 aquapazza:{name:'Acqua pazza — fish in a light broth',description:'A whole cleaned rockfish or fillets are gently cooked with tomatoes and aromatics.',steps:['Scale and clean the fish and remove gills.','Place in a pan with tomatoes, water, olive oil and optional herbs.','Simmer gently until cooked through and serve with the broth.']},
 butter:{name:'Squid with butter and soy sauce',description:'Small even pieces cook quickly and take a simple buttery glaze.',steps:['Remove innards, beak and internal shell; clean and dry.','Cut into even pieces and sauté without crowding the pan.','Cook through, then finish with butter and a little soy sauce.']}
};
