// English editorial overlays keyed by the existing species slug; no duplicate base records.
const rows=`tachiuo|Its ribbon-shaped silver body is driven by a long dorsal fin. Hairtail may hover head-up before moving horizontally to chase prey.|Coastal and offshore midwater; fish may rise in low light.|Keep hands away from the mouth, even after landing. Use a grip and long pliers.
aji|A schooling fish with a line of hard scutes near the tail. Small fish are popular sabiki targets; larger fish also take light jigheads.|Harbours, coastal bays and offshore schools.
madai|A pink-red seabream with a strong profile and small blue markings. Tai-raba and baited tenya are established Japanese boat methods.|Rocky and sandy coastal bottoms, often reached by boat.
buri|Japanese amberjack change local names as they grow: hamachi, inada and warasa may refer to younger stages. Size and season change the tackle required.|Coastal baitfish schools and offshore current lines.
kisu|A slender pale fish that feeds close to sand. Small baits and short pauses help distinguish bites from the sinker touching bottom.|Sandy shallows and bays.
kasago|A mottled bottom fish that waits beside cover. Lift a hooked fish away from rocks promptly rather than letting it return to a crevice.|Rocky bottoms, harbour edges and gaps in structure.|Watch the sharp fin spines and gill edges; use pliers to remove hooks.
saba|A fast-moving schooling fish with dark wavy markings along the back. It often runs sideways when hooked, so recover the rig before lines cross.|Coastal schools and offshore feeding areas.|Chill promptly after capture. Cooking does not remove histamine that has already formed.
iwashi|A silver schooling fish with spots along the side. Small sabiki hooks and gentle handling suit its delicate body.|Coastal bays and passing schools near harbour entrances.
suzuki|A large-mouthed predator often called seabass or sea bass in Japan. It uses current seams and structure rather than staying at one fixed depth.|Estuaries, harbours, beaches and coastal current edges.
chinu|Black seabream, also known as chinu or kurodai, feeds around structure and estuary margins. Float and bottom-lure methods approach it differently.|Harbours, rocky edges and brackish water.
kawahagi|Filefish have a small mouth and can strip bait without a strong pull. The tough skin is removed during preparation; the liver is a prized part of Japanese cuisine.|Mixed sand and rock, including coastal boat grounds.|Do not treat freshly caught fish or raw liver as automatically safe to eat.
hirame|Olive flounder lie on the seabed and rise to intercept prey. Their flat outline and both eyes on one side distinguish them from upright-swimming fish.|Sand near baitfish, often beside channels or rocky transitions.
mebaru|These large-eyed rockfish use shallow structure and low-light feeding opportunities. A slow lure above the rocks can be more effective than dragging bottom.|Rocky shallows, seaweed edges and harbour structures.
aoriika|Broad fins run along much of the mantle. Squid may follow an egi before taking it during a pause or fall.|Coastal weed beds, rocky margins and bays.|Avoid the beak and keep fingers clear of the hook crown. Do not lift a heavy squid by the line alone.
madako|An octopus can grip bottom structure strongly and is often detected as weight rather than a sharp bite.|Rocky bottoms and mixed coastal ground.|Octopus collection may be subject to local fishing rights. Check permission before targeting it.
kanpachi|Greater amberjack often dive hard towards structure immediately after being hooked. A boat skipper’s tackle recommendations matter.|Reefs and offshore structure in warmer coastal waters.
sawara|A streamlined predator with cutting teeth. Fast retrieves and careful leader checks are important in blade-jig fishing.|Coastal and offshore baitfish schools.|Keep fingers away from the teeth and use long pliers.
amago|A salmonid identified in part by its red spots. Do not rely on one colour marking when distinguishing related trout and hybrids.|Cool streams and managed trout fisheries.
nijimasu|Rainbow trout have dark spots and often a pink side stripe. Managed fisheries are a practical way to learn local rules and tackle.|Cool lakes, streams and stocked fisheries.
ayu|Ayu are associated with flowing rivers and grazing on attached algae. Tomozuri exploits territorial behaviour; lure-based ayuing has separate local permissions.|Clear rivers and seasonal migration routes.
unagi|Japanese eels are elongated fish of rivers and estuaries. Retention rules and conservation concerns vary by region.|Rivers, estuaries and connected coastal waters.|Do not eat raw eel. Have it prepared and thoroughly cooked by someone familiar with the fish.
anago|Whitespotted conger live in marine water, unlike river-associated unagi. Bottom rigs are commonly used in low light.|Sandy or muddy coastal bottom and harbour channels.|Do not eat raw conger; careful boning and thorough cooking are needed.
isaki|Chicken grunt are popular boat targets. Groundbait and bait need to reach the skipper’s chosen depth together.|Coastal reefs and nearby midwater schools.
magochi|A broad flattened head distinguishes this bottom predator from flounder. It attacks prey close to sandy bottom.|Sand and mud in shallow coastal water.|Head and gill-cover spines can injure hands. Secure the fish before unhooking.
mejina|Known to many Japanese anglers as gure, this dark fish is closely associated with rocky-shore float fishing.|Rocky coastlines and reef edges.
haze|Yellowfin gobies are accessible light-tackle targets. Small hooks and nearby casts often work better than oversized bait and long casts.|Estuary sand, mud and shallow channels.
ainame|Fat greenling feed around rocks and seaweed. Their repeated head shakes should be distinguished from a stationary snag.|Cool-water rocky bottoms and harbour structure.
kijihata|A warm-water grouper that dives back into cover after a take. Plan the first few seconds of the fight before casting.|Rocky coastal ground and reef margins.
akahata|Blacktip grouper are taken close to rocky bottom. Brief bottom contact followed by a lift helps reduce lost rigs.|Warm coastal reefs and rocky slopes.
oomonhata|Areolate grouper may chase prey above the seabed. Searching only the bottom can miss fish feeding higher in the water.|Reef margins and nearby open water.
houbo|A gurnard with broad pectoral fins and separate lower fin rays used around the seabed.|Sand and mixed offshore bottom.
itoyoridai|Golden threadfin bream have yellow striping and a trailing upper tail ray. Their soft flesh benefits from gentle landing and cooling.|Sandy and muddy coastal boat grounds.
kouika|Cuttlefish are broad-bodied bottom-associated cephalopods. A longer pause near the seabed can be useful with an egi.|Sandy bottom near weed and structure.
yariika|Spear squid have a slender pointed mantle. Long multi-jig rigs need an orderly drop and recovery.|Coastal and offshore seasonal squid grounds.
akakamas|Red barracuda are narrow-bodied predators often found in coastal schools.|Harbour mouths and coastal baitfish routes.|Use long pliers and avoid the sharp teeth.
katakuchi|Japanese anchovies have a protruding upper jaw and a small delicate body. Use small hooks and gentle recovery.|Coastal schooling water.
urume|Round herring are silver schooling fish with relatively large eyes. They can arrive in passing groups rather than remain at a fixed spot.|Coastal bays and open-water schools.
konoshiro|Dotted gizzard shad have a dark shoulder mark and rows of small spots. Young fish are known as kohada in Japanese cuisine.|Bays, estuaries and coastal schools.
bora|Grey mullet have a broad head and feed differently from predatory seabass despite sharing estuaries.|Estuaries, harbours and shallow coastal water.
shiira|Dolphinfish, or mahi-mahi, are colourful fast-moving pelagic fish. Floating structure can attract them offshore.|Warm offshore surface waters.
makogarei|A right-eyed flatfish commonly sought with bait on bottom. Distinguish it from other local flatfish before naming a catch.|Coastal sand and mud.
umazurahagi|Black scraper have a longer face than kawahagi. Their skin is tough and liver dishes are part of local food culture.|Coastal reefs and adjacent midwater.|Raw liver is not made safe by freshness alone. Expert identification and safe preparation are essential.
kidai|Yellowback seabream are often called renkodai. They are smaller seabream associated with boat bottom fishing.|Offshore sandy bottom.
kensakiika|Swordtip squid are a major target of ika-metal fishing. Small tip movements may indicate a take.|Seasonal coastal and offshore squid schools.
sayori|Japanese halfbeak have an extended lower jaw. Their small mouth calls for small bait and hooks close to the surface.|Sheltered coastal surface water.
gomasaba|Blue mackerel have spotted lower sides rather than the clearer belly of chub mackerel.|Coastal and offshore schools.|Cool promptly. Histamine risk is not corrected by later cooking.
kurosoi|Black rockfish have a large mouth and a dark body. Several dark rockfish resemble one another, so colour alone is insufficient.|Cool coastal rocks and harbour structure.
ishidai|Striped beakfish have powerful jaws. Heavy bottom tackle is a specialist Japanese rock-shore technique.|Rocky reefs and rough coastal bottom.
ishigarei|Stone flounder have distinctive hard bony areas on the upper side. Bottom rigs cover sand and mud.|Shallow coastal sand, mud and estuary margins.
akaamadai|Red tilefish live close to soft bottom. Boat anglers use controlled bottom contact rather than dragging the bait indefinitely.|Offshore sandy and muddy seabeds.
kinmedai|Splendid alfonsino have large reflective eyes suited to deeper water. Fishing requires specialist boat equipment.|Deep offshore grounds.
akamutsu|Blackthroat seaperch are also known as nodoguro. Their name refers to the dark interior of the mouth.|Deeper sandy and muddy grounds.
kuromutsu|Gnomefish have a large toothed mouth. Deep-water bait rigs are common.|Deeper coastal and offshore water.|Keep hands clear of the teeth.
medai|Japanese butterfish have a thick mucus coating. They are often targeted with groundbait from boats.|Offshore midwater near deep structure.
kusafugu|A small pufferfish encountered by shore anglers. Similar-looking puffer species and variable toxin distribution make amateur food identification unsafe.|Shallow coastal water and estuaries.|WARNING: Never prepare caught pufferfish at home or give them to an unqualified cook. No recipes are provided.
aigo|Mottled spinefoot, or aigo, can be caught around rocky shores. Its spines remain hazardous during handling.|Rocky shallows and seaweed areas.|WARNING: Venomous dorsal, anal and pelvic spines. Do not handle bare-handed. Food preparation requires safe removal of hazardous parts by an experienced person.
gonzui|This striped eel catfish may occur in dense schools. Its small size does not make it safe to handle.|Coastal rocks and harbour bottoms.|WARNING: Venomous dorsal and pectoral spines. Do not grip with bare hands; seek experienced assistance to unhook it.
haokoze|A small scorpionfish that can be mistaken for a harmless small rockfish.|Seaweed and rocky shallows.|WARNING: Venomous spines. Do not touch bare-handed or put it in a mixed catch bag for later sorting.
oniokoze|Devil stinger blend into the seabed with a rough outline and broad head.|Sand and mixed coastal bottom.|WARNING: Venomous dorsal spines. Leave handling and food preparation to trained specialists.
minokasago|Lionfish have conspicuous striped fins but should not be held by them.|Rocky coastal water.|WARNING: Venomous fin spines. Avoid bare-hand contact and do not attempt unfamiliar preparation.
akaei|A broad bottom-dwelling ray with a long tail. The tail can reach a person standing beside the fish.|Shallow sand, mud and estuary bottom.|WARNING: Keep clear of the venomous tail spine. Do not pin the fish with a foot or lift it by the tail.
yamame|A landlocked masu salmon with patterned sides. Local stream rules and closed seasons are central to trip planning.|Cool mountain streams.
wakasagi|Small Japanese smelt are caught with fine multi-hook rigs. Access may be from shore, boats or managed platforms.|Lakes and managed smelt fisheries.
iwana|White-spotted char are associated with cool headwater streams. Small habitats can be sensitive to fishing pressure.|Cold upper rivers and managed fisheries.
shimaaji|Striped jack have a conspicuous pale side stripe. Boat and managed marine-pond fishing use different tackle arrangements.|Warm coastal schools and marine fishing ponds.
hiramasa|Yellowtail amberjack resemble buri but are associated with powerful runs near reef structure.|Coastal reefs and offshore current lines.
kaiwari|Whitefin trevally have a deep, laterally compressed silver body.|Coastal and offshore water over sand and mixed bottom.
maruaji|Japanese scad are schooling relatives of horse mackerel. Confirm body markings rather than using size alone to identify them.|Coastal and offshore schools.
takabe|Yellowstriped butterfish have a bright stripe along the upper side and are a familiar food fish in parts of Japan.|Warm rocky coastlines.
shiroamadai|White tilefish are bottom-associated boat targets; do not assume every tilefish on the same ground is the same species.|Coastal soft-bottom grounds.
suma|Kawakawa are small tunas with a robust body. Check markings near the pectoral region when distinguishing similar tunas.|Warm coastal and offshore schools.
hirasouda|Frigate tuna and bullet tuna are easily confused; inspect body markings before assigning a species.|Warm coastal pelagic schools.
marusouda|Bullet tuna are small fast schooling tunas. Rapid cooling is important if fish are retained.|Warm coastal and offshore water.
usubahagi|Unicorn leatherjacket have a large flattened body and tough skin. Food suitability can depend on local advice.|Warm coastal water.|Do not assume an unfamiliar leatherjacket is safe to prepare from appearance alone.
maeso|Largescale lizardfish have a broad toothed mouth and ambush prey near bottom. Numerous bones affect how the flesh is used.|Sandy coastal bottom.|Use pliers around the teeth.
datsu|Needlefish have long toothed jaws and swim close to the surface. Avoid directing bright lights at fish at close range.|Coastal surface water.|Keep clear of the pointed jaws and handle with tools.
blackbass|Largemouth bass are familiar freshwater lure targets. They are non-native in Japan, and handling and transport rules need checking locally.|Lakes, reservoirs and ponds.|Do not move live fish between waters. Follow local rules on release and retention.
bluegill|Bluegill are deep-bodied sunfish with a dark opercular flap. They are non-native in Japan.|Ponds, lakes and gentle freshwater margins.|Do not transport live fish between waters; check local handling rules.
rouninaji|Giant trevally are powerful reef predators. Heavy tackle and an experienced operator are appropriate for large fish.|Warm southern reefs and coastal current edges.
kihada|Yellowfin tuna are pelagic fish requiring tackle suited to their size. Charter instructions take priority over generic tackle lists.|Warm offshore water.
itou|Japanese huchen are large salmonids with limited distribution. Conservation and local access restrictions are essential considerations.|Northern rivers and connected waters.|Use a conservation-minded local guide and minimise handling. This entry does not provide food preparation advice.
akame|Japanese lates are large estuary predators with a restricted range. Responsible fishing includes planning the release before a cast.|Warm estuaries and lower rivers.|Follow local conservation guidance and avoid extended handling. No cooking guidance is provided.
kurokajiki|Blue marlin are large offshore billfish targeted by specialist trolling charters.|Warm offshore water.|Leave leadering, handling and release to an experienced crew.
herabuna|Herabuna are selectively bred crucian carp associated with Japanese float fishing. Dough bait and precise depth setting define the technique.|Managed ponds and selected freshwater venues.
koi|Common carp feed close to bottom but can also take food higher in the water. Secure tackle and a large landing net are important.|Ponds, lakes and slower rivers.
oikawa|Pale chub are small river fish; breeding males can show vivid colour. Light float tackle suits modest current.|Clear streams and river margins.
chika|Japanese surf smelt are small coastal schooling fish, unlike lake-dwelling wakasagi.|Northern harbours and coastal bays.
umitanago|Temminck’s surfperch have a deep body and inhabit coastal structure. Light float tackle is a common approach.|Seaweed, rocky shallows and harbour edges.
shiroguchi|Silver croaker are bottom-associated fish known locally as ishimochi. Estuary and coastal bait rigs can take them.|Sand and mud in bays and coastal water.
magarei|Brown sole are flatfish of cooler water. Small baited bottom hooks suit their feeding habit.|Northern sandy seabeds.
hokke|Atka mackerel are an important northern food fish. Their local availability differs between shore schools and offshore grounds.|Cool northern coastal and offshore water.
kurogashiragarei|Cresthead flounder are right-eyed flatfish sought on baited bottom rigs.|Northern coastal sand and mud.
komai|Saffron cod are northern coastal cod relatives. Weather and shoreline access require careful planning in cold seasons.|Cold shallow coastal water.
nishin|Pacific herring arrive in schools. Small hooks and controlled rig handling are useful when fish are concentrated.|Northern coastal bays and harbours.
ezomebaru|White-edged rockfish are known as gaya in Hokkaido. Their small size should not obscure careful species identification.|Cool rocky coastal water.
kibire|Yellowfin seabream resemble black seabream but have yellowish lower fins. Both can use estuary margins.|Brackish channels, tidal flats and bays.
katsuo|Skipjack tuna have dark belly stripes and a streamlined body. Keep retained fish chilled promptly.|Warm offshore schools.
madara|Pacific cod are large cold-water bottom fish. Boat tackle depends on depth and current.|Northern coastal and offshore bottoms.
surumeika|Japanese flying squid are powerful open-water squid, often targeted with boat rigs.|Seasonal coastal and offshore squid grounds.
sunagarei|Sand flounder are small flatfish of northern waters. Identification requires more than simply seeing a sandy-coloured upper side.|Cold sandy seabeds.
suzumedai|Pearl-spot chromis are small schooling damselfish often encountered around rocky shores.|Coastal reefs and structure.
hoshisasanoha|Star-spotted wrasse are patterned reef fish. Several wrasses share local names, so markings and fin shape both matter.|Rocky coastal shallows.
akasasanoha|Red bamboo wrasse are colourful bottom-associated fish. Colour can change with age and sex.|Coastal rocks and seaweed.
kyusen|Kyusen is a wrasse whose colour differs between sexes. It commonly takes small baits intended for other shore fish.|Mixed sand, rocks and weed in shallow water.
sappa|Japanese sardinella are small silver schooling fish often caught on sabiki rigs.|Bays, estuaries and coastal schools.
shimagatsuo|Pacific pomfret have a deep compressed body. Availability to anglers is less predictable than that of resident harbour fish.|Open coastal and offshore water.
kobudai|Asian sheepshead wrasse develop a pronounced forehead in large males. Powerful jaws and rocky cover require sturdy tackle.|Rocky reefs and harbour structure.|Keep fingers away from the jaws and plan a secure landing.
utsubo|Kidako moray shelter in rock crevices and have strong teeth. Unhooking and food preparation require experience.|Warm rocky coastal bottom.|Do not handle the head or mouth. Seek experienced assistance rather than attempting unfamiliar preparation.
kuromaguro|Pacific bluefin tuna range from small juveniles to very large adults. Recreational restrictions and retention requirements can change.|Coastal and offshore pelagic water.|Check current tuna fishing restrictions with the operator before the trip.
browntrout|Brown trout often have dark and red spots. In Japan they occur in selected fisheries and waters, with local management rules.|Cool rivers, lakes and managed fisheries.
koshoudai|Crescent sweetlips have a deep body with markings that change as the fish grows.|Warm rocky and mixed coastal ground.
nenbutsudai|Half-lined cardinalfish are small large-eyed fish often mixed with sabiki catches. Look at the head stripes rather than assuming every small silver fish is a juvenile horse mackerel.|Sheltered rocky shores and harbour structure.
murasoi|A stocky mottled rockfish with small dark spots on the fins and underside. Search accessible shallow rock edges rather than assuming deeper water is better.|Shallow rocky coastlines and stone structures.|Avoid fin and gill-cover spines. Do not climb into unstable blocks or crevices.
takenokomebaru|Known locally as bekkouzoi, this robust rockfish has irregular dark patches on a yellow-brown body. It tries to return to cover when hooked.|Rocky coastal shallows and seaweed edges.|A conservation-sensitive species; check local rules and limit retention. Watch sharp spines.
kuromejina|Onaga-gure has a dark edge to the gill cover and a deeply forked tail. Japanese fukase float fishing presents bait in the current beside rocky reefs.|Warm rocky coasts and offshore reefs.|Use suitable flotation and footwear; follow the ferry skipper's weather and landing decisions.
chidai|Crimson seabream, also called hanadai, resembles red seabream but has a red gill-cover edge and lacks its conspicuous dark tail margin.|Coastal sand and mud near reefs.|Watch the sharp dorsal and pelvic spines. Follow the boat's rig and sinker requirements.
matoudai|John Dory has a very flat body, a round dark flank spot and a protrusible mouth. It sometimes takes live bait intended for flounder.|Coastal shelf bottoms and reef margins.|Long dorsal spines and hard body edges require careful handling with a net and pliers.
akayagara|Red cornetfish has an exceptionally long tubular snout and a thin filament extending from the tail. Its length overstates the amount of edible flesh.|Warm offshore reefs and adjacent sandy bottom.|Plan the landing of this long fish with the skipper; keep the head and tail clear of other anglers.
hachibiki|Japanese rubyfish is a red, streamlined offshore fish with a deeply forked tail. Its flesh is reddish, unlike the white flesh of many similarly coloured fish.|Offshore reef edges and nearby midwater.|Chill retained fish promptly and check local boat tackle requirements.
chigodara|Japanese codling has a chin barbel and a soft body tapering towards the tail. Marine donko is a regional name and should not be confused with freshwater fish sharing that name.|Coastal and offshore bottom habitats, including northern Japanese waters.|Use pliers for deep hooks. Keep the delicate flesh chilled and cook thoroughly.
himeji|Japanese goatfish uses two yellow chin barbels to search the bottom. Oblique bars on the upper tail lobe help identify it; the lower lobe is comparatively plain.|Sandy and shell-strewn coastal bottom.|Handle gently and remove the small bones before cooking.
kanagashira|Redwing searobin has a bony angular head and three detached lower pectoral rays. Its pectoral fin lacks the conspicuous colourful pattern of the larger houbo.|Coastal sand and mud, commonly at shelf depths.|Avoid the hard head and gill-cover spines; use a fish grip and pliers.
hirasuzuki|Blackfin seabass have a deeper body and thicker tail wrist than Japanese seabass. Anglers work minnows through current beside exposed rocks, but breaking waves are never a reason to enter an unsafe ledge.|Warm exposed rocky coasts of central and southern Japan.|Use flotation and appropriate rock footwear. Choose a safe landing point before casting and abandon the trip if waves reach the standing area.
aohata|Yellow grouper have broad dark bands and yellowish fins. Work reef margins and adjoining sand, lifting the rig promptly after it touches bottom.|Coastal reefs and adjoining sand or mud in warmer Japanese waters.|Avoid dorsal spines. Match sinker weight to current and the skipper's instructions.
kue|Longtooth grouper are powerful large reef fish. Young fish show oblique bands that fade with growth. Targeting adults requires dedicated heavy tackle, not a light rockfish outfit.|Warm rocky coastal and offshore reefs.|Book a specialist operator, confirm the complete tackle specification and let experienced staff handle large-fish landing and preparation.
mahata|Sevenband grouper show broad dark bands and a pale rear edge to the tail fin. Adults are targeted with live bait and offshore jigs; small inshore juveniles need a different approach.|Rocky coastal and deeper offshore ground.|Watch fin spines and strong dives into cover. Use a landing net and the skipper's specified tackle.
hedai|Goldlined seabream have fine golden lengthwise lines and a rounded head. Compare the mouth and stripes with black seabream rather than relying on silver body colour alone.|Warm coastal bays, with juveniles also entering estuaries.|Handle dorsal and anal spines carefully. Keep retained fish chilled.
korodai|Adult painted sweetlips have small golden-brown spots; juveniles have striking dark and yellow bands. Large shore fish are targeted on substantial bottom-bait tackle beside mixed rock and sand.|Warm rocky and sandy coastlines, including southern Kansai.|Scout access in daylight, secure the rod and prepare a landing net. Do not attempt unfamiliar rock access at night.
mutsu|Gnomefish have large eyes, a large mouth and sharp teeth. Juveniles occur close to shore, while adult fishing is usually a deep-water boat activity. Colour alone does not reliably separate them from kuromutsu.|Inshore juvenile habitat and deeper offshore bottoms.|Keep fingers away from the teeth. Follow the skipper's sequence for deploying heavy multi-hook rigs.
nibe|Honnibe croaker have oblique rows of small dark marks and lack the prominent gill-cover blotch of shiroguchi. Both may be called ishimochi locally.|Coastal sand and mud, mainly along warmer Pacific shores.|Check behind you before casting and stay clear of breaking waves. Remove small bones before cooking.
souhachi|Pointhead flounder sometimes school above the seabed. In floating-school fishing, use the skipper's indicated depth rather than automatically dropping every rig to the bottom.|Cool northern and Sea of Japan waters, over sand and mud or in midwater schools.|Confirm local minimum-size rules and handle multi-hook rigs carefully. Check the operator's requirements for bait strips and sinkers.
akagarei|Flathead flounder have a relatively large mouth and may show reddish colour on the underside. These cool-water fish are more associated with offshore bottom fishing than casual beach casting.|Cold sandy and muddy offshore bottoms in northern Japan and the Sea of Japan.|Match heavy bottom tackle to depth and current. Keep hooks organised on deck and avoid pulling a snagged rig toward people.
nizadai|Scalpel sawtails are called san-no-ji in Japan, after the dark plates beside the tail. They graze rock surfaces and can pull hard when caught during float fishing.|Warm rocky coasts and reefs.|Do not grip the tail base: its bony plates can cut your hand. Use a landing net and long pliers.
onikasago|The standard Japanese name onikasago refers to this shaggy, mottled scorpionfish. The red offshore fish sold as an onikasago boat-fishing target is commonly izukasago, a separate species.|Warm shallow rocky bottoms.|Venomous spines make whole-fish handling hazardous. Home recipes use professionally prepared fillets.
izukasago|This red scorpionfish is a familiar target of Japanese onikasago boat trips. Keep the bait close to the bottom without dragging, and follow the skipper's sinker and rig requirements.|Offshore sand, mud and mixed rocky bottoms.|Do not grasp the head or fins. Have a professional remove hazardous spines and prepare fillets.
ishigakidai|Spotted knifejaws have black spots and powerful fused teeth for crushing hard prey. Older males may lose obvious spotting and develop pale lips. Heavy rock-fishing tackle and a planned landing position are essential.|Warm rocky coasts and reefs.|Ciguatera poisoning has been linked to this species. Appearance and cooking cannot establish safety; do not eat a self-caught fish on your own judgement.
kiamadai|Golden tilefish are relatives of red and white amadai. Yellow colour is a clue, but compare the head, eyes and tail rather than identifying one from colour alone. Bottom-bait tackle should follow local boat requirements.|Warm offshore sandy and muddy bottoms.|Handle heavy sinkers and hooks carefully, and chill retained fish promptly.
okizayori|Houndfish are large surface predators with both jaws greatly extended. Unlike halfbeaks, the upper jaw is also long. Keep a hooked fish away from people's faces and do not swing it aboard.|Warm coastal and offshore surface waters.|The long jaws and sudden leaps can cause serious injury. Avoid shining bright lights across the water at night.
sake|Chum salmon are the familiar Japanese aki-zake or autumn salmon. Ocean-phase fish are silver; mature fish change colour and jaw shape. Check river and estuary restrictions before planning any fishing.|Northern Japanese coastal waters and spawning rivers.|Do not assume a river or river mouth is open to fishing. Cook wild-caught salmon thoroughly rather than serving it raw.
ginzake|Coho salmon, sold as ginzake, are also stocked by some managed trout fisheries. Small dark spots on the back and upper tail help distinguish them. Compare depth and retrieve speed before repeatedly changing lure colour.|North Pacific origin; Japanese aquaculture and selected managed fisheries.|Follow the fishery's hook and release rules. A caught trout or salmon is not automatically suitable for raw consumption.
kitamakura|A small pointed-snout puffer with wavy brown lines through the eye and body. It may steal bait during filefish fishing. Small size does not make a puffer harmless.|Warm rocky coasts and seaweed beds.|Do not eat or home-prepare this fish. Keep fingers away from its mouth.
komonfugu|A coastal puffer with small pale spots over a darker back. Several similar puffers occur in Japan, so markings must never be used as a home test of edibility.|Coastal sand and mixed rocky bottoms.|Pufferfish preparation requires qualified professionals. No home-preparation recipes are provided.
shimafugu|Yellow fins and wavy pale patterns on a dark back are useful field clues for this large puffer. Its strong teeth may damage hooks and leaders.|Warm inshore and offshore waters.|Do not prepare a whole puffer at home. Use long pliers and keep hands clear of the mouth.
torafugu|Tiger puffers are well known as a restaurant ingredient, but a caught whole fish is not a home-cooking ingredient. A dark blotch behind the pectoral fin is one identification clue.|Japanese coastal bays and offshore waters.|Only qualified professional preparation is appropriate. Confirm the operator's processing arrangements before a fishing trip.
hakofugu|This boxfish has a rigid angular body, a small mouth and small fins. Juvenile and adult colours differ. Familiarity with a regional dish does not make a self-caught boxfish safe to eat.|Warm rocky coasts and seaweed habitats.|Poisoning involving palytoxin-like toxins has been reported. Do not prepare or eat self-caught boxfish.
aobudai|A large blue-green parrotfish with fused beak-like teeth and a prominent adult forehead. Do not group it with edible parrotfishes simply because the names sound similar.|Warm rocky reefs around southern Japan.|Serious poisoning has been linked to this species. Do not eat it or assume cooking removes the risk.
soushihagi|Scrawled filefish have blue scribbled lines, scattered dark spots and a long tail. They must not be confused with edible filefish such as kawahagi or usubahagi.|Warm coastal waters and drifting seaweed.|Do not eat the fish or liver. Photograph it without handling it for identification.
hyoumondako|Blue-lined octopuses can be small enough to hide under shells or rocks. Blue markings may become vivid when disturbed and may be inconspicuous at rest.|Shallow rocky shores and tide pools.|Do not touch, collect or provoke one. A bite can be life-threatening: call Japan's emergency number 119 immediately.
hiiragi|A small silver ponyfish often taken on bottom bait rigs. Its protrusible mouth and slimy, compressed body distinguish it from juvenile bream. Use short bait on a small hook.|Shallow bays, harbours and estuaries over sand or mud.|Watch fin spines and hooks. Keep the catch chilled and check the identification before preparing it.
nezumigochi|This dragonet is known as gaccho in Osaka and megochi in many fishing contexts. It has a small mouth and cheek spines; it is not the larger flathead called magochi.|Sandy and muddy seabeds in sheltered bays.|Watch fin spines and hooks. Keep the catch chilled and check the identification before preparing it.
anahaze|Despite its Japanese name, anahaze is a sculpin, not a true goby. A large mouth and variable mottled colour suit its ambush feeding around seaweed and rocks.|Rocky shallows and seaweed beds near the shore.|Watch fin spines and hooks. Keep the catch chilled and check the identification before preparing it.
kujime|A shallow-water greenling often confused with ainame. One lateral line and a rounded tail edge are useful distinguishing features. Small bait and hooks suit its relatively small mouth.|Shallow rocky reefs and seaweed-covered shorelines.|Watch fin spines and hooks. Keep the catch chilled and check the identification before preparing it.
ginpo|A slender marine gunnel that lives in narrow rocky crevices. It is not an eel. Its pale tail rim and dark triangular dorsal markings help identify it; deboned strips are used for tempura.|Rock crevices and sheltered stony shallows.|Watch fin spines and hooks. Keep the catch chilled and check the identification before preparing it.
yamatokamasu|A slender barracuda also called mizukamasu. Compare pelvic and first dorsal fin positions with red barracuda rather than relying on colour. Search different retrieve depths as schools pass.|Coastal bays and reefs, following schools of small fish.|Watch fin spines and hooks. Keep the catch chilled and check the identification before preparing it.
tenjikudai|A small cardinalfish with pale vertical bars, known as nebuto in parts of the Seto Inland Sea. It differs from the horizontally striped nenbutsudai already in this encyclopedia.|Sheltered coastal bays over sandy or muddy bottoms.|Watch fin spines and hooks. Keep the catch chilled and check the identification before preparing it.
tsumuburi|Rainbow runner are slender offshore jacks with blue and yellow side stripes. They may accompany floating structure and take casting lures or jigs in midwater.|Warm offshore waters around floating cover and current lines.|Watch fin spines and hooks. Keep the catch chilled and check the identification before preparing it.
meaji|Bigeye scad have conspicuously large eyes with an adipose eyelid. They school in warm coastal water and can be caught with sabiki rigs or light lures.|Warm coastal waters, harbours and bays.|Watch fin spines and hooks. Keep the catch chilled and check the identification before preparing it.
oonibe|A large croaker pursued from surf beaches and boats. It is a separate species from nibe. Landing space, line capacity and wave conditions matter as much as lure choice.|Coastal surf zones, estuaries and deeper sandy or muddy grounds.|Watch fin spines and hooks. Keep the catch chilled and check the identification before preparing it.
ibodai|Known as ebodai, shizu or uoze, this rounded silver butterfish has a small mouth and dark shoulder patch. Gentle retrieval helps prevent tearing the mouth.|Coastal and offshore sandy or muddy grounds.|Watch fin spines and hooks. Keep the catch chilled and check the identification before preparing it.
chikamekintoki|A deep-bodied red bigeye with unusually long pelvic fins. It is not kinmedai. Boat bottom rigs and jigs should be kept clear of the reef rather than dragged through it.|Deeper reefs and rocky offshore grounds.|Watch fin spines and hooks. Keep the catch chilled and check the identification before preparing it.
yumekasago|A red bottom-associated rockfish encountered on deep-water bait rigs. The dark throat can lead to the nickname nodoguro, but this is not blackthroat seaperch, akamutsu.|Deep coastal and offshore seabeds, generally reached from a boat.|Watch fin spines and hooks. Keep the catch chilled and check the identification before preparing it.
akaisaki|Redbar anthias are not red versions of isaki. Sex-related colour differences are common; males show dark upper-body markings. They are encountered around offshore reefs.|Offshore rocky grounds and reefs.|Watch fin spines and hooks. Keep the catch chilled and check the identification before preparing it.
namazu|Japanese catfish are surface-lure targets in slow rivers. Wait for the weight of the fish rather than striking at the splash. Check access and footing in daylight before night fishing.|Slow-flowing rivers, canals and still waters in Japan.|Follow local fishing rules. Do not move live fish between waters. Cook freshwater fish thoroughly.
ugui|Japanese dace are common river fish known by several regional names including haya. Drift a small float naturally through current seams. Spawning colour differs from the usual silver appearance.|Rivers and lakes; some populations also enter coastal waters.|Follow local fishing rules. Do not move live fish between waters. Cook freshwater fish thoroughly.
ginbuna|Silver crucian carp are familiar small-pond float-fishing targets. They lack carp barbels. Some crucian carp cannot be identified confidently from body depth alone; avoid moving live fish between waters.|Ponds, canals, lakes and slow river margins.|Follow local fishing rules. Do not move live fish between waters. Cook freshwater fish thoroughly.
kawamutsu|Dark chub have a broad dark stripe along the side. Quiet shaded pools and slow edges can be more productive than exposed fast runs. Use small hooks and drift the bait naturally.|Clear streams and river margins with cover and moderate flow.|Follow local fishing rules. Do not move live fish between waters. Cook freshwater fish thoroughly.
biwamasu|Biwa salmon are endemic to Lake Biwa. Boat fishing is regulated under a seasonal approval system. A licensed, approved guide is the practical starting point; check the current rules rather than assuming open access.|Lake Biwa and its tributaries; adults feed in the lake.|Follow local fishing rules. Do not move live fish between waters. Cook freshwater fish thoroughly.
himemasu|Kokanee are landlocked sockeye salmon. Silver lake-phase fish look very different from red spawning fish. Follow each lake’s season, bag limit, hook and bait rules, and keep track of the school’s depth.|Cold lakes with locally managed fishing seasons.|Follow local fishing rules. Do not move live fish between waters. Cook freshwater fish thoroughly.
hamafuefuki|Known as taman in Okinawa and tamami around Kansai, this emperor feeds over mixed sand and reef. Plan how to stop the first run and land the fish before casting a bottom bait.|Japanese coastal waters; region and depth differ by species.|Handle fin spines, teeth and hooks carefully. Chill fish promptly and use properly handled sashimi-grade fish for raw recipes.
fuedai|Star snapper has a pale spot high on the rear flank. The local name shibudai can cover different snappers, so identify the fish rather than relying on its nickname.|Japanese coastal waters; region and depth differ by species.|Handle fin spines, teeth and hooks carefully. Chill fish promptly and use properly handled sashimi-grade fish for raw recipes.
yokosujifuedai|A coastal snapper with a dark lengthwise band that broadens towards the rear. The markings fade with growth; juveniles may enter sheltered brackish water.|Japanese coastal waters; region and depth differ by species.|Handle fin spines, teeth and hooks carefully. Chill fish promptly and use properly handled sashimi-grade fish for raw recipes.
kurohoshifuedai|Russell’s snapper resembles several other black-spotted snappers. A single flank spot is not enough for safe identification. Use correctly identified food-grade fish for cooking; heat does not remove ciguatoxins.|Japanese coastal waters; region and depth differ by species.|Do not eat unidentified reef fish. Cooking and freezing do not remove ciguatoxins. Use verified food-grade fish.
tamagashira|A small red bottom fish sometimes caught while targeting amadai. Look for reddish crossbars, a large eye and a forked tail without the trailing filament of threadfin bream.|Japanese coastal waters; region and depth differ by species.|Handle fin spines, teeth and hooks carefully. Chill fish promptly and use properly handled sashimi-grade fish for raw recipes.
chairomaruhata|Orange-spotted grouper live around bottom structure, with juveniles also using sheltered brackish habitats. Their first dive calls for appropriate tackle, not a small-rockfish outfit. Recipes assume verified food-grade fish.|Japanese coastal waters; region and depth differ by species.|Do not eat unidentified reef fish. Cooking and freezing do not remove ciguatoxins. Use verified food-grade fish.
kasumiaji|Adult bluefin trevally develop blue fins and scattered blue-black spots. Juveniles are among the small jacks called mekki. Scale tackle to the fish: a harbour juvenile and an adult reef fish are very different targets.|Japanese coastal waters; region and depth differ by species.|Handle fin spines, teeth and hooks carefully. Chill fish promptly and use properly handled sashimi-grade fish for raw recipes.
gingameaji|Bigeye trevally have a conspicuous eye and a small dark mark high on the gill cover. Juveniles are popular mekki targets; adult schools in southern waters require much stronger tackle.|Japanese coastal waters; region and depth differ by species.|Handle fin spines, teeth and hooks carefully. Chill fish promptly and use properly handled sashimi-grade fish for raw recipes.
itohikiaji|Young African pompano have a diamond-shaped body and long trailing dorsal and anal rays. Adults lose the exaggerated filaments. Support the body when unhooking and photographing the fish.|Japanese coastal waters; region and depth differ by species.|Handle fin spines, teeth and hooks carefully. Chill fish promptly and use properly handled sashimi-grade fish for raw recipes.
usumebaru|One of the offshore rockfish called okimebaru. Irregular dark patches on the upper flank help distinguish it from plainer species. On a boat, reproduce the skipper’s instructed depth rather than dragging the rig over rock.|Japanese coastal waters; region and depth differ by species.|Handle fin spines, teeth and hooks carefully. Chill fish promptly and use properly handled sashimi-grade fish for raw recipes.
hatsume|A small deep-water rockfish from northern and Sea of Japan waters. It lacks the strong upper-flank blotches of usumebaru and has a forked tail. Boat tackle and sinker weights must match the skipper’s instructions.|Japanese coastal waters; region and depth differ by species.|Handle fin spines, teeth and hooks carefully. Chill fish promptly and use properly handled sashimi-grade fish for raw recipes.
shimazoi|A northern rockfish with pale longitudinal stripes on a brown body. Work a lure just above rocky cover and lift the fish clear promptly after a bite.|Japanese coastal waters; region and depth differ by species.|Handle fin spines, teeth and hooks carefully. Chill fish promptly and use properly handled sashimi-grade fish for raw recipes.
matsukawa|Barfin flounder have bold dark fin bars and a rough eyed side. Stock enhancement and minimum-size release rules apply in parts of Hokkaido; check the current local direction before keeping one.|Japanese coastal waters; region and depth differ by species.|Handle fin spines, teeth and hooks carefully. Chill fish promptly and use properly handled sashimi-grade fish for raw recipes.
babagarei|Often sold as nametagarei, this thick flatfish has a small mouth and a notably slimy surface. Gentle bottom bait presentations suit it, and simmering is a familiar way to cook it.|Japanese coastal waters; region and depth differ by species.|Handle fin spines, teeth and hooks carefully. Chill fish promptly and use properly handled sashimi-grade fish for raw recipes.
numagarei|Starry flounder use estuaries and can enter fresh water. Many Japanese fish are left-eyed, so the usual left-flounder/right-righteye shortcut is unreliable; check the dark fin bars and rough skin as well.|Japanese coastal waters; region and depth differ by species.|Cook freshwater and estuary fish thoroughly. Follow local retention rules and never move fish to another water.
nigoi|Barbel steed search the riverbed with a projecting snout and downward-facing mouth. They can take bait or lures. Similar Hemibarbus species may need closer examination, so avoid overconfident photo-only identification.|Japanese rivers or lakes; consult local fishery rules.|Cook freshwater and estuary fish thoroughly. Follow local retention rules and never move fish to another water.
kamatsuka|A sand-dwelling gudgeon with an inferior mouth and barbels. The Japanese group includes recently separated species, so locality and detailed features matter. Present tiny bait on the bottom rather than midwater.|Japanese rivers or lakes; consult local fishery rules.|Cook freshwater and estuary fish thoroughly. Follow local retention rules and never move fish to another water.
motsugo|Called kuchiboso, this tiny fish has an upturned mouth and no barbels. A very small hook and bait are more useful than forceful striking. It is well suited to observing small float movements.|Japanese rivers or lakes; consult local fishery rules.|Cook freshwater and estuary fish thoroughly. Follow local retention rules and never move fish to another water.
tamoroko|A small barbel-bearing cyprinid of slow rivers and ponds. It is stockier than honmoroko, while motsugo has no barbels. Fish tiny bait near the bottom along quiet banks.|Japanese rivers or lakes; consult local fishery rules.|Cook freshwater and estuary fish thoroughly. Follow local retention rules and never move fish to another water.
honmoroko|Honmoroko are slender Lake Biwa cyprinids valued as food. They school in the lake and approach shore to spawn. Check current protected areas and dates before fishing; plain grilling with vinegar miso is a familiar serving style.|Japanese rivers or lakes; consult local fishery rules.|Cook freshwater and estuary fish thoroughly. Follow local retention rules and never move fish to another water.
muroaji|Amberstripe scad have a slender body and small finlets behind the dorsal and anal fins. Muroaji can also be used as a broader group name, so distinguish the actual species. Chill food fish promptly rather than leaving them in the live-bait bucket.|Japanese coastal waters; region and depth differ by species.|Handle fin spines, teeth and hooks carefully. Chill fish promptly and use properly handled sashimi-grade fish for raw recipes.
umeiro|Yellowtail blue snapper have a blue-violet body and yellow upper rear flank and tail. They are not takabe or yellow-and-blueback fusiliers. Present bait in the chum trail at the boat skipper’s instructed depth.|Japanese coastal waters; region and depth differ by species.|Handle fin spines, teeth and hooks carefully. Chill fish promptly and use properly handled sashimi-grade fish for raw recipes.`;
export type FishEnglish={overview:string;habitat:string;safety?:string};
export const englishFish:Record<string,FishEnglish>=Object.fromEntries(rows.split('\n').map(row=>{const [slug,overview,habitat,safety]=row.split('|');return [slug,{overview,habitat,safety}]}));
