export type GuideEnglish={title:string;summary:string;method?:string;fish?:string;sections:{heading:string;body:string}[]};
export const englishGuides:Record<string,GuideEnglish>={
 'tairaba-bottom-contact':{title:'Tai-raba for red seabream: touch bottom, then keep winding',summary:'A visitor’s guide to a Japanese boat-fishing method built around controlled bottom contact and a steady retrieve.',method:'tai-rubber',fish:'madai',sections:[
 {heading:'Ask the boat before buying tackle',body:'The skipper can specify head weights, braid size and the depth range. Tai-raba heads are sold in grams, while some other Japanese sinkers use go numbers; do not interchange the numbers. Rental tackle can be a sensible way to try the method before selecting your own rod.'},
 {heading:'Avoid leaving the head on bottom',body:'Lower with enough control to recognise when the head touches down. Begin winding promptly so the skirt moves off the seabed rather than lying among snags. If contact is unclear, ask whether a heavier head is needed instead of simply feeding more line.'},
 {heading:'Keep the retrieve consistent',body:'Choose a comfortable speed and wind through the instructed layer. Initial taps are not a reason for a violent strike. Continue winding until the rod loads, maintaining tension as the small hooks engage. Change one element of speed or skirt presentation at a time.'},
 {heading:'Land, then check the rig',body:'Let the crew guide the fish into the net. Check the leader where it joins the head and inspect hook points before the next drop. Chill retained fish promptly, and discuss release or retention with the operator when planning the trip.'}]},
 'aji-sabiki-depth':{title:'Sabiki fishing in Japan: find the horse mackerel’s feeding depth',summary:'A practical first session at a permitted pier: prepare a short rig, release small amounts of bait and repeat the depth that produces bites.',method:'sabiki',fish:'aji',sections:[
 {heading:'Before leaving',body:'Choose a managed fishing park or another location with clearly permitted access. Check opening times, bait restrictions and whether casting is allowed. A tackle shop can help you choose hooks for the size of horse mackerel currently being targeted; a large hook is not automatically better.'},
 {heading:'Search vertically',body:'Lower the rig under the rod tip, not across neighbouring lines. Near bottom, recover a little line so the sinker does not lie among rocks. Give the basket a small lift, then pause. Search progressively higher if there are no bites. Note the line length or reel turns at the productive layer.'},
 {heading:'When it is not working',body:'First check whether fish are present. If other anglers are catching, compare depth and bait release rather than immediately changing the entire rig. Replace a damaged rig, reduce oversized bait releases and use smaller hooks when small fish cannot take the current ones.'},
 {heading:'Landing and packing up',body:'Keep the rod movement controlled: multiple hooks can catch clothing and fingers. Have pliers, a fish grip and an ice-filled cooler ready before fishing. Bag clipped line and bait packaging; rinse only where the venue permits.'}]},
 'tachiuo-tenya-action':{title:'Tachiuo tenya: work the depth, recognise the bite, then set the hook',summary:'Learn the sequence used on Japanese hairtail boats without confusing a small preliminary tap with a committed take.',method:'tachiuo-tenya',fish:'tachiuo',sections:[
 {heading:'Book with the right questions',body:'Ask for the meeting port, boarding time, rental availability, bait, tenya weight and line requirements. A 40-go tenya is not a 40-gram lure. Boats coordinate weight and line to reduce tangles, so follow the operator rather than an online generic specification.'},
 {heading:'Keep the bait straight',body:'Attach the sardine or prepared bait firmly along the head, leaving the hook point clear. A bent bait can spin. Check it after missed bites; damage concentrated at one end helps you decide whether to pause longer or change the presentation.'},
 {heading:'A repeatable first drift',body:'Lower to the skipper’s indicated layer, then alternate controlled lifts, slow winding and still pauses. Watch for both taps and an unexpected reduction in load. Stay within the instructed depth: following fish lower than everyone else can create tangles.'},
 {heading:'Finish safely',body:'Set the hook once the take develops rather than striking wildly at every vibration. Keep tension during retrieval. Use long pliers and a grip around the mouth; hairtail teeth remain sharp after the fish stops moving.'}]},
 'shore-jigging-jig-weight':{title:'Choosing a shore jig: control depth before chasing distance',summary:'Use the rod rating, wind, current and landing route to select a manageable jig, then search one layer at a time.',method:'shore-jigging',fish:'buri',sections:[
 {heading:'Choose the venue first',body:'A long cast is useful only where casting is allowed and the backcast is clear. Check the landing height, net length and exit route before assembling tackle. A rocky headland is not an appropriate first stop in swell simply because fish have been reported there.'},
 {heading:'Choose a controllable weight',body:'Read the rod’s casting range. Increase weight only when necessary to maintain contact in current or wind, within that range. On shallow water a heavy jig may snag before you can begin the retrieve. A tackle shop can help match a beginner setup to the actual venue.'},
 {heading:'Search systematically',body:'Start with a known sink count, then repeat the same retrieve rhythm. If nothing responds, vary depth before changing colour and speed together. Pay attention to baitfish and current edges, but do not cast into birds or across another angler’s line.'},
 {heading:'When a fish takes',body:'Maintain pressure without locking the drag. Move only on secure footing and guide the fish towards the planned landing point. Replace a leader that feels rough after touching structure. Stop when worsening wind or waves remove the safe landing route.'}]},
 'eging-shakuri-count':{title:'Eging in Japan: the pause matters as much as the lift',summary:'Give a squid jig room to sink naturally and learn what the line tells you during the fall.',method:'eging',fish:'aoriika',sections:[
 {heading:'Choose the sinking pattern',body:'An egi is a weighted squid jig, not a baited hook. Its size and sinking speed affect how long it stays above rocks and weed. Start with a jig matched to the rod and a venue with enough depth; do not insist on bottom contact in very shallow weed.'},
 {heading:'Lift, then watch',body:'After a controlled cast, allow the jig to sink. Use several manageable lifts to move it, then pause. The number of lifts is not a universal rule. Wind can bow the line and hide movement, so recover excessive slack without dragging the jig unnaturally.'},
 {heading:'Recognise a take',body:'Look for a sideways line movement, a fall that stops early or a change in resistance. Lift firmly to engage the hook crown, then keep pressure. Squid can release a jig during slack line, especially near the landing point.'},
 {heading:'Respect the shore',body:'Prepare a landing net rather than lifting a heavy squid on thin line. Avoid shining lights at neighbours or leaving ink and packaging where people walk. Check any local seasonal squid protection and access rules before the trip.'}]},
 'kisu-retrieve-speed':{title:'Japanese whiting: slow down and read the sand',summary:'Short casts, small baits and a controlled stop-and-draw retrieve make a first whiting session easier to understand.',method:'choinage',fish:'kisu',sections:[
 {heading:'A simple setup',body:'Use a light rod rated for the sinker and a short trace that you can cast safely. A bait shop can supply small marine worm baits and suitable hooks. More hooks make tangles harder to manage; begin with a rig you can untangle and rebait easily.'},
 {heading:'Cover a small fan',body:'Cast onto clear sand, take up slack and draw the rig a short distance. Pause and feel for taps. Change direction or distance gradually. A nearby trough can hold fish, so do not skip the water close to shore in pursuit of a long cast.'},
 {heading:'Read missed bites',body:'Recover the bait after repeated taps. Bait that is too long or balled around the hook can be pulled without hooking a fish. If the sinker repeatedly buries in soft sand, shorten the pause and keep the next movement gentle.'},
 {heading:'Keep the session comfortable',body:'Avoid swimming areas and give walkers a clear route behind you. Carry shade, drinking water, a cooler and rubbish bag. Stop when casting space becomes crowded, even if fish are still biting.'}]},
 'kasago-ana-rig':{title:'Kasago crevice fishing without climbing into dangerous gaps',summary:'Use a short rig from stable footing and separate a bite from a snag before pulling harder.',method:'ana',fish:'kasago',sections:[
 {heading:'Safe access comes first',body:'Crevices in a permitted pier edge are different from gaps between wave-breaking blocks. Do not climb down between concrete blocks or follow a map pin into a restricted breakwater. Choose a position with a clear route back and no wave wash.'},
 {heading:'Present a small bait',body:'Attach a compact bait to a weighted single-hook rig. Lower it into an opening and keep light contact. Large loose bait may be stripped without a clear take and can catch on the surrounding structure.'},
 {heading:'Bite or snag?',body:'A fish may give repeated movement, while a snag remains fixed. Lift smoothly when the fish loads the rod, then keep it away from cover. If the rig sticks, change the angle gently; do not pull with your face in the line of the hook.'},
 {heading:'Limit what you keep',body:'Rockfish can be vulnerable to repeated harvest at a small spot. Follow local size and retention rules, release small fish carefully where permitted and move on rather than removing every fish from one opening. Use pliers around fin spines.'}]},
 'chinu-field-notes':{title:'Black seabream on a float: connect depth, bait and current',summary:'A practical introduction to fukase fishing for chinu, including what to adjust when the hook bait comes back untouched.',method:'fukase',fish:'chinu',sections:[
 {heading:'Understand the drift',body:'Fukase uses a lightly weighted hook bait, often accompanied by small amounts of groundbait. First check that groundbait is allowed. The float shows surface movement, but the hook bait may travel differently below it.'},
 {heading:'Set a starting depth',body:'Use a depth appropriate to the bottom and feeding layer, then watch the drift over several casts. Make small adjustments to the float stop or shot placement. Do not repeatedly fish deeper without knowing whether the hook is snagging.'},
 {heading:'Diagnose the bait',body:'Untouched bait can mean the fish are elsewhere or the bait is travelling outside the feeding stream. Missing bait can mean small fish are intercepting it. Change one factor at a time so you can tell whether depth, weight or drift improved the presentation.'},
 {heading:'Before the first run',body:'Set the drag and choose a landing position before feeding the swim. Black seabream can turn towards structure after a take. Keep a controlled rod angle and use a net rather than attempting to lift a heavy fish onto a high wall.'}]},
 'saba-sabiki-cooling':{title:'Catching mackerel from a pier: manage the run and cool the catch',summary:'A short practical checklist for schooling mackerel, crowded piers and immediate chilling.',method:'sabiki',fish:'saba',sections:[
 {heading:'Keep the rig manageable',body:'Mackerel often move horizontally when hooked. Choose a rig and rod length that let you lift fish without sweeping hooks through the crowd. Ask the venue whether groundbait and casting are permitted.'},
 {heading:'Find the school’s layer',body:'Start with controlled vertical drops and note the depth that produces bites. A passing school may leave quickly; no rig change can guarantee it returns. Use small measured bait releases rather than emptying a large quantity at once.'},
 {heading:'Land before lines cross',body:'Guide the fish away from neighbouring rigs with steady pressure. A multi-hook rig with several moving fish is harder to control, so prepare a grip and pliers beforehand. Put hooks somewhere safe before opening the cooler.'},
 {heading:'Chill promptly',body:'Bring enough ice and chill retained mackerel promptly. Do not leave a catch in the sun while continuing to fish. Later cooking does not remove histamine already formed. If food handling has been uncertain, do not assume appearance or smell proves safety.'}]},
 'suzuki-field-notes':{title:'Japanese seabass: work a current seam, not just a casting distance',summary:'Choose a lure layer, control line through the drift and prepare for head shakes at the landing point.',method:'seabass-lure',fish:'suzuki',sections:[
 {heading:'Read the venue',body:'Look for a change in current, depth or structure from safe dry footing. Estuaries and harbours can have vessel traffic, restricted walls and difficult exits. Wading needs specialised judgement; it is not required for a first seabass session.'},
 {heading:'Match the lure layer',body:'Use a lure that works at the depth you intend to cover. Cast across a seam and feel how the current changes its resistance. A lure moving too fast or digging into bottom may never pass naturally through the feeding layer.'},
 {heading:'Make changes you can understand',body:'Repeat a few casts at the same angle and retrieve speed, then change one factor. Check the hook points and leader after touching structure. A lack of bites does not prove the fish need a different colour.'},
 {heading:'Keep tension at the finish',body:'Seabass shake their heads and may jump near the surface. Maintain controlled tension without overloading the rod. Have the net within reach before hooking a fish; do not lean over a high wall while trying to reach a lure.'}]},
 'osakabay-september-fish':{title:'Fishing in Osaka Bay in September: a first-trip plan',summary:'Compare a managed pier session with a boat trip, then check local access and recent conditions before booking.',sections:[
 {heading:'Choose the experience',body:'For a first shore trip, a managed fishing park can make opening times, access and facilities easier to confirm. Horse mackerel and mackerel are possible seasonal targets where schools are present. Offshore hairtail trips are a different activity with specific tackle and boarding instructions.'},
 {heading:'Use the map as a shortlist',body:'Filter for Osaka or nearby Hyogo and the method you want to use. A harbour marker is not blanket permission to fish every wall. Read the location’s reference links and confirm the permitted fishing section, parking and return transport.'},
 {heading:'Book a boat clearly',body:'Ask which port to meet at, whether rental tackle and bait are included, and what cancellation conditions apply to bad weather. Show the Japanese method name—such as タチウオテンヤ—when language is a barrier. Match the operator’s sinker and line requirements.'},
 {heading:'Plan for heat and changeable weather',body:'Bring water, sun protection, a suitable life jacket and a way to keep fish cold. Seasonal targets are not a current catch forecast. Check weather and fresh local reports before travelling, and have a shore-based alternative if the boat cancels.'}]},
 'tokyobay-autumn-fish':{title:'Fishing in Tokyo Bay in autumn: shore, estuary or boat?',summary:'Choose the setting before the species and check the rules of each urban waterfront.',sections:[
 {heading:'Urban shore fishing',body:'Managed sea-fishing parks and designated waterfront sections are useful starting points. Opening hours, permitted tackle and casting restrictions differ. A public promenade does not necessarily permit fishing; read the signs and use the official venue information.'},
 {heading:'Estuary options',body:'Goby fishing with a small baited rig can be approachable in suitable permitted areas. Seabass lure fishing covers a different layer and often needs more casting space. Avoid shipping channels, bridges with restricted access and unfamiliar tidal mud.'},
 {heading:'Boat options',body:'Tokyo Bay boats offer different seasonal targets. Ask the operator about rentals, bait, the exact meeting location and whether instructions are available in a language you understand. Arrive with the specified tackle rather than assuming your shore outfit will work.'},
 {heading:'Connect the trip',body:'Use the map to compare facilities and transport, then open the relevant fish and method pages. Take spare hooks, pliers, a rubbish bag and a cooler if keeping fish. Published seasonal information is a planning aid, not a promise of current catches.'}]},
 'wakayama-autumn-fish':{title:'Fishing in Wakayama: plan around coast, waves and access',summary:'Wakayama offers harbours, rocky shores and boat grounds; choose a venue that matches your experience.',sections:[
 {heading:'Start with the right shoreline',body:'A permitted harbour edge or managed facility is easier for a first visit than a remote rocky headland. Rocky-shore fishing needs appropriate footwear, a life jacket and a clear understanding of the return route. A calm-looking inlet can still receive swell.'},
 {heading:'Match method to access',body:'Eging targets squid around suitable coastal structure; short-cast bottom rigs suit clear sand; offshore jigging and tenya require a boat. Confirm local bait, casting and access restrictions before carrying tackle onto the shore.'},
 {heading:'Use local knowledge',body:'Ask a tackle shop or boat operator about the current conditions, but distinguish a recent report from guaranteed availability. Boat sinker and line specifications are coordinated across anglers. Some shore rocks require a ferry and cannot be reached on foot.'},
 {heading:'Prepare the return',body:'Check the last ferry or public transport service and leave remote ground before conditions deteriorate. Carry all line and bait packaging out. If a route, sign or closure is unclear, choose another location rather than interpreting a map marker as permission.'}]}
};
