import styles from './catalog.module.css';
import {pageSharing} from '@/lib/page-sharing';
import {fishMatchesSearch} from '@/lib/fish-aliases';
import Link from 'next/link';
import {sortFishCatalog,fishSortOptions,parseFishSort} from '@/lib/fish-catalog-sort';
import {fishCatalog} from '@/lib/fish-registry';
import FishThumbnail from '@/components/FishThumbnail';
import FishCollectionPanel from '@/components/FishCollectionPanel';
export const metadata=pageSharing("/fish","魚図鑑｜名前・別名・危険魚から探す","釣れた魚の特徴・見分け方・危険部位から釣り方・料理まで調べるUOLINKの魚図鑑。");
export default async function Page({searchParams}:{searchParams:Promise<{q?:string|string[];hazard?:string;water?:string;sort?:string}>}){const params=await searchParams;const q=typeof params.q==='string'?params.q:'';const sort=parseFishSort(params.sort);const results=sortFishCatalog(fishCatalog.filter(f=>fishMatchesSearch(f,q??'')&&(!params.water||f.waterTypes?.includes(params.water as 'sea'|'brackish'|'fresh')||(!f.waterTypes&&params.water==='sea'))&&(params.hazard!=='1'||!!f.hazard)),sort);return <div className={`section pageTop ${styles.catalog}`}><div className={`pageHero ${styles.hero}`}><span>FISH ENCYCLOPEDIA</span><h1>魚図鑑</h1><p>魚の名前・別名で検索し、特徴と見分け方を確認できます。知らない魚は触る前に危険情報を確認してください。</p></div><form key={[q,params.water??'',sort,params.hazard??''].join('|')} className="filterBar" action="/fish"><input aria-label="魚の名前・別名を検索" name="q" defaultValue={q??''} placeholder="カレイ・カツオ・ガシラでも検索"/><label>生息環境<select name="water" defaultValue={params.water??''}><option value="">すべて</option><option value="sea">海水</option><option value="brackish">汽水</option><option value="fresh">淡水</option></select></label><label>並び順<select name="sort" defaultValue={sort}>{fishSortOptions.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label><label><input type="checkbox" name="hazard" value="1" defaultChecked={params.hazard==='1'}/> 危険魚のみ</label><button type="submit">検索・並べ替え</button><Link href="/fish">条件を解除</Link></form><div className={styles.afterSearch}><Link href="/identify" className={styles.identify}>📷 写真から魚を調べる →</Link><span>名前・別名・仲間の呼び名で検索</span></div><FishCollectionPanel/><p role="status">{results.length}魚種{q&&`：「${q}」の検索結果`}</p>{!results.length&&<p>一致する魚がありません。名前を短くして検索してください。</p>}<div className="fishGrid large">{results.map(f=><a key={f.slug} className="fishCard" href={`/fish/${f.slug}`}><div className="fishThumb fishThumbArt" style={{'--accent':f.accent} as React.CSSProperties}><FishThumbnail fish={f}/><span>{f.season}</span></div><h3>{f.name}</h3>{f.hazard&&<b style={{color:"#9e321e",padding:"0 16px"}}>WARNING · 素手で触らない</b>}<p>{f.scientific}</p><div className="chips">{f.methods[0]&&<span>{f.methods[0]}</span>}<span>{f.areas[0]}</span>{f.kids&&<span>親子向け</span>}</div></a>)}</div></div>}
