import {notFound} from 'next/navigation';
import Link from 'next/link';
import FishArt from '@/components/FishArt';
import LaunchFishExtras from '@/components/LaunchFishExtras';
import TachiuoMedia from '@/components/TachiuoMedia';
import {fish,getFish} from '@/lib/data';
import {fishDetails} from '@/lib/fish-details';
import t from './tachiuo.module.css';

export function generateStaticParams(){return fish.map(f=>({slug:f.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const f=getFish(slug);return {title:f?`${f.name}｜魚図鑑`:'魚図鑑',description:f?.desc}}

function TachiuoPage(){
 const f=getFish('tachiuo')!;const d=fishDetails.tachiuo;const months=Array.from({length:12},(_,i)=>i+1);
 return <div className={t.page}><section className={t.hero}>
  <div className={t.crumb}><Link href="/">ホーム</Link>　›　<Link href="/fish">魚図鑑</Link>　›　タチウオ</div>
  <div className={t.top}><aside className={t.summary}><h1>タチウオ</h1><div className={t.en}>Largehead hairtail</div><button className={t.sound}>🔊 魚の解説を聞く</button><div className={t.facts}><div className={t.row}><span>分類</span><b>{d.family} {d.genus}</b></div><div className={t.row}><span>学名</span><b><i>{f.scientific}</i></b></div><div className={t.row}><span>別名</span><b>{d.aliases.join('・')}</b></div><div className={t.row}><span>体長</span><b>{f.size}</b></div><div className={t.row}><span>旬</span><b>{f.season}</b></div><div className={t.row}><span>難易度</span><b className={t.stars}>★★★☆☆</b></div><div className={t.row}><span>危険度</span><b className={t.stars}>★★★☆☆</b></div></div><div className={t.tags}><span>食べて美味しい</span><span>大阪湾の人気魚</span><span>船釣り対応</span></div></aside>
  <TachiuoMedia/><div className={t.tools}><span>♡<small>お気に入り</small></span><span>🎣<small>釣った！</small></span><span>↗<small>シェア</small></span><span>▣<small>保存</small></span></div></div>
  <div className={t.cards}><article className={t.card}><h3>▣ 特徴</h3><div className={t.feature}><p>{f.desc} {d.body}</p><div className={t.dangerArt}></div></div></article><article className={t.card}><h3>🐟 生態</h3><div className={t.list}><div><span>生息域</span><b>{d.habitat}</b></div><div><span>水深</span><b>{f.depth}</b></div><div><span>エサ</span><b>{d.diet}</b></div><div><span>行動</span><b>{d.behavior}</b></div><div><span>寿命</span><b>{d.lifespan}</b></div></div></article><article className={t.card}><h3>🎣 釣り方</h3><div className={t.methods}><Link href="/methods/tachiuo-tenya">テンヤ釣り <span>›</span></Link><Link href="/methods">ジギング <span>›</span></Link><Link href="/methods">ウキ釣り <span>›</span></Link><Link href="/methods">引き釣り <span>›</span></Link></div></article><article className={`${t.card} ${t.foodCard}`}><h3>🍽 食べ方</h3><div className={t.foodPhoto}><img src="/images/fish/tachiuo-food.jpg" alt="タチウオ料理 塩焼き・刺身・炙り・天ぷら・ムニエル"/></div><p>{d.taste}</p><div className={t.foodTags}>{d.cooking.map(x=><span key={x}>{x}</span>)}</div></article><article className={t.card}><h3>◷ 釣れる時期</h3><div className={t.months}>{months.map(m=><span key={m} className={f.months.includes(m)?t.on:''}>{m}月</span>)}</div></article></div>
 </section><section className={t.cta}><div><h2>この魚を釣ってみよう！</h2><p>釣り場・釣り方・釣具をUOLINKでそのまま確認できます。</p></div><Link href="/spots">📍 おすすめの釣り場</Link><Link href="/gear">🧰 必要な釣具</Link><Link href="/methods/tachiuo-tenya">🎣 テンヤの詳細</Link><Link className={t.game} href="/game">🎮 ゲームで練習</Link></section><section className={t.lightSection}><LaunchFishExtras slug="tachiuo" name="タチウオ"/></section></div>
}

export default async function Page({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const f=getFish(slug);if(!f)notFound();if(slug==='tachiuo')return <TachiuoPage/>;const d=fishDetails[slug];
 return <div className="section pageTop"><div className="breadcrumb"><Link href="/">ホーム</Link> / <Link href="/fish">魚図鑑</Link> / {f.name}</div><section className="fishDetailHero"><div className="fishTitle"><span>FISH No.{String(fish.indexOf(f)+1).padStart(3,'0')}</span><h1>{f.name}</h1><p>{f.en}</p><i>{f.scientific}</i><div className="chips"><span>旬 {f.season}</span><span>{'★'.repeat(f.difficulty)}{'☆'.repeat(5-f.difficulty)}</span><span>⚠ {f.danger}</span></div></div><div className="fallbackViewer"><FishArt slug={f.slug} label={`${f.name} 2D illustration`}/><small>2D図鑑イラスト</small></div></section>
 <section className="factsGrid"><article><span>サイズ</span><b>{f.size}</b></article><article><span>水深</span><b>{f.depth}</b></article><article><span>主なエリア</span><b>{f.areas.join('・')}</b></article><article><span>おすすめ</span><b>{f.beginner?'初心者にもおすすめ':'経験者向け'}</b></article></section>
 <section className="detailGrid"><article><span>ABOUT</span><h2>{f.name}ってどんな魚？</h2><p>{f.desc}</p>{d&&<><h3>体の特徴</h3><p>{d.body}</p><h3>釣れる時期</h3><p>{d.seasonNote}</p></>}<div className="months">{Array.from({length:12},(_,i)=>i+1).map(m=><b className={f.months.includes(m)?'on':''} key={m}>{m}月</b>)}</div></article><aside><span>HOW TO CATCH</span><h2>この魚を釣る</h2>{f.methods.map((m,i)=><Link href="/methods" className="methodLink" key={m}><strong>0{i+1}</strong><div><b>{m}</b><small>釣り方・仕掛けを見る</small></div><em>→</em></Link>)}<Link href="/gear" className="gearCta">必要な釣具をまとめて見る →</Link></aside></section>
 {d&&<><section className="detailGrid"><article><span>ECOLOGY</span><h2>生態と暮らし</h2><h3>分類</h3><p>{d.family}・{d.genus}</p><h3>生息場所</h3><p>{d.habitat}</p><h3>エサ</h3><p>{d.diet}</p><h3>行動</h3><p>{d.behavior}</p><h3>寿命</h3><p>{d.lifespan}</p></article><aside><span>BEGINNER GUIDE</span><h2>初めて狙うなら</h2><p>{d.beginnerTip}</p><h3>釣り方のポイント</h3><p>{d.fishing}</p><h3>安全</h3><p>{d.safety}</p></aside></section><section className="detailGrid"><article><span>TABLE</span><h2>食べて楽しむ</h2><p>{d.taste}</p><div className="chips">{d.cooking.map(x=><span key={x}>{x}</span>)}</div></article><aside><span>TRIVIA</span><h2>魚の豆知識</h2><p>{d.trivia}</p>{d.aliases.length>0&&<><h3>別名</h3><p>{d.aliases.join('・')}</p></>}</aside></section></>}
 <LaunchFishExtras slug={slug} name={f.name}/><section className="nextActions"><div><span>NEXT STEP</span><h2>次は、ほんものを釣りに行こう。</h2></div><Link href="/spots">📍 釣れる場所を探す</Link><Link href="/gear">🎣 必要な釣具を見る</Link></section></div>
}
