// Static crawler-friendly JPEG cards generated from the same public registries.
const fs=require('fs'),path=require('path'),Module=require('module'),ts=require('typescript'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),resolve=Module._resolveFilename;Module._resolveFilename=function(s,...a){return resolve.call(this,s.startsWith('@/')?path.join(root,s.slice(2)):s,...a)};
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,f);
const sharp=require(process.env.SHARP_MODULE||'sharp'),{ImageResponse}=require('next/og'),{createElement:h}=require('react');
const {fishCatalog}=require('../lib/fish-registry.ts'),{getFishImage}=require('../lib/fish-images.ts'),{allGuides}=require('../lib/all-guides.ts'),{fishingMapEntries}=require('../lib/fishing-map-data.ts');
async function main(){const entries=[
 ['/', '魚から、釣りへつながる','UOLINK',getFishImage(fishCatalog[0])],['/fish','釣れた魚を、もっと知る','魚図鑑',getFishImage(fishCatalog[1])],['/guide','釣りの疑問を、実釣の力に','GUIDE / QUICK GUIDE',getFishImage(fishCatalog[2])],['/spots','全国の釣り場と船宿を探す','UOLINK MAP'],['/cooking','釣った後の食卓まで','魚料理',getFishImage(fishCatalog[1])],['/identify','この魚なに？','写真から魚の候補を調べる',getFishImage(fishCatalog[1])],
 ...fishCatalog.flatMap(f=>[[`/fish/${f.slug}`,f.name,'特徴・見分け方・釣り方',getFishImage(f)],...(f.cooking?[[`/cooking/${f.slug}`,`${f.name}の料理`,'下処理・材料・レシピ',getFishImage(f)],...f.cooking.recipes.map(r=>[`/cooking/${f.slug}/${r.slug}`,`${f.name}の${r.name}`,'UOLINK RECIPE',r.image??getFishImage(f)])]:[])]),
 ...allGuides.map(g=>[`/guide/${g.slug}`,g.title,g.articleType,getFishImage(fishCatalog.find(f=>g.fishTags.includes(f.slug))??fishCatalog[0])]),
 ...fishingMapEntries.map(s=>[`/spots/${s.slug}`,s.name,`${s.prefecture??s.area} · ${s.type==='boat'?'釣船・船宿':'釣り場ガイド'}`])];
 const chars=[...new Set(Array.from('UOLINKuo_link魚から釣りへつながる'+entries.map(e=>e[1]+e[2]).join('')))].sort().join('');const cache=path.join(root,'.next/cache/social-font');fs.mkdirSync(cache,{recursive:true});const fontFile=path.join(cache,crypto.createHash('sha256').update(chars).digest('hex')+'.ttf');
 if(!fs.existsSync(fontFile)){const css=await fetch('https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@700&text='+encodeURIComponent(chars));if(!css.ok)throw Error('Font CSS '+css.status);const url=(await css.text()).match(/src: url\(([^)]+)\)/)?.[1];if(!url)throw Error('Font missing');const r=await fetch(url);if(!r.ok)throw Error('Font failed');fs.writeFileSync(fontFile,Buffer.from(await r.arrayBuffer()));}
 const font=fs.readFileSync(fontFile),manifest={},out=path.join(root,'public/sharing');fs.mkdirSync(out,{recursive:true});let n=0,max=0;
 for(const [route,title,label,src] of entries){let image;if(src){const file=path.join(root,'public',src.split('?')[0]);if(!fs.existsSync(file))throw Error('Missing '+file);image='data:image/png;base64,'+(await sharp(file).resize(480,340,{fit:'inside',withoutEnlargement:true}).png().toBuffer()).toString('base64');}
 const el=h('div',{style:{display:'flex',flexDirection:'column',width:'100%',height:'100%',padding:'48px 60px',background:'#eaf5f7',color:'#123748',fontFamily:'Noto',fontWeight:700}},h('div',{style:{display:'flex',justifyContent:'space-between',fontSize:28}},h('span',null,'UOLINK'),h('span',{style:{color:'#087ca0'}},label)),h('div',{style:{display:'flex',flex:1,alignItems:'center',gap:28}},h('div',{style:{fontSize:title.length>35?43:54,lineHeight:1.4,width:image?600:1000}},title),image?h('img',{src:image,width:420,height:320,style:{objectFit:'contain'}}):h('div',{style:{display:'flex',fontSize:100,color:'#0a8aa6'}},'↗')),h('div',{style:{display:'flex',justifyContent:'space-between',fontSize:22,paddingTop:20,borderTop:'2px solid #bfd8e1'}},h('span',null,'魚から、釣りへつながる'),h('span',null,'uo_link')));
 const png=Buffer.from(await new ImageResponse(el,{width:1200,height:630,fonts:[{name:'Noto',data:font,weight:700,style:'normal'}]}).arrayBuffer());const jpg=await sharp(png).jpeg({quality:85,chromaSubsampling:'4:4:4'}).toBuffer();const hash=crypto.createHash('sha256').update(jpg).digest('hex').slice(0,12),name=route==='/'?'home':route.slice(1).replaceAll('/','--');const file=`${name}-${hash}.jpg`;fs.writeFileSync(path.join(out,file),jpg);manifest[route]='/sharing/'+file;max=Math.max(max,jpg.length);if(++n%100===0)console.log('Cards',n);}
 fs.writeFileSync(path.join(root,'lib/sharing-images.json'),JSON.stringify(manifest,null,2)+'\n');console.log('Generated',n,'cards; maximum bytes',max);
}
main().catch(e=>{console.error(e);process.exitCode=1});
